import assert from 'node:assert/strict'
import test from 'node:test'
import {readFileSync} from 'node:fs'
import {stripTypeScriptTypes} from 'node:module'
const url=s=>`data:text/javascript;base64,${Buffer.from(s).toString('base64')}`
const read=n=>readFileSync(new URL(`../functions/_shared/${n}.ts`,import.meta.url),'utf8')
const erp=url('export const erpNextOrigin=()=>"https://erp.example";export const erpNextList=()=>{};export const erpNextCreate=()=>{};export const erpNextRequest=()=>{};')
const sync=url(stripTypeScriptTypes(read('accounting-party-sync')).replace('./erpnext.ts',erp))
const backend=url('export class HttpError extends Error { constructor(status,message){super(message);this.status=status} }')
const mod=await import(url(stripTypeScriptTypes(read('accounting-party-review')).replace('./backend.ts',backend).replace('./erpnext.ts',erp).replace('./accounting-party-sync.ts',sync)))
globalThis.Deno={env:{get:()=> 'https://tenant.supabase.co'}}
function fixture(){
 const db={ACCI_PartySyncQueue:[{id:'job',connection_id:'connection',org_id:'org',party_type:'customer',revision:1,status:'blocked',verified_payload:null}],
 ACCI_Connections:[{ACCIC_ID:'connection',ACCIC_StatusCode:'active',ACCIC_ProviderCode:'erpnext',ACCIC_LegalEntityID:'entity',ACCIC_SettingsJSON:{partySync:{enabled:true,siteOrigin:'https://erp.example',customerGroup:'Commercial',territory:'World'}}}],
 cmp_LegalEntities:[{LegalEntity_ID:'entity',Company_ID:'company',LegalEntity_IsActive:true}],CRM_AccountProfiles:[{CRMAccount_OrgID:'org',CRMAccount_CompanyID:'company',CRMAccount_IsDeleted:false}],Org_Master_Type:[{Org_ID:'org',OrgType_ID:'role'}],Org_Types:[{OrgType_ID:'role',OrgType_Name:'Customer'}],
 Org_Master:[{Org_id:'org',Org_Name:'New name',Org_BaseCurrency:'currency'}],CRM_AccountOperationalProfiles:[],sys_Currency:[{Currency_ID:'currency',Currency_Code:'GBP'}],ACCI_PartyMappings:[{ACCIPM_ConnectionID:'connection',ACCIPM_OrgID:'org',ACCIPM_PartyType:'customer',ACCIPM_ProviderPartyID:'ERP-1',ACCIPM_IsActive:true}],RefCountry:[{RN_Code:'GB',RN_Desc:'United Kingdom'}]}
 const record={name:'ERP-1',customer_name:'Old name',customer_type:'Company',customer_group:'Commercial',territory:'World',default_currency:'GBP',modified:'v1'};let writes=0,reviews=0
 const admin={from(table){let result=db[table]??[];const q={select(){return q},eq(k,v){result=result.filter(r=>r[k]===v);return q},neq(k,v){result=result.filter(r=>r[k]!==v);return q},is(k,v){return q.eq(k,v)},in(k,v){result=result.filter(r=>v.includes(r[k]));return q},limit(n){result=result.slice(0,n);return q},maybeSingle(){return Promise.resolve({data:result[0]??null,error:null})},single(){return q.maybeSingle()},then(resolve){return Promise.resolve({data:structuredClone(result),error:null}).then(resolve)}};return q},async rpc(name){if(name==='multideck_accounting_address')return {data:{OrgAdd_ID:'address',OrgAdd_Line1:'1 Example Street',OrgAdd_TownCity:'Exampleton',OrgAdd_Country:'GB'},error:null};assert.equal(name,'multideck_accounting_review_party');reviews++;return {data:null,error:null}}}
 const io={async get(type,id){assert.equal(type,'Customer');assert.equal(id,'ERP-1');return {...record}},async list(type,fields,filters){if(type==='Custom Field')return [{unique:1,fieldtype:'Data'}];if(type==='Address')return [];return filters.every(([k,,v])=>record[k]===v)?[{name:record.name}]:[]},async update(type,id,payload){assert.equal(payload.modified,record.modified);Object.assign(record,payload,{modified:'v2'});writes++;return {...record}},async create(){throw new Error('Review must never create a provider party')}}
 return {admin,io,db,record,counts:()=>({writes,reviews})}
}
test('initial review shows exact existing ID and proposed name change without writing',async()=>{const f=fixture();const r=await mod.reviewPartyIdentities(f.admin,'connection','actor',undefined,f.io);assert.equal(r.reviews.length,1);assert.equal(r.reviews[0].providerId,'ERP-1');assert.deepEqual(r.reviews[0].changes,[{field:'customer_name',from:'Old name',to:'New name'}]);assert.deepEqual(f.counts(),{writes:0,reviews:0})})
test('confirmation attaches identity and queues a baseline without rewriting the name or claiming delivery success',async()=>{const f=fixture();const r=await mod.reviewPartyIdentities(f.admin,'connection','actor',undefined,f.io);const saved=await mod.reviewPartyIdentities(f.admin,'connection','actor',r,f.io);assert.equal(saved.results[0].queued,true);assert.match(f.record.custom_multideck_party_key,/^[a-f0-9]{64}$/);assert.equal(f.record.customer_name,'Old name');assert.equal(saved.fullLedgerReconciled,false);assert.deepEqual(f.counts(),{writes:1,reviews:1})})
test('provider drift after preview fails before any identity write',async()=>{const f=fixture();const r=await mod.reviewPartyIdentities(f.admin,'connection','actor',undefined,f.io);f.record.modified='changed';await assert.rejects(mod.reviewPartyIdentities(f.admin,'connection','actor',r,f.io),/changed since/);assert.deepEqual(f.counts(),{writes:0,reviews:0})})
test('foreign connection and revoked entity cannot be reviewed',async()=>{const f=fixture();await assert.rejects(mod.preparePartyReview(f.admin,'foreign','job',f.io),/no longer/);f.db.cmp_LegalEntities[0].LegalEntity_IsActive=false;await assert.rejects(mod.preparePartyReview(f.admin,'connection','job',f.io),/inactive/);assert.deepEqual(f.counts(),{writes:0,reviews:0})})
test('another tenant identity, missing mapping, processed job and repeated requests fail closed',async()=>{for(const change of [f=>f.record.custom_multideck_party_key='foreign',f=>f.db.ACCI_PartyMappings=[],f=>f.db.ACCI_PartySyncQueue[0].verified_payload={}]){const f=fixture();change(f);await assert.rejects(mod.preparePartyReview(f.admin,'connection','job',f.io));assert.deepEqual(f.counts(),{writes:0,reviews:0})}const f=fixture();await assert.rejects(mod.reviewPartyIdentities(f.admin,'connection','actor',{reviews:[{jobId:'job'},{jobId:'job'}]},f.io),/distinct/);})
