import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

const root = new URL("../../", import.meta.url)
const read = (path) => readFile(new URL(path, root), "utf8")

const migration = await read("supabase/migrations/20260901100000_booking_detail_editing.sql")
const routingMigration = await read("supabase/migrations/20260902153715_booking_multi_leg_routes_and_cargo_dimensions.sql")
const bookingComponents = await read("multideck.client/src/components/multideck/booking-components.tsx")
const bookingApi = await read("multideck.client/src/lib/booking-workflow-api.ts")

test("booking detail edits have a dedicated persisted override boundary", () => {
  assert.match(migration, /add column if not exists "Job_EditableDetailsJSON" jsonb not null default '\{\}'::jsonb/)
  assert.match(migration, /create or replace function booking_api\.save_booking_detail_fields/)
  assert.match(migration, /booking_api\.has_permission\(caller_auth_user_id, 'Bookings\.Write'\)/)
  assert.match(migration, /office\."Company_ID" = app_user\."Company_ID"/)
  assert.match(migration, /jsonb_object_agg\(entry\.key, entry\.value\)/)
  assert.match(migration, /create or replace function booking_api\.workspace_extended/)
  assert.match(migration, /App_UserJobStars/)
  assert.match(migration, /perform booking_api\.save_booking_detail_fields\(caller_auth_user_id, requested_job_id, payload\)/)
  for (const key of ["progress", "lastUpdated", "sourceId", "documentsStatus", "workflowStatus", "routeSummary", "customFields"]) {
    assert.match(migration, new RegExp(`'${key}'`, "u"))
  }
  assert.match(migration, /entry\.key like 'customField:%'/u)
  assert.match(migration, /length\(entry\.key\) <= 180/u)
})

test("the details workspace keeps only booking and quote references locked", () => {
  assert.match(bookingComponents, /BookingCargoWiseField label="Booking ref" value=\{record\.booking\.id\} \/>/)
  assert.match(bookingComponents, /BookingCargoWiseField label="Quote ref" value=\{quoteReference\} \/>/)
  assert.match(bookingComponents, /editDetail\("termsAndConditions"\)/)
  assert.match(bookingComponents, /onPartyChange\(role, field, value\)/)
  assert.match(bookingComponents, /onCargoChange\(index, field, value\)/)
  assert.match(bookingComponents, /onChange=\{onContainerChange\}/)
  assert.match(bookingComponents, /function addDraftContainer\(\)/)
  assert.match(bookingComponents, /function removeDraftContainer\(index: number\)/)
  assert.match(bookingComponents, /containers: workspace\.containers/)
  assert.match(bookingComponents, /onRouteChange\(index, field, value\)/)
  assert.match(bookingComponents, /setLiveJobStarred\(savedWorkspace\.booking\.bookingReference, draftBooking\.isFavourite\)/)
})

test("booking selectors reuse the quote directories and dependent choices", () => {
  assert.match(bookingComponents, /getQuoteSources\(\)/)
  assert.match(bookingComponents, /loadUnlocodeDirectory\(\)/)
  assert.match(bookingComponents, /filterLocationsForMode\(/)
  assert.match(bookingComponents, /freightShipmentAllowed\(modeKey, option\.code\)/)
  assert.match(bookingComponents, /bookingEquipmentOptionsByMode/)
  assert.match(bookingComponents, /options=\{bookingDirectionOptions\}/)
  assert.match(bookingComponents, /options=\{bookingHblModeOptions\}/)
  assert.match(bookingComponents, /options=\{bookingIncotermOptions\}/)
  assert.match(bookingComponents, /options=\{commodityOptions\} searchable/u)
  assert.match(bookingComponents, /options=\{organisationOptions\("customer"\)\} searchable/u)
  assert.match(bookingComponents, /options=\{organisationOptions\("carrier"\)\} searchable/u)
  assert.match(bookingComponents, /function selectDraftOrganisation/u)
  assert.match(bookingComponents, /function selectDraftLocation/u)
  assert.match(bookingComponents, /BookingCargoWiseAmountField label="Booking value"/u)
  assert.match(bookingComponents, /BookingCargoWiseAmountField label="Goods value"/u)
  assert.match(bookingComponents, /BookingCargoWiseField label="Goods description" value=\{goodsDescription\}/u)
  assert.match(bookingComponents, /BookingCargoWiseField label="Known cargo" value=\{knownCargo\}/u)
  assert.match(bookingApi, /knownCargo\?: string \| null/u)
  assert.match(bookingComponents, /mode=\{record\.booking\.mode\}/u)
  assert.match(bookingComponents, /iconText: bookingCountryFlag\(location\.countryCode\)/u)
  assert.match(bookingComponents, /onDetailChange\("quoteType", nextDirection\)/u)
  assert.match(bookingComponents, /bookingQuoteReference\(record\.workspace\)/u)
  assert.match(bookingComponents, /currentUser\?\.name/u)
  assert.match(bookingComponents, /ModeIcon = modeKey === "air" \? Plane/u)
  assert.match(bookingComponents, /normalizedDirection === "import" \? ArrowDownToLine/u)
})

test("booking routing steps and item dimensions persist through the tenant-safe booking boundary", () => {
  assert.match(bookingComponents, /Add routing step/u)
  assert.match(bookingComponents, /workspace\.routes\.map\(\(leg, index\)/u)
  assert.match(bookingComponents, /routes: workspace\.routes\.map/u)
  assert.match(bookingComponents, /modeKey === "ocean" \|\| modeKey === "sea"/u)
  for (const field of ["Length", "Width", "Height", "Dimension unit"]) {
    assert.match(bookingComponents, new RegExp(`label="${field}"`, "u"))
  }
  assert.match(routingMigration, /create or replace function booking_api\.save_booking_route_legs/u)
  assert.match(routingMigration, /jsonb_array_length\(payload->'routes'\) > 30/u)
  assert.match(routingMigration, /office\."Company_ID" = app_user\."Company_ID"/u)
  assert.match(routingMigration, /That routing step does not belong to this booking/u)
  assert.match(routingMigration, /create or replace function booking_api\.save_booking_cargo_measurements/u)
  assert.match(routingMigration, /"JobCargo_Length" = nullif\(line->>'length', ''\)::numeric/u)
  assert.match(routingMigration, /jsonb_array_elements\(coalesce\(result->'cargo', '\[\]'::jsonb\)\) as item\(value\)/u)
  assert.match(routingMigration, /item\.value \|\| jsonb_strip_nulls/u)
  assert.match(routingMigration, /perform booking_api\.save_booking_route_legs/u)
  assert.match(routingMigration, /revoke all on function booking_api\.save_booking_route_legs/u)
  assert.doesNotMatch(routingMigration, /delete from public\."Job_Routing"/u)
  assert.match(routingMigration, /Ordered routing-step and item-dimension editing is not supported in Dexter/u)
  assert.match(routingMigration, /Ordered route-leg and cargo-dimension watches are not supported/u)
  assert.match(bookingComponents, /BookingCargoWiseField label="ETD" value=\{estimatedDeparture\} inputType="date"/u)
  assert.match(bookingComponents, /BookingCargoWiseField label="ETA" value=\{estimatedArrival\} inputType="date"/u)
  assert.match(bookingComponents, /const estimatedDeparture = firstRoute\?\.plannedDepartureAt \|\| record\.booking\.departureDate/u)
  assert.match(bookingComponents, /const estimatedArrival = lastRoute\?\.plannedArrivalAt \|\| record\.booking\.arrivalDate \|\| record\.booking\.eta/u)
  assert.match(bookingComponents, /const lastRoute = workspace\.routes\.at\(-1\) \?\? route/u)
  assert.match(routingMigration, /apply_accepted_quote_schedule_to_new_route/u)
  assert.match(routingMigration, /JobRoute_PlannedDepartureAt/u)
  assert.match(routingMigration, /JobRoute_PlannedArrivalAt/u)
})

test("the client exposes the extended workspace data needed to round-trip edits", () => {
  assert.match(bookingApi, /editableDetails\?: Record<string, unknown>/)
  assert.match(bookingApi, /length\?: number \| null/)
  assert.match(bookingApi, /sealNumber\?: string \| null/)
  assert.match(bookingApi, /export function saveBookingWorkflow\(jobId: string, booking: Record<string, unknown>\)/)
})
