import assert from "node:assert/strict"
import fs from "node:fs"
import test from "node:test"

const migration = fs.readFileSync(new URL("../migrations/20260901164232_seamless_calendar_meetings_booking_links.sql", import.meta.url), "utf8")
const operationalMilestones = fs.readFileSync(new URL("../migrations/20260901230000_calendar_operational_milestones.sql", import.meta.url), "utf8")
const coloursMigration = fs.readFileSync(new URL("../migrations/20260901234500_calendar_meeting_colours.sql", import.meta.url), "utf8")
const parallelConnectionsMigration = fs.readFileSync(new URL("../migrations/20260901233300_parallel_calendar_connections.sql", import.meta.url), "utf8")
const api = fs.readFileSync(new URL("../functions/calendar-api/index.ts", import.meta.url), "utf8")
const publicApi = fs.readFileSync(new URL("../functions/calendar-public/index.ts", import.meta.url), "utf8")
const oauth = fs.readFileSync(new URL("../functions/calendar-oauth/index.ts", import.meta.url), "utf8")
const webhook = fs.readFileSync(new URL("../functions/calendar-webhook/index.ts", import.meta.url), "utf8")
const worker = fs.readFileSync(new URL("../functions/calendar-worker/index.ts", import.meta.url), "utf8")
const bookingCrm = fs.readFileSync(new URL("../functions/_shared/calendar-booking-crm.ts", import.meta.url), "utf8")
const providerAvailability = fs.readFileSync(new URL("../functions/_shared/calendar-provider-availability.ts", import.meta.url), "utf8")
const backend = fs.readFileSync(new URL("../functions/_shared/backend.ts", import.meta.url), "utf8")
const dexter = fs.readFileSync(new URL("../functions/agent-dexter/index.ts", import.meta.url), "utf8")
const app = fs.readFileSync(new URL("../../multideck.client/src/App.tsx", import.meta.url), "utf8")
const gallery = fs.readFileSync(new URL("../../multideck.client/src/data/multideck-data.ts", import.meta.url), "utf8")
const composer = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/mail-composer.tsx", import.meta.url), "utf8")
const managePage = fs.readFileSync(new URL("../../multideck.client/src/pages/meeting-manage-page.tsx", import.meta.url), "utf8")
const bookingPage = fs.readFileSync(new URL("../../multideck.client/src/pages/public-booking-page.tsx", import.meta.url), "utf8")
const connectionSettings = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/calendar-connection-settings.tsx", import.meta.url), "utf8")

test("calendar data remains service-only and permission bounded", () => {
  for (const permission of ["Calendar.Read", "Calendar.ManageOwn", "Calendar.ManageAll", "Calendar.Connect", "Calendar.BookingLinks.Manage", "Calendar.Templates.Manage"]) {
    assert.match(migration, new RegExp(permission.replace(".", "\\.")))
  }
  assert.match(migration, /enable row level security/)
  assert.match(migration, /revoke all on table public\.%I from public, anon, authenticated/)
  assert.match(migration, /grant all on table[\s\S]*to service_role/)
  assert.match(api, /can\(permissions, "Calendar\.Read"\)/)
  assert.match(backend, /Access-Control-Allow-Headers[^\n]*x-multideck-meeting-source/)
  assert.match(oauth, /permissionValues\(admin, actor\.User_ID\)/)
  assert.match(oauth, /includes\("Calendar\.Connect"\)/)
})

test("operational ribbons inherit Bookings and Warehouse access boundaries", () => {
  assert.match(api, /can\(permissions, "Bookings\.Read"\)/)
  assert.match(api, /can\(permissions, "Warehouse\.Read"\)/)
  assert.match(api, /multideck_calendar_job_milestones/)
  assert.match(api, /cmp_Users_Offices/)
  assert.match(api, /WMSFacility_OrgOfficeID/)
  assert.match(api, /\.in\("WMSOrder_FacilityID", facilityIds\)/)
  assert.doesNotMatch(api, /WMSOrder_CreatedBy/)
  assert.doesNotMatch(api, /Job_CreatedBy", actor\.User_ID/)
  assert.match(operationalMilestones, /security definer/)
  assert.match(operationalMilestones, /office\."Company_ID" = p_company_id/)
  assert.match(operationalMilestones, /'collection'::text/)
  assert.match(operationalMilestones, /'departure'/)
  assert.match(operationalMilestones, /'arrival'/)
  assert.match(operationalMilestones, /'delivery'/)
  assert.match(operationalMilestones, /revoke all on function[\s\S]*from public, anon, authenticated/)
  assert.match(operationalMilestones, /grant execute on function[\s\S]*to service_role/)
})

test("public booking uses ten-minute holds, verification and participant-bound management", () => {
  assert.match(migration, /"CAL_BookingHolds"/)
  assert.match(migration, /"CAL_ManagementTokens"/)
  assert.match(migration, /"CALManagementToken_ParticipantID" uuid not null/)
  assert.match(migration, /"CALManagementToken_SecretRef" varchar\(240\) not null/)
  assert.match(migration, /_multideck_calendar_delete_management_secret/)
  assert.match(publicApi, /10 \* 60_000/)
  assert.match(migration, /multideck_calendar_consume_public_rate_limit/)
  assert.match(migration, /on conflict \("CALRateLimit_CompanyID","CALRateLimit_ActionCode","CALRateLimit_SubjectHash","CALRateLimit_WindowStartedAt"\)/)
  assert.match(publicApi, /admin\.rpc\("multideck_calendar_consume_public_rate_limit"/)
  assert.match(publicApi, /cleanText\(payload\.website, 200\)\) return \{ accepted: true \}/)
  assert.match(bookingPage, /aria-hidden="true">Website<Input tabIndex=\{-1\} autoComplete="off"/)
  assert.match(migration, /multideck_calendar_record_verification_failure/)
  assert.match(migration, /for update;[\s\S]*CALBookingHold_VerificationAttempts/)
  assert.match(publicApi, /admin\.rpc\("multideck_calendar_record_verification_failure"/)
  assert.match(publicApi, /CALBookingHold_VerificationHash/)
  assert.match(publicApi, /rendered\.text\.replaceAll\(code, "••••••"\)/)
  assert.match(publicApi, /defaultCalendarEmailTemplate\("booking_verification"\)/)
  assert.match(publicApi, /Verification is always Multideck-owned[\s\S]*brand: undefined/)
  assert.match(publicApi, /readAvailability\(admin, row/)
  assert.match(publicApi, /CALBookingHold_VerifiedAt/)
  assert.match(publicApi, /secureManagementToken\(admin, participant\.CALParticipant_ID, managementToken\)/)
  assert.match(publicApi, /CALBookingLink_RescheduleCutoffMinutes/)
  assert.match(publicApi, /The rescheduling window for this meeting has closed/)
  assert.match(publicApi, /path\[2\] === "slots"/)
  assert.match(publicApi, /readManagedAvailability/)
  assert.match(publicApi, /excludeReservationId: state\.meeting\.CALMeeting_ReservationID/)
  assert.match(publicApi, /providerBusyRanges\(admin, state\.meeting\.CALMeeting_OrganiserUserID/)
  assert.match(managePage, /getManagedMeetingSlots/)
  assert.doesNotMatch(managePage, /This meeting was scheduled internally/)
  assert.match(worker, /secretValue\(admin, existing\.CALManagementToken_SecretRef\)/)
  assert.match(publicApi, /if \(hold\.CALBookingHold_MeetingID\)[\s\S]*bookingConfirmation\(admin, row, hold, existingMeeting\)/)
  assert.match(publicApi, /CAL_MeetingParticipants"\)\.upsert/)
  assert.match(publicApi, /CALDelivery_KindCode: "crm_link"/)
  assert.match(publicApi, /restoreManagedMeetingSnapshot/)
  assert.match(publicApi, /CALMeeting_PendingChangeJSON: \{ kind: "attendee_cancel"/)
  assert.match(worker, /activeAttendees\.map/)
  assert.match(worker, /pendingKind === "attendee_cancel"/)
  assert.match(migration, /UX_CAL_ChangeRequests_participant_pending/)
})

test("booking retries stay idempotent and CRM linking cannot undo a confirmed provider event", () => {
  assert.match(migration, /multideck_calendar_finalise_verified_hold/)
  assert.match(migration, /on conflict \("CALMeeting_ReservationID"\) do nothing/)
  assert.match(migration, /CALReservation_SourceCode"='meeting'[\s\S]*CALBookingHold_VerifiedAt/)
  assert.match(publicApi, /admin\.rpc\("multideck_calendar_finalise_verified_hold"/)
  assert.match(publicApi, /Your booking is saved but is still being prepared/)
  assert.match(publicApi, /availability range of 90 days or fewer/)
  assert.match(migration, /multideck_calendar_match_or_create_booking_lead/)
  assert.match(migration, /pg_advisory_xact_lock/)
  assert.match(migration, /lower\(btrim\(lead\."CRMLead_Email"\)\) = v_email/)
  assert.match(migration, /UX_CRM_Activities_calendar_meeting/)
  assert.match(migration, /'provider_cancel','crm_link','booking_verification'/)
  assert.match(bookingCrm, /linkBookingMeetingToCrm/)
  assert.match(worker, /if \(kind === "crm_link"\)/)
  assert.match(worker, /providerCreationAlreadyConfirmed/)
  assert.match(worker, /currentMeeting\?\.CALMeeting_StatusCode === "confirmed"/)
  assert.doesNotMatch(worker, /createBookingLeadAfterProvision/)
  assert.match(bookingPage, /Confirmation is taking longer than expected/)
  assert.match(bookingPage, /This booking was not confirmed/)
  assert.match(bookingPage, /Check status/)
})

test("provider boundaries use PKCE, state, authenticated webhooks and exact callbacks", () => {
  assert.match(oauth, /request\.method === "OPTIONS"[\s\S]*204/)
  assert.match(oauth, /code_challenge_method: "S256"/)
  assert.match(oauth, /CALOAuthState_StateHash/)
  assert.match(oauth, /CALOAuthState_ConsumedAt/)
  assert.match(oauth, /\.is\("CALOAuthState_ConsumedAt", null\)[\s\S]*\.gt\("CALOAuthState_ExpiresAt", consumedAt\)[\s\S]*\.select\("\*"\)\.maybeSingle\(\)/)
  assert.match(oauth, /isTrustedMultideckOrigin/)
  assert.match(oauth, /CALConnection_SyncCursor: null/)
  assert.match(oauth, /CALConnection_SubscriptionSecretRef: null/)
  assert.match(oauth, /CAL_ProviderEvents"\)\.delete\(\)\.eq\("CALProviderEvent_ConnectionID"/)
  assert.match(oauth, /calendar_connection", "syncing"/)
  assert.match(oauth, /class ProviderOAuthError extends HttpError/)
  for (const reason of ["credentials_rejected", "authorization_rejected", "renewable_token_missing", "identity_unavailable", "provider_exchange_failed"]) {
    assert.match(oauth, new RegExp(`"${reason}"`))
    assert.match(connectionSettings, new RegExp(`reason === "${reason}"`))
  }
  assert.match(connectionSettings, /Calendar" : "Zoom"} authorised/)
  assert.match(connectionSettings, /verifying the connection and preparing the first sync/)
  assert.match(webhook, /CALWebhookReceipt_DeliveryKey/)
  assert.match(webhook, /clientState|x-goog-channel-token|authorization/i)
  assert.match(webhook, /Repeating this update is intentional/)
  assert.match(webhook, /enqueueZoomMeetingUpdate/)
  assert.match(webhook, /zoom-webhook:/)
  assert.match(webhook, /CALMeeting_EditVersion: Number\(meeting\.CALMeeting_EditVersion\) \+ 1/)
  assert.match(worker, /events\/watch/)
  assert.match(worker, /graph\.microsoft\.com\/v1\.0\/subscriptions/)
  assert.match(backend, /multideck-app-\[a-z0-9-\]\+-databrain-solutions\\\.vercel\\\.app/)
  assert.match(backend, /APP_PREVIEW_ORIGIN/)
  assert.match(backend, /APP_ALLOWED_ORIGINS/)
})

test("Zoom declares all user-scoped permissions needed for the meeting lifecycle", () => {
  const scopes = oauth.match(/zoom: \[([^\]]+)\]/)?.[1] ?? ""
  for (const scope of ["meeting:write:meeting", "meeting:read:meeting", "meeting:update:meeting", "meeting:delete:meeting", "user:read:user"]) {
    assert.ok(scopes.includes(`"${scope}"`), `Missing Zoom scope: ${scope}`)
  }
  assert.doesNotMatch(scopes, /:admin|:master|recording|transcript/)
})

test("Google and Microsoft calendars can stay connected together with distinct colours", () => {
  assert.match(parallelConnectionsMigration, /CALConnection_ColourCode/)
  assert.match(parallelConnectionsMigration, /when 'google' then 'blue'/)
  assert.match(parallelConnectionsMigration, /when 'microsoft' then 'violet'/)
  assert.match(parallelConnectionsMigration, /CK_CAL_ProviderConnections_colour/)
  assert.match(oauth, /existing\?\.CALConnection_IsPrimaryCalendar === true \|\| !primary/)
  assert.doesNotMatch(oauth, /CALConnection_IsPrimaryCalendar: provider !== "zoom",/)
  assert.match(providerAvailability, /\.in\("CALConnection_ProviderCode", \["google", "microsoft"\]\)/)
  assert.doesNotMatch(providerAvailability, /\.eq\("CALConnection_IsPrimaryCalendar", true\)/)
  assert.match(api, /path\[0\] === "connections"[\s\S]*updateConnectionColour/)
  assert.match(api, /const source = connection\?\.provider \?\? null[\s\S]*calendarSource: source/)
  assert.match(api, /colour: connection\?\.colour \?\? "neutral"/)
  assert.match(connectionSettings, /Connect Google Calendar and Microsoft Calendar together/)
  assert.match(connectionSettings, /<MeetingColourPicker/)
  assert.match(connectionSettings, /updateCalendarConnectionColour\(provider, colour\)/)
  assert.doesNotMatch(connectionSettings, /Only one primary calendar can be connected/)
  assert.match(dexter, /Settings > Integrations for Google or Microsoft Calendar colours/)
})

test("reminders and provider updates are durable, idempotent and compensating", () => {
  assert.match(migration, /tsrange\([\s\S]*timezone\('UTC', "CALReservation_StartAt"\)[\s\S]*timezone\('UTC', "CALReservation_EndAt"\)/)
  assert.doesNotMatch(migration, /tstzrange\(\s*"CALReservation_StartAt"\s*-/)
  assert.match(migration, /multideck_calendar_claim_deliveries/)
  assert.match(migration, /for update skip locked/)
  assert.match(migration, /IX_CAL_Deliveries_due[\s\S]*where "CALDelivery_StatusCode" in \('pending','leased'\)/)
  assert.match(migration, /IX_CAL_ProviderConnections_sync/)
  assert.match(migration, /IX_CAL_ProviderEvents_owner_range/)
  assert.match(migration, /IX_CAL_ManagementTokens_participant_active/)
  assert.match(migration, /IX_CAL_ChangeRequests_meeting_status/)
  assert.match(migration, /_multideck_calendar_refresh_reminders/)
  assert.match(migration, /CALDelivery_IdempotencyKey/)
  assert.match(migration, /CALDelivery_StatusCode" = 'cancelled'/)
  assert.match(worker, /compensatePartialProviderMeeting/)
  assert.match(worker, /deterministicEventId/)
  assert.match(worker, /persistProviderReference/)
  assert.match(worker, /deleteProviderMeeting/)
  assert.match(worker, /if \(url\) throw new HttpError\(502, "Google Calendar returned too many changes/)
  assert.match(worker, /if \(url\) throw new HttpError\(502, "Microsoft Calendar returned too many changes/)
  assert.match(worker, /Provider cleanup needs operator attention; the time remains reserved/)
  assert.match(worker, /!providerMirror/)
  assert.match(worker, /scheduledVersion !== Number\(state\.meeting\.CALMeeting_EditVersion\)/)
  assert.match(worker, /Idempotency-Key/)
  assert.match(worker, /attempts < 3/)
  assert.match(worker, /if \(meetingUpdateError\) throw meetingUpdateError/)
  assert.match(worker, /if \(providerEventError\) throw providerEventError/)
  assert.match(worker, /if \(deliveryUpdateError\) throw deliveryUpdateError/)
  assert.match(providerAvailability, /CALBookingLink_ProviderCode", meetingProvider/)
  assert.match(providerAvailability, /too many events in this range to calculate availability safely/)
  assert.match(api, /removeIncompleteMeeting/)
  assert.match(api, /restorePendingMeetingSnapshot/)
  assert.match(api, /restoreStandaloneMeetingSnapshot/)
  assert.match(api, /The meeting could not queue its provider and attendee updates/)
  assert.match(api, /The cancellation could not be sent to the meeting provider/)
  assert.match(api, /The approved time could not be queued for attendees/)
})

test("Calendar has native routes, email insertion and reusable gallery patterns", () => {
  assert.match(app, /route === "\/calendar"/)
  assert.match(app, /route === "\/calendar\/booking-links"/)
  assert.match(app, /isPublicBookingRoute\(route\)/)
  assert.match(app, /isMeetingManageRoute\(route\)/)
  assert.match(composer, /Insert booking link/)
  assert.match(gallery, /id: "calendar-view"/)
  assert.match(gallery, /id: "calendar-day-ribbon"/)
  assert.match(gallery, /id: "availability-picker"/)
  assert.match(gallery, /route: "\/warehouse\/calendar"/)
  for (const id of ["meeting-time-picker", "meeting-provider-select", "meeting-colour-picker", "meeting-attendee-picker", "meeting-attendee-status"]) {
    assert.match(gallery, new RegExp(`id: "${id}"`))
  }
})

test("calendar colours are bounded, editable and remain visual-only", () => {
  const picker = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/meeting-colour-picker.tsx", import.meta.url), "utf8")
  const dialog = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/meeting-dialog.tsx", import.meta.url), "utf8")
  const popover = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/meeting-details-popover.tsx", import.meta.url), "utf8")
  const calendarView = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/calendar-view.tsx", import.meta.url), "utf8")
  assert.match(coloursMigration, /CALMeeting_ColourCode/)
  assert.match(coloursMigration, /'teal','amber','blue','violet','rose','red','cyan','neutral'/)
  assert.match(api, /appearanceOnly/)
  assert.match(api, /CALMeeting_ColourCode: nextColour/)
  assert.match(api, /colour: row\.CALMeeting_ColourCode/)
  assert.match(dialog, /<MeetingColourPicker value=\{draft\.colour\}/)
  assert.match(popover, /event\.canEdit && mode === "reschedule"/)
  assert.match(popover, /label="Edit event" icon=\{Pen01\}/)
  assert.match(popover, /updateMeeting\(event\.id, patch\)/)
  assert.match(popover, /patch\.colour = colour/)
  assert.match(popover, /if \(!Object\.keys\(patch\)\.length\)/)
  assert.match(popover, /"Save changes"/)
  assert.doesNotMatch(popover, /async function changeColour/)
  assert.match(picker, /meetingColourOptions/)
  assert.match(calendarView, /overlap === "contained" \? 8 : 4/)
  assert.match(calendarView, /overlapBoundary=\{overlap !== "none"\} contained=\{overlap === "contained"\}/)
  assert.match(dexter, /Calendar event colours are visual-only operator preferences/)
})

test("verification stays Multideck-owned while operational meeting emails remain tenant-brandable", () => {
  const emailTemplates = fs.readFileSync(new URL("../functions/_shared/calendar-email-templates.ts", import.meta.url), "utf8")
  const emailRenderer = fs.readFileSync(new URL("../functions/_shared/email-template.ts", import.meta.url), "utf8")
  const templateSettings = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/meeting-email-template-settings.tsx", import.meta.url), "utf8")
  assert.match(emailTemplates, /TENANT_CUSTOMISABLE_CALENDAR_EMAIL_TEMPLATE_KINDS[\s\S]*kind !== "booking_verification"/)
  assert.match(emailTemplates, /return TENANT_CUSTOMISABLE_CALENDAR_EMAIL_TEMPLATE_KINDS\.map/)
  assert.match(api, /Choose a tenant-brandable meeting email template\./)
  assert.match(templateSettings, /useState<MeetingEmailTemplateKind>\("management"\)/)
  assert.doesNotMatch(emailRenderer, /ui-monospace|SFMono-Regular|Menlo,monospace/)
})

test("the shared meeting composer preserves Calendar and CRM context in a centred modal", () => {
  const dialog = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/meeting-dialog.tsx", import.meta.url), "utf8")
  const picker = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/meeting-attendee-picker.tsx", import.meta.url), "utf8")
  const shell = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/app-shell.tsx", import.meta.url), "utf8")
  assert.match(dialog, /<Dialog open=\{Boolean\(context\)\}/)
  assert.match(dialog, /<DialogContent[^\n]*sm:max-w-\[620px\]/)
  assert.match(dialog, /context\?\.source === "crm" \? "CRM meeting" : "New meeting"/)
  assert.doesNotMatch(dialog, /SideDrawer/)
  assert.match(dialog, /"Schedule meeting"/)
  assert.match(dialog, /Creating \$\{meetingProviderLabels\[draft\.provider\]\} link…/)
  assert.match(dialog, /Sending invitations…/)
  assert.match(dialog, /defaultMeetingProviderForInbox\(resolveDefaultInboxProvider\(mailboxes, preferred\)\)/)
  assert.match(dialog, /FALLBACK_PROVIDER: CalendarProvider = "multideck"/)
  assert.match(dialog, /isMeetingProviderReady\(preferredProvider, providerConnections\) \? preferredProvider : "multideck"/)
  assert.match(shell, /<MeetingDialogHost navigate=\{navigate\} \/>/)
  assert.match(picker, /searchMeetingPeople/)
  assert.match(api, /path\[0\] === "people" && path\.length === 1 && request\.method === "GET"/)
  assert.match(api, /\.eq\("Company_ID", actor\.Company_ID\)\.eq\("User_AccessStatus", "active"\)/)
  assert.match(api, /multideck_crm_accessible_account_ids/)
  assert.match(api, /\.eq\("CRMLead_IsDeleted", false\)\.not\("CRMLead_Email", "is", null\)/)
  assert.match(api, /deliberately adds no new Dexter domain or watch adapter/)
})

test("meeting details open beside the event and availability lives in Profile settings", () => {
  const popover = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/meeting-details-popover.tsx", import.meta.url), "utf8")
  const calendarPage = fs.readFileSync(new URL("../../multideck.client/src/pages/calendar-page.tsx", import.meta.url), "utf8")
  const calendarView = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/calendar-view.tsx", import.meta.url), "utf8")
  const calendarPeriodCore = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/calendar-period-core.ts", import.meta.url), "utf8")
  const warehouseCalendar = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/warehouse-components.tsx", import.meta.url), "utf8")
  const availability = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/availability-settings.tsx", import.meta.url), "utf8")
  const settings = fs.readFileSync(new URL("../../multideck.client/src/pages/settings-page.tsx", import.meta.url), "utf8")
  const bookingLinks = fs.readFileSync(new URL("../../multideck.client/src/pages/booking-links-page.tsx", import.meta.url), "utf8")
  // The card anchors to the clicked event block and reuses the composer's time picker to reschedule in place.
  assert.match(calendarView, /onOpen\(event, click\.currentTarget\)/)
  assert.match(popover, /<PopoverAnchor virtualRef=/)
  assert.match(popover, /<MeetingTimePicker startAt=\{times\.startAt\}/)
  assert.match(popover, /<MeetingAttendeeList participants=\{participants\} maxVisible=\{4\}/)
  assert.match(popover, /updateMeeting\(event\.id, \{ action: "cancel" \}\)/)
  assert.match(calendarPage, /<MeetingDetailsPopover selection=\{selected\}/)
  // Calendar and Warehouse share the same period engine while keeping their own event cards and change review.
  assert.match(calendarPeriodCore, /export function calendarPeriodDates/)
  assert.match(calendarView, /calendarPeriodDates\(view, anchor, true\)/)
  assert.match(warehouseCalendar, /calendarPeriodDates\(view, anchorDate\)/)
  assert.match(calendarView, /overlapBoundary && "after:pointer-events-none after:absolute after:inset-0 after:rounded-\[inherit\] after:border-2 after:border-\[var\(--md-surface\)\]"/)
  assert.doesNotMatch(calendarView, /overlapBoundary && "border-2 border-white"/)
  // Empty slots honour the visible timezone, and drag-to-move must stop at a compact attendee-impact review.
  assert.match(calendarView, /zonedToIso\(calendarDateKey\(day\)/)
  assert.match(calendarView, /onReviewMove\(event, startAt/)
  assert.match(calendarPage, /Review new meeting time/)
  assert.match(calendarPage, /Nothing changes until you confirm/)
  assert.match(calendarPage, /updateCalendarEvent\(pendingMove\.event, \{ startAt: pendingMove\.startAt/)
  assert.doesNotMatch(calendarPage, /SideDrawer|AvailabilityDrawer|MeetingDetailsDrawer/)
  // Availability is a Profile settings panel, deep-linkable from Calendar and booking links.
  assert.match(settings, /<AvailabilitySettingsPanel[\s\S]*id="availability-settings"/)
  assert.match(availability, /saveCalendarAvailability\(draft\)/)
  assert.match(availability, /<WorkingHoursEditor value=\{draft\.workingHours\}/)
  assert.match(calendarView, /navigate\("\/settings\?tab=availability"\)/)
  assert.match(bookingLinks, /<WorkingHoursEditor value=\{availability\}/)
  assert.match(bookingLinks, /Archive this booking link\?/)
  assert.match(bookingLinks, /updateBookingLink\(archiveTarget\.id, \{ status: "archived" \}\)/)
  assert.match(gallery, /id: "working-hours-editor"/)
})

test("Dexter and Watching for you expose explicit Calendar capabilities", () => {
  assert.match(migration, /multideck_dexter_domain_calendar/)
  assert.match(migration, /multideck_dexter_domain_booking_links/)
  for (const action of ["create_meeting", "reschedule_meeting", "cancel_meeting", "approve_meeting_change", "create_booking_link", "edit_booking_link", "pause_booking_link"]) {
    assert.match(migration, new RegExp(`'${action}'`))
  }
  assert.match(migration, /_multideck_calendar_watch_signal/)
  assert.match(migration, /CAL_ChangeRequests/)
  assert.match(dexter, /calendar domain contains the operator's canonical Multideck meetings/)
  assert.match(dexter, /booking_links domain contains the operator's personal reusable booking types/)
  assert.match(dexter, /Use create_meeting, reschedule_meeting, cancel_meeting and approve_meeting_change/)
  assert.match(dexter, /Use create_booking_link, edit_booking_link and pause_booking_link/)
  assert.doesNotMatch(dexter, /create and edit flows stay in Calendar > Booking links/)
})

test("booking links support kinds, hosts and a custom public form with required fields", () => {
  const kindsMigration = fs.readFileSync(new URL("../migrations/20260902160000_calendar_booking_kinds_external_events.sql", import.meta.url), "utf8")
  const builder = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/booking-link-builder.tsx", import.meta.url), "utf8")
  const bookingLinks = fs.readFileSync(new URL("../../multideck.client/src/pages/booking-links-page.tsx", import.meta.url), "utf8")
  // Schema: kind on the link, a hosts join table, and the assigned host recorded on each hold.
  assert.match(kindsMigration, /CALBookingLink_KindCode/)
  assert.match(kindsMigration, /in \('one_on_one','round_robin','collective'\)/)
  assert.match(kindsMigration, /create table if not exists public\."CAL_BookingLinkHosts"/)
  assert.match(kindsMigration, /CALBookingHold_HostUserID/)
  // Finalising a verified hold makes the assigned host the organiser and invites collective co-hosts.
  assert.match(kindsMigration, /v_host := coalesce\(v_hold\."CALBookingHold_HostUserID", v_link\."CALBookingLink_OwnerUserID"\)/)
  assert.match(kindsMigration, /if v_link\."CALBookingLink_KindCode"='collective' then/)
  // API validates kinds and active hosts; owner is always a host; question types and choice options are bounded.
  assert.match(api, /BOOKING_LINK_KINDS = new Set\(\["one_on_one", "round_robin", "collective"\]\)/)
  assert.match(api, /const ids = \[\.\.\.new Set\(\[actor\.User_ID, \.\.\.requested\]\)\]/)
  assert.match(api, /\.eq\("User_AccessStatus", "active"\)\.in\("User_ID", ids\)/)
  assert.match(api, /BOOKING_QUESTION_TYPES = new Set\(\["short_text", "long_text", "email", "phone", "number", "select", "checkbox"\]\)/)
  assert.match(api, /needs at least one choice/)
  assert.match(api, /path\[0\] === "booking-links" && path\[1\] === "hosts"/)
  // Public availability is the union of hosts for round robin and the intersection for collective; the least-booked free host wins.
  assert.match(publicApi, /function readHostAvailability/)
  assert.match(publicApi, /kind === "round_robin" \? hostIds\.length > 0 : hostIds\.length === hosts\.length/)
  assert.match(publicApi, /async function assignHost/)
  assert.match(publicApi, /function answerFor\(question: PublicQuestion, raw: unknown\)/)
  assert.match(publicApi, /must be ticked to continue/)
  assert.match(publicApi, /Choose one of the listed options/)
  // Builder UI: name-then-customise flow, kind picker, host picker with provider readiness, and typed required questions.
  assert.match(bookingLinks, /function NewBookingLinkDialog/)
  assert.match(bookingLinks, /Create and customise/)
  assert.match(bookingLinks, /<SegmentedControl options=\{drawerSections\}/)
  assert.match(bookingLinks, /<BookingLinkKindPicker value=\{kind\}/)
  assert.match(bookingLinks, /<BookingHostPicker value=\{hostUserIds\}/)
  assert.match(bookingLinks, /<BookingQuestionBuilder value=\{questions\}/)
  assert.match(builder, /role="radiogroup" aria-label="Booking link type"/)
  assert.match(builder, /not connected \{meetingProviderLabels\[provider\]\}/)
  assert.match(builder, /question\.type === "select" \?[\s\S]*<TagEntryField/)
  assert.match(builder, /aria-label=\{`Require \$\{question\.label/)
  // The public form renders every question type and validates before the hold request.
  assert.match(bookingPage, /if \(type === "checkbox"\)/)
  assert.match(bookingPage, /if \(type === "select"\)/)
  assert.match(bookingPage, /needs a valid phone number/)
  for (const id of ["booking-link-kind-picker", "booking-host-picker", "booking-question-builder"]) assert.match(gallery, new RegExp(`id: "${id}"`))
})

test("synced Google and Microsoft events can be moved, renamed and deleted from Multideck", () => {
  const kindsMigration = fs.readFileSync(new URL("../migrations/20260902160000_calendar_booking_kinds_external_events.sql", import.meta.url), "utf8")
  const providerEvents = fs.readFileSync(new URL("../functions/_shared/calendar-provider-events.ts", import.meta.url), "utf8")
  const popover = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/meeting-details-popover.tsx", import.meta.url), "utf8")
  const calendarPage = fs.readFileSync(new URL("../../multideck.client/src/pages/calendar-page.tsx", import.meta.url), "utf8")
  const calendarApi = fs.readFileSync(new URL("../../multideck.client/src/lib/calendar-api.ts", import.meta.url), "utf8")
  // Edits are owner-bound, never touch Multideck-managed mirrors, respect private titles and write straight to the provider.
  assert.match(api, /path\[0\] === "external-events" && path\[1\] && path\.length === 2 && request\.method === "PATCH"/)
  assert.match(api, /\.eq\("CALProviderEvent_OwnerUserID", actor\.User_ID\)/)
  assert.match(providerEvents, /CALProviderEvent_MeetingID/)
  assert.match(providerEvents, /IsPrivate[\s\S]*title/)
  assert.match(providerEvents, /googleapis\.com\/calendar\/v3\/calendars/)
  assert.match(providerEvents, /graph\.microsoft\.com\/v1\.0\/me\/events/)
  assert.match(providerEvents, /status === 401/)
  assert.match(providerEvents, /status === 403/)
  // Dexter changes go through the durable delivery queue; the worker performs the provider write.
  assert.match(kindsMigration, /'external_event_update','external_event_cancel'/)
  assert.match(kindsMigration, /multideck_dexter_domain_external_events/)
  assert.match(kindsMigration, /'update_external_event'/)
  assert.match(kindsMigration, /'delete_external_event'/)
  assert.match(worker, /external_event_update/)
  assert.match(worker, /pushExternalEventChange/)
  assert.match(dexter, /external_events domain contains Google and Microsoft calendar events/)
  assert.match(dexter, /domain === "external_events"/)
  // Watching for you reacts to mirrored-event changes without polling a model.
  assert.match(kindsMigration, /CAL_ProviderEvents[\s\S]*_multideck_calendar_watch_signal/)
  // UI: one dispatcher decides between meeting and external updates; the popover offers rename, move and delete for editable synced events.
  assert.match(calendarApi, /export async function updateExternalEvent/)
  assert.match(calendarApi, /export async function updateCalendarEvent/)
  assert.match(popover, /updateExternalEvent\(event\.id, \{ action: "cancel" \}\)/)
  assert.match(popover, /Synced from/)
  assert.match(calendarPage, /Move this event\?/)
})

test("calendar blocks drag across days with a kanban-style lift and a quiet hover", () => {
  const calendarView = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/calendar-view.tsx", import.meta.url), "utf8")
  const drag = fs.readFileSync(new URL("../../multideck.client/src/lib/calendar-drag.ts", import.meta.url), "utf8")
  const popover = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/meeting-details-popover.tsx", import.meta.url), "utf8")
  const styles = fs.readFileSync(new URL("../../multideck.client/src/styles.css", import.meta.url), "utf8")
  const attendees = fs.readFileSync(new URL("../../multideck.client/src/components/multideck/meeting-attendee-status.tsx", import.meta.url), "utf8")
  assert.match(drag, /export function useCalendarEventDrag/)
  assert.match(drag, /export function useCalendarDayDrag/)
  assert.match(drag, /data-calendar-day/)
  assert.match(calendarView, /useCalendarDayDrag/)
  assert.match(calendarView, /hover:brightness-\[\.97\]/)
  assert.doesNotMatch(calendarView, /hover:-translate-y-px/)
  assert.match(styles, /--md-shadow-popover/)
  assert.match(popover, /shadow-\[var\(--md-shadow-popover\)\]/)
  assert.match(attendees, /filterable/)
  assert.match(popover, /filterable=\{participants\.length > 6\}/)
})
