import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import { stripTypeScriptTypes } from "node:module"
import test from "node:test"

const source = await readFile(new URL("../functions/company-event-image/core.ts", import.meta.url), "utf8")
const { eventImagePrompt, falImageUrl, isWebp } = await import(`data:text/javascript,${encodeURIComponent(stripTypeScriptTypes(source))}`)

test("event cover prompt uses the occasion and location without asking for lettering", () => {
  const prompt = eventImagePrompt({
    title: "Summer social", location: "Roof terrace, Leeds", details: "Informal team dinner at sunset", startsAt: "2026-10-02T18:00:00Z",
  })
  assert.match(prompt, /Summer social/)
  assert.match(prompt, /Roof terrace, Leeds/)
  assert.match(prompt, /Informal team dinner at sunset/)
  assert.match(prompt, /21:9/)
  assert.match(prompt, /Do not add words/)
})

test("generated image downloads stay on fal media hosts", () => {
  assert.equal(falImageUrl("https://v3b.fal.media/files/example.webp").hostname, "v3b.fal.media")
  for (const url of ["http://v3b.fal.media/a", "https://fal.media.evil.test/a", "https://127.0.0.1/a", "https://user@fal.media/a"]) {
    assert.throws(() => falImageUrl(url))
  }
})

test("generated bytes must actually be WebP", () => {
  assert.equal(isWebp(new TextEncoder().encode("RIFF\u0000\u0000\u0000\u0000WEBPdata")), true)
  assert.equal(isWebp(new TextEncoder().encode("not an image")), false)
})
