import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"

const migration = readFileSync(new URL("../migrations/20260803150000_crm_shawn_essentials.sql", import.meta.url), "utf8")
const companyDashboard = readFileSync(new URL("../migrations/20260808000440_crm_dashboard_company_deals.sql", import.meta.url), "utf8")
const dexter = readFileSync(new URL("../migrations/20260803152000_dexter_crm_essentials.sql", import.meta.url), "utf8")
const followUps = readFileSync(new URL("../migrations/20260803212017_crm_follow_up_opportunities.sql", import.meta.url), "utf8")
const contextualFollowUps = readFileSync(new URL("../migrations/20260824153000_contextual_follow_up_recommendations.sql", import.meta.url), "utf8")
const page = readFileSync(new URL("../../multideck.client/src/pages/crm-page.tsx", import.meta.url), "utf8")
const homePage = readFileSync(new URL("../../multideck.client/src/pages/home-page.tsx", import.meta.url), "utf8")
const homeFollowUps = readFileSync(new URL("../../multideck.client/src/lib/home-follow-ups.ts", import.meta.url), "utf8")
const app = readFileSync(new URL("../../multideck.client/src/App.tsx", import.meta.url), "utf8")
const translations = readFileSync(new URL("../../multideck.client/src/i18n/translate.ts", import.meta.url), "utf8")
const forms = readFileSync(new URL("../../multideck.client/src/pages/crm-forms-page.tsx", import.meta.url), "utf8")
const dashboard = readFileSync(new URL("../../multideck.client/src/components/multideck/crm-dashboard.tsx", import.meta.url), "utf8")
const crmComponents = readFileSync(new URL("../../multideck.client/src/components/multideck/crm-components.tsx", import.meta.url), "utf8")
const pipelineEditor = readFileSync(new URL("../../multideck.client/src/components/multideck/crm-pipeline-editor.tsx", import.meta.url), "utf8")
const demoIsolation = readFileSync(new URL("../migrations/20260818092918_crm_demo_lead_isolation.sql", import.meta.url), "utf8")
const qaLeadMarkers = readFileSync(new URL("../migrations/20260818093051_crm_mark_qa_leads_demo.sql", import.meta.url), "utf8")
const dexterFunction = readFileSync(new URL("../functions/agent-dexter/index.ts", import.meta.url), "utf8")

test("CRM dashboard keeps personal work user-scoped and uses company-visible deals", () => {
  assert.match(migration, /multideck_crm_get_dashboard/)
  assert.match(migration, /CRMLead_OwnerUserID" = v_context\.user_id/)
  assert.match(companyDashboard, /CRMLead_OwnerUserID" = v_context\.user_id/)
  assert.match(companyDashboard, /company_deals as/)
  assert.match(companyDashboard, /pipeline\."Company_ID" = v_context\.company_id/)
  assert.doesNotMatch(companyDashboard, /CRMOppty_OwnerUserID" = v_context\.user_id/)
  assert.match(companyDashboard, /revoke all on function public\.multideck_crm_get_dashboard.*public, anon/s)
  assert.match(companyDashboard, /grant execute on function public\.multideck_crm_get_dashboard.*authenticated/s)
  assert.match(migration, /p_inactivity_days not in \(30, 90, 180\)/)
  assert.match(migration, /last_contact_at is not null\), last_contact_at asc/)
  assert.match(page, /getCrmDashboard/)
  assert.match(page, /No leads match this view/)
  assert.doesNotMatch(page.slice(page.indexOf("export function CrmOverviewPage"), page.indexOf("function PipelineSettingsDrawer")), /CrmSalesCommandCenter|CrmMetricsGrid/)
})

test("follow-up opportunities are deterministic, mailbox-scoped and require review before CRM creation", () => {
  assert.match(followUps, /multideck_crm_get_follow_up_opportunities/)
  assert.match(followUps, /multideck_crm_create_follow_up_lead/)
  assert.match(followUps, /mailbox\."CommMailbox_UserID" = v_context\.user_id/)
  assert.match(followUps, /CommMailboxAccess_CanRead/)
  assert.match(followUps, /interval '3 days'/)
  assert.match(followUps, /interval '5 days'/)
  assert.match(followUps, /not "CommMessage_IsDraft"/)
  assert.match(followUps, /CRMLead_OwnerUserID" = v_context\.user_id/)
  assert.match(followUps, /This email is already connected to a CRM record/)
  assert.match(followUps, /revoke all on function public\.multideck_crm_get_follow_up_opportunities.*public, anon/s)
  assert.match(followUps, /grant execute on function public\.multideck_crm_create_follow_up_lead.*authenticated/s)
  assert.match(page, /getCrmFollowUpOpportunities/)
  assert.match(page, /Review the details found in the email before adding them to CRM/)
  assert.match(dashboard, /className="md-crm-row-open-target"/)
  assert.match(dashboard, /sideInteractive=\{opportunity\.canCreate\}/)
  assert.doesNotMatch(dashboard, /role=\{onOpen \? "button"/)
})

test("Home and CRM share a contextual follow-up queue without exposing ranking reasons", () => {
  assert.match(contextualFollowUps, /_multideck_crm_get_follow_up_candidates_v1/)
  assert.match(contextualFollowUps, /CommDelivery_EventTypeCode[\s\S]*\(bounce\|fail\|reject\)/)
  assert.match(contextualFollowUps, /has_acknowledgement/)
  assert.match(contextualFollowUps, /has_closed_conversation/)
  assert.match(contextualFollowUps, /CRMLead_FirstResponseDueAt/)
  assert.match(contextualFollowUps, /CRMOppty_NextActionDueAt/)
  assert.match(contextualFollowUps, /CusQuoteHeader_FollowUpAt/)
  assert.match(contextualFollowUps, /recommendationCode/)
  assert.match(contextualFollowUps, /person_rank = 1/)
  assert.match(contextualFollowUps, /never the internal ranking reasons/)
  assert.doesNotMatch(contextualFollowUps, /'recommendationReason'/)
  assert.doesNotMatch(contextualFollowUps, /'rankingReasons'/)
  assert.match(homeFollowUps, /getCrmFollowUpOpportunities/)
  assert.doesNotMatch(homeFollowUps, /listThreads|unreadCount/)
  assert.match(homePage, /formatFollowUpRecommendation/)
  assert.match(dashboard, /formatFollowUpRecommendation/)
  assert.match(dexterFunction, /exact hidden ordering or ranking reasons/)
  assert.match(dexterFunction, /existing event-driven Watching for you adapters/)
})

test("deal stages localise counts and empty states", () => {
  assert.match(crmComponents, /translate\(count === 1 \? "deal" : "deals"\)/)
  assert.match(crmComponents, /t\("No deals in this stage"\)/)
  assert.doesNotMatch(crmComponents, />No deals in this stage</)
})

test("area map separates unrecognised leads from recognised areas hidden by the display limit", () => {
  assert.match(dashboard, /const mappedAreas = useMemo/)
  assert.match(dashboard, /const mappedTotal = mappedAreas\.reduce/)
  assert.match(dashboard, /mappedAreas\.length - points\.length/)
  assert.match(dashboard, /more mapped areas not shown/)
  assert.match(dashboard, /without areas/)
})

test("marked demo leads stay out of CRM, Dexter and watch surfaces", () => {
  assert.match(demoIsolation, /multideck_crm_list_leads_essential/)
  assert.match(demoIsolation, /multideck_crm_get_dashboard/)
  assert.match(demoIsolation, /multideck_dexter_domain_leads/)
  assert.match(demoIsolation, /with ordinality rows\(item, ordinal\)/)
  assert.match(demoIsolation, /jsonb_agg\(item[\s\S]*order by ordinal\)/)
  assert.match(demoIsolation, /lower\(coalesce\(lead\."CRMLead_MetadataJSON" ->> 'isDemo', 'false'\)\) <> 'true'/)
  assert.match(demoIsolation, /TR_CRM_Leads_dexter_watch/)
  assert.match(demoIsolation, /TR_CRM_Leads_native_address_dexter_watch_update/)
  assert.match(qaLeadMarkers, /automated-qa-address/)
  assert.match(qaLeadMarkers, /\^qr-live-qa-/)
  assert.match(qaLeadMarkers, /\^codex-lead-/)
  assert.doesNotMatch(qaLeadMarkers, /CRMLead_ID"\s*=/)
})

test("pipeline stages expose separate keyboard controls without nested buttons", () => {
  const stageCard = pipelineEditor.slice(pipelineEditor.indexOf("function StageCard"), pipelineEditor.indexOf("function TonePicker"))
  assert.match(stageCard, /aria-pressed=\{selected\}/)
  assert.match(stageCard, /onClick=\{onSelect\}/)
  assert.match(stageCard, /aria-label=\{`\$\{t\("Rename stage"\)\}/)
  assert.doesNotMatch(stageCard, /role="button"/)
  assert.doesNotMatch(stageCard, /tabIndex=\{-1\}/)
})

test("lead transfers lock, reject stale owners, update open opportunities and notify both owners", () => {
  assert.match(migration, /CRM_LeadTransferRequests/)
  assert.match(migration, /pg_advisory_xact_lock/)
  assert.match(migration, /The lead owner changed while this request was open/)
  assert.match(migration, /status\."CRMOpptyStatus_IsOpen"/)
  assert.match(migration, /from \(values \(p_expected_owner_id\), \(p_target_user_id\)\)/)
  assert.match(migration, /CRM\.Leads\.Reassign/)
  const leadDetailPage = page.slice(page.indexOf("export function CrmLeadDetailPage"), page.indexOf("export function CrmListsPage"))
  assert.match(leadDetailPage, /requestLeadTransfer/)
  assert.match(leadDetailPage, /decideLeadTransfer/)
  assert.match(leadDetailPage, /cancelLeadTransfer/)
  assert.match(leadDetailPage, /hasPermission\(currentUser, "CRM\.Leads\.Reassign"\)/)
  assert.match(leadDetailPage, /Request ownership/)
  assert.match(leadDetailPage, /Ownership request pending/)
  assert.match(leadDetailPage, /Ownership requests/)
  assert.match(leadDetailPage, /Reason for overriding ownership/)
  assert.match(leadDetailPage, /Search team members/)
  assert.match(leadDetailPage, /requestsToReview\.map/)
  assert.match(leadDetailPage, /currentPendingRequest/)
  assert.match(app, /<CrmLeadDetailPage[^>]*currentUser=\{currentUser\}/)
  for (const phrase of ["Manage ownership", "Ownership request pending", "Send ownership request", "Reason for overriding ownership"]) {
    assert.ok(translations.includes(`"${phrase}": { de:`), `${phrase} must be localised`)
  }
})

test("deal winning is conversion-stage validated, permissioned and idempotent", () => {
  assert.match(migration, /multideck_crm_win_deal/)
  assert.match(migration, /CRMPipelineStage_IsConversion/)
  assert.match(migration, /CRMOppty_WonAt" is not null/)
  assert.match(migration, /Org_Master_Type/)
  assert.match(migration, /CRM_AccountProfiles/)
  assert.match(page, /Confirm deal won/)
})

test("forms is an inert planned shell and Dexter exposes only deterministic parity", () => {
  assert.match(forms, /Nothing on this page saves, sends, signs or schedules reminders/)
  assert.match(forms, /<Button disabled/)
  assert.doesNotMatch(forms, /fetch\(|supabase|callCrmRpc/)
  assert.match(dexter, /pendingTransfer/)
  assert.match(dexter, /Comm_DeliveryEvents_dexter_watch/)
  assert.match(dexter, /request_lead_transfer/)
  assert.match(dexter, /mark_deal_won/)
})
