import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import test from "node:test"

const repoRoot = resolve(import.meta.dirname, "../..")
const read = (path) => readFileSync(resolve(repoRoot, path), "utf8")

const migration = read("supabase/migrations/20260818153000_crm_account_contact_register_paging.sql")
const organisationMigration = read("supabase/migrations/20260820093814_crm_company_multi_types.sql")
const optionalTypesMigration = read("supabase/migrations/20260820095816_allow_company_type_removal.sql")
const edge = read("supabase/functions/customers/index.ts")
const backend = read("supabase/functions/_shared/backend.ts")
const api = read("multideck.client/src/lib/customer-api.ts")
const accountsPage = read("multideck.client/src/pages/crm-accounts-page.tsx")
const accountDetailPage = read("multideck.client/src/pages/crm-account-detail-page.tsx")
const contactsPage = read("multideck.client/src/pages/crm-contacts-page.tsx")
const customersPage = read("multideck.client/src/pages/customers-page.tsx")
const crmPage = read("multideck.client/src/pages/crm-page.tsx")
const dataTable = read("multideck.client/src/components/multideck/data-table.tsx")
const pagination = read("multideck.client/src/components/multideck/pagination.tsx")
const navigation = read("multideck.client/src/data/navigation-data.ts")
const app = read("multideck.client/src/App.tsx")
const styles = read("multideck.client/src/styles.css")
const translations = read("multideck.client/src/i18n/translate.ts")

test("account and contact register RPCs bound rows, filter before paging, and retain totals", () => {
  assert.match(migration, /multideck_crm_account_register_page/)
  assert.match(migration, /multideck_crm_contact_register_page/)
  assert.equal((migration.match(/least\(coalesce\(p_limit, 50\), 100\)/g) ?? []).length, 2)
  assert.equal((migration.match(/ordinal > v_offset and ordinal <= v_offset \+ v_limit/g) ?? []).length, 2)
  assert.equal((migration.match(/jsonb_agg\(id order by ordinal\)/g) ?? []).length, 2)
  assert.equal((migration.match(/'total', \(select count\(\*\) from filtered\)/g) ?? []).length, 2)
  assert.match(migration, /Customers\.Read/)
  assert.match(migration, /multideck_crm_accessible_account_ids\(v_context\.company_id\)/)
  assert.match(migration, /grant execute on function public\.multideck_crm_account_register_page[\s\S]*to authenticated, service_role/)
})

test("the Customers Edge function hydrates only the ordered page identifiers", () => {
  assert.match(backend, /export function authenticatedClient\(token: string\)/)
  assert.match(edge, /params\.has\("limit"\)/)
  assert.match(edge, /userDb\.rpc\("multideck_crm_organisation_register_page"/)
  assert.match(edge, /userDb\.rpc\("multideck_crm_contact_register_page"/)
  assert.match(edge, /customerRows\(admin, current\.Company_ID, null, null, false, ids, undefined, "any"\)/)
  assert.match(edge, /contactRows\(admin, current\.Company_ID, null, null, null, false, ids\)/)
  assert.match(edge, /ids\.flatMap\(\(id\) => rowMap\.get\(id\)/)
})

test("companies use one company-scoped register and multi-value type contract", () => {
  assert.match(organisationMigration, /multideck_crm_organisation_register_page/)
  assert.match(organisationMigration, /v_organisation_type not in \('company', 'customer', 'supplier'\)/)
  assert.match(organisationMigration, /multideck_crm_accessible_account_ids\(v_context\.company_id\)/)
  assert.match(organisationMigration, /jsonb_array_elements_text\(p_input -> 'orgTypeIds'\)/)
  assert.match(organisationMigration, /insert into public\."Org_Master_Type"/)
  assert.match(organisationMigration, /on conflict \("OrgType_ID", "Org_ID"\) do nothing/)
  assert.match(organisationMigration, /grant execute on function public\.multideck_crm_organisation_register_page[\s\S]*to authenticated, service_role/)
  assert.doesNotMatch(edge, /organisationTypeFromUrl/)
  assert.match(edge, /p_organisation_type: organisationType/)
  assert.match(edge, /organisationType !== "company" && organisationType !== "customer" && organisationType !== "supplier"/)
  assert.match(api, /orgTypeIds: string\[\]/)
  assert.match(accountsPage, /<MultiSelectMenu/)
  assert.match(organisationMigration, /p_filter_query jsonb default null/)
  assert.match(organisationMigration, /multideck_register_filter_matches\(filter_fields, p_filter_query\)/)
  assert.match(organisationMigration, /'organisationTypes', organisation_types\.names/)
  assert.match(edge, /organisationFilterQuery\(params\.get\("filterQuery"\)\)/)
  assert.match(edge, /organisationFilterFields = new Set/)
  assert.match(api, /filterQuery: input\.filterQuery \? JSON\.stringify\(input\.filterQuery\) : null/)
  assert.match(accountsPage, /<AdvancedFilterPopover/)
})

test("CRM navigation exposes one Companies register with supplier links redirected", () => {
  assert.match(navigation, /label: "Organisations"/)
  assert.match(navigation, /label: "Companies"[\s\S]*route: "\/crm\/accounts"/)
  assert.doesNotMatch(navigation, /route: "\/crm\/suppliers"/)
  assert.doesNotMatch(app, /route === "\/crm\/suppliers"/)
  assert.match(app, /path === "\/crm\/suppliers"\) return "\/crm\/accounts"/)
  assert.match(accountsPage, /organisationType: "company"/)
  assert.match(translations, /Organisations: "Organizations"/)
})

test("company types retain Dexter read and event-driven watch parity", () => {
  assert.match(organisationMigration, /create or replace function public\.multideck_dexter_domain_customers/)
  assert.match(organisationMigration, /'organisationTypes', types\.names/)
  assert.match(organisationMigration, /Organisations and contacts/)
  assert.match(organisationMigration, /'Org_Master_Type'/)
  assert.match(organisationMigration, /AIDexterWatchSignal_NewJSON/)
  assert.doesNotMatch(organisationMigration, /cron|schedule|http_request/)
})

test("the organisation header shows only editable organisation-type pills", () => {
  assert.match(accountDetailPage, /kind="status" indicator=\{false\} tone="neutral"/)
  assert.match(accountDetailPage, /const canRemove = Boolean\(reference && type\.id\)/)
  assert.match(accountDetailPage, /aria-label=\{`\$\{t\("Remove company type"\)\}: \$\{t\(type\.name\)\}`\}/)
  assert.match(accountDetailPage, /group\/type isolate gap-0/)
  assert.match(accountDetailPage, /md-company-type-remove-slot ms-0 inline-grid w-0/)
  assert.match(accountDetailPage, /group-hover\/type:ms-1 group-hover\/type:w-5/)
  assert.match(accountDetailPage, /md-company-type-remove/)
  assert.match(styles, /\.md-company-type-remove-slot \{[\s\S]*inline-size var\(--md-motion-fast\)[\s\S]*margin-inline-start var\(--md-motion-fast\)[\s\S]*opacity var\(--md-motion-fast\)[\s\S]*translate var\(--md-motion-fast\)[\s\S]*scale var\(--md-motion-fast\)/)
  assert.match(accountDetailPage, /active:scale-\[0\.96\]/)
  assert.match(accountDetailPage, /group-hover\/type:w-5 group-hover\/type:translate-x-0 group-hover\/type:scale-100/)
  assert.match(accountDetailPage, /group-focus-within\/type:opacity-100/)
  assert.match(accountDetailPage, /\[@media\(hover:none\)\]:opacity-100/)
  assert.doesNotMatch(accountDetailPage, /blur-\[4px\]|transition-\[background-color,filter/)
  assert.doesNotMatch(accountDetailPage, /canRemove && "pe-7"/)
  assert.doesNotMatch(accountDetailPage, /if \(!orgTypeIds\.length\)/)
  assert.match(accountDetailPage, /aria-label=\{t\("Edit company types"\)\}/)
  assert.match(accountDetailPage, /<DropdownMenuCheckboxItem/)
  assert.match(accountDetailPage, /onSelect=\{\(event\) => event\.preventDefault\(\)\}/)
  assert.match(accountDetailPage, /checked=\{currentTypeIds\.includes\(type\.id\)\}/)
  assert.match(accountDetailPage, /setCompanyTypeIdsDraft\(nextTypeIds\)/)
  assert.match(accountDetailPage, /const companyTypesBatchDelayMs = 450/)
  assert.match(accountDetailPage, /setTimeout\(\(\) => void flushCompanyTypes\(\), saveDelayMs\)/)
  assert.match(accountDetailPage, /selectCompanyTypes\(currentTypeIds\.filter\(\(id\) => id !== type\.id\), 0\)/)
  assert.match(accountDetailPage, /if \(!open\) void flushCompanyTypes\(\)/)
  assert.match(accountDetailPage, /await patchCompanyTypes\(requestedTypeIds\)/)
  assert.doesNotMatch(accountDetailPage, /disabled=\{companyTypesSaving\}/)
  assert.doesNotMatch(accountDetailPage, /<MultiSelectMenu/)
  assert.match(api, /export async function updateAccountCompanyTypes/)
  assert.match(api, /`\/\$\{encodeURIComponent\(accountId\)\}\/types`/)
  assert.match(edge, /async function updateAccountTypes/)
  assert.match(edge, /p_input: \{ name, orgTypeIds \}/)
  assert.match(edge, /parts\[1\] === "types"[\s\S]*updateAccountTypes/)
  assert.doesNotMatch(edge, /async function updateAccountTypes[\s\S]{0,1600}accountDetail\(/)
})

test("existing companies may remove their final type without weakening creation", () => {
  assert.match(optionalTypesMigration, /v_type_ids := coalesce\(v_type_ids, array\[\]::uuid\[\]\)/)
  assert.match(optionalTypesMigration, /if cardinality\(v_type_ids\) > 12/)
  assert.doesNotMatch(optionalTypesMigration, /cardinality\(v_type_ids\).*< 1/)
  assert.match(optionalTypesMigration, /delete from public\."Org_Master_Type"/)
  assert.match(optionalTypesMigration, /'organisationTypes', v_new_types/)
  assert.match(edge, /validateOrganisationTypeIds\(admin, payload\.orgTypeIds, true\)/)
  assert.match(edge, /validateOrganisationTypeIds\(admin, payload\.orgTypeIds\)\s*$/m)
  assert.match(organisationMigration, /Choose between 1 and 12 company types\./)
})

test("CRM account and contact pages use server filtering, sorting, and pagination", () => {
  assert.match(api, /export async function listAccountsPage/)
  assert.match(api, /export async function listContactsPage/)
  assert.doesNotMatch(api, /legacyAccountRegisterPage|legacyContactRegisterPage/)
  assert.doesNotMatch(api, /customerRequest<ApiCustomer\[]>\(""|customerRequest<ApiContact\[]>\("\/contacts"/)
  assert.match(api, /customerRequest<AccountRegisterPage>\(query/)
  assert.match(api, /customerRequest<ContactRegisterPage>\(`\/contacts\$\{query\}`/)
  assert.match(accountsPage, /listAccountsPage\(\{/)
  assert.match(contactsPage, /listContactsPage\(\{/)
  assert.doesNotMatch(accountsPage, /const filtered = useMemo/)
  assert.doesNotMatch(contactsPage, /const filtered = useMemo/)
  assert.match(accountsPage, /serverSorting=\{\{ value: sort/)
  assert.match(accountsPage, /pagination=\{\{ offset, limit: accountPageSize, total/)
  assert.match(contactsPage, /pagination=\{\{ offset, limit: contactPageSize, total/)
})

test("the canonical DataTable exposes accessible server-owned paging", () => {
  assert.match(dataTable, /pagination\?: \{/)
  assert.match(dataTable, /serverSorting\?: \{/)
  assert.match(dataTable, /if \(serverSorting\) return rows/)
  assert.match(dataTable, /<Pagination/)
  assert.match(dataTable, /onPageChange=\{\(page\) => paging\.onOffsetChange\(\(page - 1\) \* paging\.limit\)\}/)
  assert.match(dataTable, /onPageSizeChange=\{paging\.onLimitChange\}/)
  assert.match(pagination, /aria-label=\{t\("Previous page"\)\}/)
  assert.match(pagination, /aria-label=\{t\("Next page"\)\}/)
  assert.match(pagination, /aria-live="polite"/)
})

test("remaining customer surfaces avoid the unbounded account API", () => {
  assert.doesNotMatch(customersPage, /\blistCustomers\(/)
  assert.doesNotMatch(crmPage, /\blistCustomers\(/)
  assert.match(customersPage, /listCustomerDirectoryPage\(/)
  assert.match(crmPage, /listAccountsPage\(/)
  assert.match(customersPage, /limit: rowsPerPage/)
  const followUpDialog = crmPage.slice(crmPage.indexOf("function FollowUpRecordDialog"), crmPage.indexOf("function DealDetailDrawer"))
  assert.match(followUpDialog, /search: accountSearch\.trim\(\)/)
  assert.match(followUpDialog, /limit: 25/)
  assert.doesNotMatch(followUpDialog, /while \(offset < total\)|loadAllCrmAccounts/)
})
