import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"

const customers = readFileSync(new URL("../functions/customers/index.ts", import.meta.url), "utf8")
const migration = readFileSync(new URL("../migrations/20260803224820_crm_account_contact_dexter_parity_v2.sql", import.meta.url), "utf8")
const atomicMigration = readFileSync(new URL("../migrations/20260818103119_crm_atomic_account_contact_writes.sql", import.meta.url), "utf8")
const boundedReadMigration = readFileSync(new URL("../migrations/20260818156000_crm_customer_detail_bounded_reads.sql", import.meta.url), "utf8")
const watchFix = readFileSync(new URL("../migrations/20260803231257_crm_customer_watch_company_scope.sql", import.meta.url), "utf8")
const seed = readFileSync(new URL("../seed.sql", import.meta.url), "utf8")
const customerApi = readFileSync(new URL("../../multideck.client/src/lib/customer-api.ts", import.meta.url), "utf8")
const accountsPage = readFileSync(new URL("../../multideck.client/src/pages/crm-accounts-page.tsx", import.meta.url), "utf8")
const crmPage = readFileSync(new URL("../../multideck.client/src/pages/crm-page.tsx", import.meta.url), "utf8")
const accountDetail = readFileSync(new URL("../../multideck.client/src/pages/crm-account-detail-page.tsx", import.meta.url), "utf8")
const contactsPage = readFileSync(new URL("../../multideck.client/src/pages/crm-contacts-page.tsx", import.meta.url), "utf8")
const contactDetail = readFileSync(new URL("../../multideck.client/src/pages/crm-contact-detail-page.tsx", import.meta.url), "utf8")
const contactCreateDialog = readFileSync(new URL("../../multideck.client/src/components/multideck/contact-create-dialog.tsx", import.meta.url), "utf8")
const advancedFilterPopover = readFileSync(new URL("../../multideck.client/src/components/multideck/advanced-filter-popover.tsx", import.meta.url), "utf8")
const organisationFoundation = readFileSync(new URL("../../multideck.client/src/components/multideck/organisation-foundation-panel.tsx", import.meta.url), "utf8")
const organisationFoundationMigration = readFileSync(new URL("../migrations/20260820110000_crm_organisation_contact_address_foundation.sql", import.meta.url), "utf8")
const accountOperations = readFileSync(new URL("../../multideck.client/src/components/multideck/account-operations-workspace.tsx", import.meta.url), "utf8")
const accountOperationsMigration = readFileSync(new URL("../migrations/20260820162000_crm_account_operational_detail.sql", import.meta.url), "utf8")

test("account and contact product routes use the authenticated customer API rather than fixture arrays", () => {
  assert.match(customerApi, /edgeFetch\("customers"/)
  assert.match(customerApi, /`account-detail:\$\{customerId\}`/)
  assert.match(customerApi, /`contact-detail:\$\{contactId\}`/)
  assert.match(customerApi, /"account-reference"/)
  assert.match(accountsPage, /listAccountsPage\(\{/)
  assert.match(contactsPage, /listContactsPage\(\{/)
  assert.match(accountDetail, /getCustomer\(accountId\)/)
  assert.match(contactDetail, /getContact\(contactId\)/)
  assert.match(customerApi, /invalidateCrmResources\(session\.user\.id, \["accounts:", "contacts:", `account-detail:\$\{contact\.accountId\}`, `contact-detail:\$\{contactId\}`\]\)/)
  assert.match(customerApi, /invalidateCrmResources\(session\.user\.id, \["accounts:", "contacts:", `account-detail:\$\{accountId\}`\]\)/)
  for (const source of [accountsPage, accountDetail, contactsPage, contactDetail]) {
    assert.doesNotMatch(source, /crmContacts|crmAccountSignals|multideck-data|mock|placeholderData/)
  }
})

test("account and contact details expose real empty states and permission-scoped email history", () => {
  assert.match(customers, /const permissions = await requirePermission\(admin, current\.User_ID, "Customers\.Read"\)/)
  assert.match(customers, /recentEmails\(admin, userId, permissions,/)
  assert.doesNotMatch(customers, /async function recentEmails[\s\S]*?permissionValues\(admin, userId\)/)
  assert.match(customers, /Email\.Read/)
  assert.match(customers, /multideck_crm_customer_recent_emails/)
  assert.match(boundedReadMigration, /Comm_MailboxAccess/)
  assert.match(boundedReadMigration, /CommMailboxAccess_CanRead/)
  assert.match(boundedReadMigration, /CommThread_CustomerOrgID/)
  assert.match(accountDetail, /No recent emails are linked to this account or its contacts/)
  assert.match(contactDetail, /No recent emails are linked to this contact/)
  assert.doesNotMatch(accountDetail + contactDetail, /sample email|example conversation|fake activity/i)
  assert.match(customers, /editVersion: profile\?\.CRMAccount_EditVersion \?\? 1/)
  assert.match(customers, /editVersion: profile\?\.CRMContact_EditVersion \?\? 1/)
})

test("account summary matches the six-tile leads summary pattern", () => {
  const sharedSummaryClass = /grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-6/
  const sharedTileClass = /h-\[44px\] min-w-0 rounded-\[var\(--md-radius-lg\)\] px-3 py-1\.5/
  assert.match(crmPage, sharedSummaryClass)
  assert.match(accountsPage, sharedSummaryClass)
  assert.match(crmPage, sharedTileClass)
  assert.match(accountsPage, sharedTileClass)
  for (const label of ["Contacts", "Needs attention", "Marketing opted in", "Unassigned"]) {
    assert.match(accountsPage, new RegExp(`t\\(\\"${label}\\"\\)`))
  }
  assert.match(accountsPage, /t\("Total companies"\)/)
  assert.match(accountsPage, /t\("Healthy companies"\)/)
})

test("account and contact directories use the configurable register table and in-table controls", () => {
  for (const source of [accountsPage, contactsPage]) {
    assert.match(source, /<DataTable/)
    assert.match(source, /<RegisterViewSwitch/)
    assert.match(source, /<RegisterFacetSelect/)
    assert.match(source, /<RegisterSearchField/)
    assert.doesNotMatch(source, /<TableHeader>|<TableBody>/)
  }
  assert.match(accountsPage, /storageKey="crm-company-organisations-v1"/)
  assert.match(contactsPage, /storageKey="crm-contacts"/)
  const filterValueControl = advancedFilterPopover.slice(
    advancedFilterPopover.indexOf('<div className="col-start-2 row-start-3'),
    advancedFilterPopover.indexOf('<Button', advancedFilterPopover.indexOf('<div className="col-start-2 row-start-3')),
  )
  assert.match(filterValueControl, /kind === "select"/)
  assert.match(filterValueControl, /aria-label=\{t\("Filter value"\)\}/)
  assert.match(filterValueControl, /\(meta\?\.options \?\? \[\]\)\.map/)
})

test("a top-bar contact requires an explicit account choice", () => {
  assert.match(contactCreateDialog, /const defaultAccountId = fixedAccountId \?\? ""/)
  assert.match(contactCreateDialog, /<option value="">\{t\("Choose an account"\)\}<\/option>/)
  assert.doesNotMatch(contactCreateDialog, /accounts\[0\]/)
  assert.match(contactCreateDialog, /accounts\.length === 0[\s\S]*Create an account before adding a contact/)
})

test("account and contact creation failures stay visible and recoverable on every wizard step", () => {
  assert.match(accountsPage, /referenceState.*"idle" \| "loading" \| "ready" \| "error"/)
  assert.match(accountsPage, /setReferenceState\("error"\)/)
  assert.match(accountsPage, /Organisation types could not be loaded\. Try again before creating this company\./)
  assert.match(accountsPage, /setReferenceReloadToken\(\(value\) => value \+ 1\)/)

  const accountGlobalError = accountsPage.slice(accountsPage.lastIndexOf("{createError ?"))
  assert.match(accountGlobalError, /role="alert"/)
  const contactGlobalError = contactCreateDialog.slice(contactCreateDialog.lastIndexOf("{createError ?"))
  assert.match(contactGlobalError, /role="alert"/)
  assert.match(contactGlobalError, /\{t\(createError\)\}/)
})

test("contact fields edit inline and consent changes require evidence", () => {
  assert.match(contactDetail, /import \{ InlineField, InlineFieldCard, InlineSelectField, InlineSwitchField \}/)
  assert.match(contactDetail, /import \{[^}]*getContact[^}]*updateContact[^}]*type ApiContactDetail[^}]*type UpdateContactInput \}/)
  assert.match(contactDetail, /const saveQueueRef = useRef<Promise<void>>\(Promise\.resolve\(\)\)/)
  assert.match(contactDetail, /const patch = useCallback\(\(change: Partial<ContactDraft>\)/)
  assert.match(contactDetail, /saveQueueRef\.current\.then\(async \(\) =>/)
  assert.match(contactDetail, /const current = contactRef\.current/)
  assert.match(contactDetail, /await updateContact\(contactId, \{ \.\.\.next, metadata \}, current\.editVersion\)/)
  assert.match(contactDetail, /saveQueueRef\.current = save\.catch\(\(\) => undefined\)/)
  assert.match(contactDetail, /<InlineFieldCard title="Who they are" directEdit>/)
  assert.match(contactDetail, /<InlineField label="First name"[\s\S]*?onSave=\{\(firstName\) => patch\(/)
  assert.match(customerApi, /export async function updateContact\(contactId: string, input: UpdateContactInput, expectedVersion: number\)/)
  assert.doesNotMatch(contactDetail, /id="contact-detail-form"|Save changes|Edit contact|ContactEditDialog/)
  assert.match(contactDetail, /MarketingOptInControl/)
  assert.match(contactDetail, /<ContactConsentDialog[\s\S]*?onSave=\{async \(marketingOptIn, marketingConsentReason\) =>/)
  const consentDialog = contactDetail.slice(contactDetail.indexOf("function ContactConsentDialog"))
  assert.match(consentDialog, /What is this based on\?/)
  assert.match(consentDialog, /disabled=\{saving \|\| !changed \|\| !reason\.trim\(\)\}/)
  assert.match(consentDialog, /await onSave\(optIn, reason\.trim\(\)\)/)
  assert.match(contactDetail, /Additional fields/)
  assert.match(atomicMigration, /Explain the source or evidence for this consent change/)
  assert.match(customers, /multideck_crm_update_contact/)
  assert.match(customers, /p_expected_version: expectedVersion\(payload\.expectedVersion\)/)
})

test("company foundations preserve offices, address capabilities, defaults, and contact history", () => {
  assert.match(accountDetail, /<OrganisationFoundationPanel/)
  assert.match(organisationFoundation, /account\.officeAssignments/)
  assert.match(organisationFoundation, /account\.addressCapabilities/)
  assert.match(organisationFoundation, /account\.relatedPartyDefaults/)
  assert.match(organisationFoundation, /Weekly opening hours/)
  assert.match(organisationFoundation, /Dated overrides/)
  assert.match(contactDetail, /contact\.employmentHistory/)
  assert.match(contactDetail, /contact\.emailHistory/)
  assert.match(contactDetail, /transferContact\(contact\.id/)
  assert.match(organisationFoundationMigration, /CRM_AccountOfficeAssignments/)
  assert.match(organisationFoundationMigration, /CRM_ContactOrganisationAssignments/)
  assert.match(organisationFoundationMigration, /Org_AddressOpeningHours/)
  assert.match(organisationFoundationMigration, /Org_AddressOpeningOverrides/)
  assert.match(organisationFoundationMigration, /Org_RelatedPartyDefaults/)
  assert.match(organisationFoundationMigration, /multideck_crm_transfer_contact/)
  assert.match(organisationFoundationMigration, /multideck_crm_resolve_related_party_default/)
})

test("account editing uses existing CRM reference data and preserves the current customer model", () => {
  assert.match(customers, /sys_CRMRelationshipStatuses/)
  assert.match(accountDetail, /getCustomerReference/)
  assert.match(accountDetail, /relationshipStatuses/)
  assert.match(accountDetail, /const saveQueueRef = useRef<Promise<void>>\(Promise\.resolve\(\)\)/)
  assert.match(accountDetail, /saveQueueRef\.current\.then\(async \(\) =>/)
  assert.match(accountDetail, /const current = accountRef\.current/)
  assert.match(accountDetail, /await updateAccount\(accountId, \{ \.\.\.next, metadata \}, current\.editVersion\)/)
  assert.match(accountDetail, /<ScoreCell label=\{t\("Health"\)\} score=\{currentAccount\.healthScore\} tone="health" \/>/)
  assert.match(accountDetail, /<ScoreCell label=\{t\("Churn risk"\)\} score=\{currentAccount\.churnRiskScore\} tone="risk" \/>/)
  assert.match(accountDetail, /function ScoreCell\(\{ label, score, tone \}/)
  assert.match(accountDetail, /<ProgressRing ratio=\{\(score \?\? 0\) \/ 100\}/)
  assert.match(accountDetail, /<header[\s\S]*<HeadingField value=\{currentAccount\.name\}/)
  assert.doesNotMatch(accountDetail, /<aside[\s\S]*Company details/)
  assert.match(accountDetail, /<AccountDetailTabs account=\{currentAccount\}/)
  assert.match(accountDetail, /<AccountOperationsPanel account=\{currentAccount\}/)
  assert.match(accountDetail, /MarketingOptInControl/)
  assert.match(accountDetail, /<AddCustomField onAdd=\{\(label, value\) => patch\(\{ customFields:/)
  assert.match(customers, /CRM_AccountProfiles/)
  assert.match(customers, /CRM_CustomerEngagementPreferences/)
  assert.match(accountDetail, /CustomerWarehouseAccess customerId=\{currentAccount\.id\}/)
  assert.match(accountDetail, /<Zone title=\{t\("Profile"\)}>\s*<InlineFieldGroup stacked directEdit>/)
})

test("account operations are contextual, persisted and available to booking workflows", () => {
  assert.match(accountOperations, /roleTabs[\s\S]*account\.types/)
  for (const label of ["Shipping line", "SCAC code", "Consignee", "Collection addresses", "Overseas agent", "Credit limit", "Supported invoice currencies", "VAT number", "EORI number", "Direct representation authority", "Recurring operational instructions", "Appointment required", "Privacy and retention"]) {
    assert.match(accountOperations, new RegExp(label, "i"))
  }
  assert.match(customers, /accountOperations\(admin, id, profile \?\? null\)/)
  assert.match(customers, /multideck_crm_replace_account_operations/)
  assert.match(accountOperationsMigration, /CRM_AccountOperationalInstructions/)
  assert.match(accountOperationsMigration, /Org_AddressOperationalDetails/)
  assert.match(accountOperationsMigration, /CRM_AccountDocumentRecords/)
  assert.match(accountOperationsMigration, /multideck_crm_resolve_account_instructions/)
  assert.match(accountOperationsMigration, /app_user_can_access_organisation/)
  assert.match(accountOperationsMigration, /left\(regexp_replace[\s\S]*, 8\)/)
})

test("account country codes are validated before any customer write", () => {
  assert.match(customers, /function countryCode\(value: unknown\)/)
  assert.match(customers, /\^\[A-Z\]\{2\}\$/)
  const createRoute = customers.slice(customers.indexOf('if (request.method === "POST" && !parts.length)'), customers.indexOf('if (request.method === "POST" && parts.length === 2'))
  assert.ok(createRoute.indexOf("countryCode(payload.countryCode)") < createRoute.indexOf('admin.rpc("multideck_crm_create_account"'))
  assert.match(customerApi, /countryCode: countryCode\(input\.countryCode\)/)
  assert.match(accountsPage, /maxLength=\{2\}/)
  assert.match(accountsPage, /Two-letter ISO code, e\.g\. GB/)
})

test("CRM detail reads stay scoped and consent reasons are validated before writes", () => {
  const customerRows = customers.slice(customers.indexOf("async function customerRows"), customers.indexOf("async function contactRows"))
  const contactRows = customers.slice(customers.indexOf("async function contactRows"), customers.indexOf("async function recentEmails"))
  const accountDetailSource = customers.slice(customers.indexOf("async function accountDetail"), customers.indexOf("async function contactDetail"))
  const contactDetailSource = customers.slice(customers.indexOf("async function contactDetail"), customers.indexOf("async function updateAccount"))
  const updateAccountSource = customers.slice(customers.indexOf("async function updateAccount"), customers.indexOf("async function updateContact"))
  const updateContactSource = customers.slice(customers.indexOf("async function updateContact"), customers.indexOf("function crmWriteError"))

  assert.match(accountDetailSource, /const summaryWithSource = \(await customerRows\(admin, companyId, null, id, true, undefined, userId, "any"\)\)\[0\]/)
  assert.match(accountDetailSource, /contactRows\(admin, companyId, null, id, null, false, undefined, userId, 20\)/)
  assert.ok(accountDetailSource.indexOf("const contactIds = contactList.map") < accountDetailSource.indexOf("recentEmails(admin, userId, permissions, id, contactIds"))
  assert.doesNotMatch(accountDetailSource, /admin\.from\("Org_Master"\)/)
  assert.doesNotMatch(accountDetailSource, /admin\.from\("CRM_AccountProfiles"\)/)
  assert.doesNotMatch(accountDetailSource, /admin\.from\("Org_Addresses"\)/)

  assert.match(contactDetailSource, /const summaryWithSource = \(await contactRows\(admin, companyId, null, null, id, true, undefined, userId, 1\)\)\[0\]/)
  assert.match(contactDetailSource, /const profile = __detailSource\.profile/)
  assert.doesNotMatch(contactDetailSource, /admin\.from\("CRM_ContactProfiles"\)/)

  assert.match(customerRows, /let typeLinkQuery = admin\.from\("Org_Master_Type"\)/)
  assert.match(customerRows, /typeLinkQuery = typeLinkQuery\.in\("Org_ID", scopedIds\)/)
  assert.match(customerRows, /let query = admin\.from\("Org_Master"\)/)
  assert.match(customerRows, /\.in\("Org_id", scopedIds\)/)

  assert.match(contactRows, /let query = admin\.from\("Org_Contacts"\)\.select\("\*"\)/)
  assert.match(contactRows, /query = scopedContactIdsOverride[\s\S]*query\.in\("OrgContact_ID", scopedContactIdsOverride\)[\s\S]*query\.in\("Org_ID", accessibleIds\)/)
  assert.match(contactRows, /if \(contactId\) query = query\.eq\("OrgContact_ID", contactId\)/)

  assert.match(updateAccountSource, /admin\.rpc\("multideck_crm_update_account"/)
  assert.match(updateContactSource, /admin\.rpc\("multideck_crm_update_contact"/)
  assert.match(updateAccountSource, /p_expected_version/)
  assert.match(updateContactSource, /p_expected_version/)
  assert.doesNotMatch(updateAccountSource, /admin\.from\("(?:Org_Master|CRM_AccountProfiles|Org_Addresses|CRM_CustomerEngagementPreferences|CRM_Activities)"\)\.(?:insert|update|upsert|delete)/)
  assert.doesNotMatch(updateContactSource, /admin\.from\("(?:Org_Contacts|OrgContact_Emails|CRM_ContactProfiles|Comm_Identities|CRM_Activities|CRM_ActivityParticipants)"\)\.(?:insert|update|upsert|delete)/)
  assert.match(contactDetailSource, /multideck_crm_contact_activity_page/)
  assert.match(contactDetailSource, /activityError[\s\S]*historyError/)
  assert.match(contactDetailSource, /recentEmails\(admin, userId, permissions, summary\.accountId, \[id\], summary\.email \? \[summary\.email\] : \[\], false\)/)
})

test("account and contact writes are transactional, versioned, duplicate-safe and audited", () => {
  assert.match(atomicMigration, /begin;[\s\S]*commit;/)
  assert.match(atomicMigration, /CRMAccount_EditVersion.*bigint not null default 1/)
  assert.match(atomicMigration, /CRMContact_EditVersion.*bigint not null default 1/)
  for (const fn of ["multideck_crm_create_account", "multideck_crm_update_account", "multideck_crm_create_contact", "multideck_crm_update_contact"]) {
    assert.match(atomicMigration, new RegExp(`create or replace function public\\.${fn}`))
    assert.match(atomicMigration, new RegExp(`grant execute on function public\\.${fn}`))
  }
  assert.match(atomicMigration, /p_expected_version bigint/)
  assert.match(atomicMigration, /CRM_CONFLICT:/)
  assert.match(atomicMigration, /pg_advisory_xact_lock\(hashtextextended/)
  assert.match(atomicMigration, /CRM_Activities/)
  assert.match(atomicMigration, /CRM_ActivityParticipants/)
  assert.match(atomicMigration, /sys_CRMActivityTypes[\s\S]*No active CRM activity type is configured/)
  assert.match(atomicMigration, /sys_WorkflowRecordTypes/)
  for (const recordType of ["crm_account", "crm_contact", "crm_activity"]) assert.match(atomicMigration, new RegExp(`'${recordType}'`))
  assert.match(atomicMigration, /Audit_EnableTableAudit/)
  assert.match(atomicMigration, /redact/i)
  assert.match(customers, /function crmWriteError\(error: any, fallback: string\)/)
  assert.match(customers, /error\?\.code === "22023" \|\| error\?\.code === "22P02"/)
  assert.match(customers, /function expectedVersion\(value: unknown\): number \| null/)
  assert.match(customers, /new HttpError\(409, "This record changed while you were editing it\./)
})

test("Dexter read and watch parity remains allowlisted, permissioned and event driven", () => {
  assert.match(migration, /'contacts'/)
  assert.match(migration, /'customers'/)
  assert.match(migration, /Customers\.Read/)
  assert.match(migration, /AI_DexterWatchSignals/)
  assert.match(migration, /TR_CRM_AccountProfiles_crm_customer_watch/)
  assert.match(migration, /TR_CRM_ContactProfiles_crm_customer_watch/)
  assert.match(migration, /AI_DexterWatches/)
  assert.match(watchFix, /select distinct watch\."AIDexterWatch_CompanyID"/)
  assert.match(watchFix, /AIDexterWatch_IsArmed/)
  assert.doesNotMatch(watchFix, /from public\."cmp_Company".*limit 1/s)
  assert.doesNotMatch(migration, /generic.*write|execute.*sql/i)
})

test("development records are database seeds and never browser placeholders", () => {
  assert.match(seed, /CRM_AccountProfiles/)
  assert.match(seed, /CRM_ContactProfiles/)
  assert.match(seed, /CRM_CustomerEngagementPreferences/)
  assert.match(seed, /Comm_ConsentPreferences/)
  assert.match(seed, /\.example\.test/)
  assert.match(seed, /developmentFixture/)
  assert.doesNotMatch(seed, /supabase_seed_crm_email/)
})
