import assert from 'node:assert/strict'
import test from 'node:test'
import {mkdtempSync,readFileSync,rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {spawnSync} from 'node:child_process'
const root=new URL('../',import.meta.url)
const migration=readFileSync(new URL('migrations/20260917212723_finance_export_atomic_completion.sql',root),'utf8')
const baseline=readFileSync(new URL('baseline/public-schema.sql',root),'utf8')
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`
const table=name=>baseline.match(new RegExp(`CREATE TABLE IF NOT EXISTS "public"\\."${name}" \\([\\s\\S]*?^\\);`,'m'))?.[0]
test('atomic export: rollback, leases, replay, scope revocation and source drift',()=>{
 const bin=process.env.PG_TEST_BIN||'/opt/homebrew/opt/postgresql@17/bin',dir=mkdtempSync(join(tmpdir(),'finance-export-'));let started=false
 const run=(cmd,args,input)=>{const r=spawnSync(join(bin,cmd),args,{input,encoding:'utf8',timeout:30000});assert.equal(r.status,0,r.stderr);return r.stdout.trim()}
 const args=['-X','-qAt','-h',dir,'-U','postgres','-d','postgres','-v','ON_ERROR_STOP=1']
 const sql=q=>run('psql',args,q)
 const reject=(q,re)=>{const r=spawnSync(join(bin,'psql'),args,{input:q,encoding:'utf8',timeout:30000});assert.notEqual(r.status,0);assert.match(r.stderr,re)}
 try{
  run('initdb',['-D',join(dir,'data'),'-A','trust','-U','postgres','--no-locale','--no-sync','-E','UTF8'])
  run('pg_ctl',['-D',join(dir,'data'),'-l',join(dir,'log'),'-o',`-k ${dir} -c listen_addresses=''`,'-w','start']);started=true
  sql(`create role anon;create role authenticated;create role service_role;
   create table "cmp_Users"("User_ID" uuid,"Company_ID" uuid,"User_AccessStatus" text);
   create table "cmp_LegalEntities"("LegalEntity_ID" uuid,"Company_ID" uuid,"LegalEntity_IsActive" boolean);
   create table "ACCI_Connections"("ACCIC_ID" uuid,"ACCIC_LegalEntityID" uuid,"ACCIC_StatusCode" text,"ACCIC_ProviderCode" text,"ACCIC_ExternalTenantName" text,"ACCIC_SettingsJSON" jsonb);
   create table "FIN_Documents"("FINDoc_ID" uuid primary key,"FINDoc_LegalEntityID" uuid,"FINDoc_StatusCode" text,"FINDoc_ExportStatusCode" text,"FINDoc_TypeCode" text,"FINDoc_UpdatedAt" timestamptz,"FINDoc_UpdatedBy" uuid);
   create table "FIN_CashTransactions"("FINCash_ID" uuid primary key,"FINCash_LegalEntityID" uuid,"FINCash_StatusCode" text,"FINCash_ExportStatusCode" text,"FINCash_TypeCode" text,"FINCash_UpdatedAt" timestamptz,"FINCash_UpdatedBy" uuid);
   create function _multideck_dexter_has_permission(uuid,text) returns boolean language sql as 'select true';
   ${['FIN_IntegrationQueue','ACCI_ExportBatches','ACCI_ExportItems','ACCI_ExternalRefs','ACCI_ReconciliationIssues','ACCI_SyncEvents'].map(table).join('\n')}
   alter table "ACCI_ExportBatches" alter column "ACCIEB_BatchNo" add generated by default as identity;
   alter table "ACCI_ExternalRefs" alter column "ACCIER_LastSyncedAt" drop not null;
   create unique index ref_local on "ACCI_ExternalRefs"("ACCIER_ConnectionID","ACCIER_DocumentTypeCode","ACCIER_LocalTable","ACCIER_LocalID");
   insert into "cmp_Users" values('${id(1)}','${id(2)}','active'),('${id(8)}','${id(9)}','active');
   insert into "cmp_LegalEntities" values('${id(3)}','${id(2)}',true);
   insert into "ACCI_Connections" values('${id(4)}','${id(3)}','active','erpnext','Example Ltd','{}');
   ${migration}`)
  const canonical=n=>({localId:id(n),localTable:'FIN_Documents',typeCode:'sl_invoice',localNumber:`INV-${n}`,providerCode:'erpnext',externalCompany:'Example Ltd',localAmount:12})
  const setup=n=>sql(`insert into "FIN_Documents" values('${id(n)}','${id(3)}','approved','queued','sl_invoice',now(),null);insert into "FIN_IntegrationQueue"("FINIntQ_ID","FINIntQ_LocalID","FINIntQ_LocalTable") values('${id(n+100)}','${id(n)}','FIN_Documents');`)
  const begin=(n,actor=1)=>`select multideck_finance_begin_export('${id(n+100)}','${id(actor)}','${id(4)}','${JSON.stringify(canonical(n))}');`
  const success=n=>({status:'synced',externalId:`ERP-${n}`,externalObjectType:'Sales Invoice',responsePayload:{multideckCanonicalExport:canonical(n),multideckDeliveryVerification:{status:'matched'}}})
  const finish=(n,token,result=success(n),actor=1)=>`select multideck_finance_finish_export('${id(n+100)}','${token}','${id(actor)}','${JSON.stringify(result)}');`
  setup(10)
  reject(`set role authenticated;${begin(10)}`,/permission denied/)
  reject(`set role anon;${begin(10)}`,/permission denied/)
  reject(begin(10,8),/outside the active authorised workspace/)
  let claim=JSON.parse(sql(begin(10)))
  reject(begin(10),/already processing/)
  reject(finish(10,claim.token,{status:'synced',externalId:'ERP-10',externalObjectType:'Sales Invoice'}),/comparison evidence/)
  assert.equal(sql('select count(*) from "ACCI_ExternalRefs"'),'0')
  // Force a late transaction failure: no reference, queue or document may turn green.
  sql(`create function fail_export_audit() returns trigger language plpgsql as $$begin raise exception 'audit unavailable';end$$;create trigger fail_audit before insert on "ACCI_SyncEvents" for each row execute function fail_export_audit();`)
  reject(finish(10,claim.token),/audit unavailable/)
  assert.equal(sql('select count(*) from "ACCI_ExternalRefs"'),'0')
  assert.equal(sql(`select "FINDoc_StatusCode" from "FIN_Documents" where "FINDoc_ID"='${id(10)}'`),'approved')
  sql('drop trigger fail_audit on "ACCI_SyncEvents";')
  assert.equal(JSON.parse(sql(finish(10,claim.token))).status,'synced')
  assert.equal(JSON.parse(sql(finish(10,claim.token))).completed,false)
  assert.equal(sql('select count(*) from "ACCI_SyncEvents"'),'1')
  assert.equal(sql(`select "FINDoc_StatusCode" from "FIN_Documents" where "FINDoc_ID"='${id(10)}'`),'submitted')
  setup(11);let old=JSON.parse(sql(begin(11)))
  sql(`update "FIN_IntegrationQueue" set "FINIntQ_LeaseUntil"=now()-interval '1 second' where "FINIntQ_ID"='${id(111)}';`)
  assert.equal(JSON.parse(sql(finish(11,old.token))).completed,false)
  claim=JSON.parse(sql(begin(11)))
  assert.notEqual(claim.token,old.token)
  assert.equal(JSON.parse(sql(finish(11,old.token))).completed,false)
  sql(`update "cmp_Users" set "User_AccessStatus"='inactive' where "User_ID"='${id(1)}';`)
  reject(finish(11,claim.token),/outside the active authorised workspace/)
  sql(`update "cmp_Users" set "User_AccessStatus"='active' where "User_ID"='${id(1)}';update "ACCI_Connections" set "ACCIC_ExternalTenantName"='Changed' where "ACCIC_ID"='${id(4)}';`)
  assert.equal(JSON.parse(sql(finish(11,claim.token))).status,'blocked')
  assert.equal(sql(`select "FINDoc_StatusCode" from "FIN_Documents" where "FINDoc_ID"='${id(11)}'`),'approved')
  assert.equal(sql(`select "ACCIER_LastSyncedAt" is null from "ACCI_ExternalRefs" where "ACCIER_LocalID"='${id(11)}'`),'t')
  sql(`update "ACCI_Connections" set "ACCIC_ExternalTenantName"='Example Ltd';`)
  setup(12);claim=JSON.parse(sql(begin(12)))
  sql(`update "FIN_Documents" set "FINDoc_StatusCode"='cancelled' where "FINDoc_ID"='${id(12)}';`)
  assert.equal(JSON.parse(sql(finish(12,claim.token))).status,'blocked')
  assert.equal(sql(`select "FINDoc_StatusCode" from "FIN_Documents" where "FINDoc_ID"='${id(12)}'`),'cancelled')
  setup(13);claim=JSON.parse(sql(begin(13)))
  assert.equal(JSON.parse(sql(finish(13,claim.token,{status:'failed',message:'Provider unavailable',issue:'provider_export_failed'}))).status,'failed')
  assert.equal(sql(`select count(*) from "ACCI_ExternalRefs" where "ACCIER_LocalID"='${id(13)}'`),'0')
  // Preserve the former queue-mock guarantees using the real transaction.
  sql(`alter table "FIN_Documents" add column "FINDoc_PostingStatusCode" text default 'posted';`)
  setup(15);claim=JSON.parse(sql(begin(15)))
  const mismatch={status:'blocked',message:'ERPNext delivery differs',issue:'provider_delivery_mismatch',externalId:'ERP-15',externalObjectType:'Sales Invoice',requestPayload:{company:'Example Ltd'},responsePayload:{state:'provider_reference_retained',deliveryVerification:{status:'mismatch'}}}
  assert.equal(JSON.parse(sql(finish(15,claim.token,mismatch))).status,'blocked')
  assert.equal(sql(`select "FINDoc_StatusCode"||':'||"FINDoc_PostingStatusCode"||':'||"FINDoc_ExportStatusCode" from "FIN_Documents" where "FINDoc_ID"='${id(15)}'`),'approved:posted:blocked')
  assert.equal(sql(`select "ACCIEI_ResponsePayloadJSON"#>>'{deliveryVerification,status}' from "ACCI_ExportItems" where "ACCIEI_ID"='${claim.itemId}'`),'mismatch')
  assert.equal(sql(`select "ACCIEI_RequestPayloadJSON"->>'company' from "ACCI_ExportItems" where "ACCIEI_ID"='${claim.itemId}'`),'Example Ltd')
  assert.equal(sql(`select count(*) from "ACCI_ReconciliationIssues" where "ACCIRI_LocalID"='${id(15)}' and "ACCIRI_IssueType"='provider_delivery_mismatch' and "ACCIRI_ExternalRefID" is not null`),'1')
  sql(`insert into "ACCI_ReconciliationIssues"("ACCIRI_ConnectionID","ACCIRI_LocalTable","ACCIRI_LocalID","ACCIRI_IssueType","ACCIRI_Title") values('${id(4)}','FIN_Documents','${id(15)}','ledger_discrepancy','Ledger'),('${id(99)}','FIN_Documents','${id(15)}','provider_delivery_mismatch','Foreign'),('${id(4)}','FIN_Documents','${id(15)}','provider_export_failed','Failure');`)
  claim=JSON.parse(sql(begin(15)))
  assert.equal(JSON.parse(sql(finish(15,claim.token))).status,'synced')
  assert.equal(sql(`select "FINDoc_StatusCode"||':'||"FINDoc_PostingStatusCode" from "FIN_Documents" where "FINDoc_ID"='${id(15)}'`),'submitted:posted')
  assert.equal(sql(`select count(*) from "ACCI_ReconciliationIssues" where "ACCIRI_LocalID"='${id(15)}' and "ACCIRI_StatusCode"='synced'`),'2')
  assert.equal(sql(`select count(*) from "ACCI_ReconciliationIssues" where "ACCIRI_LocalID"='${id(15)}' and "ACCIRI_StatusCode"='queued'`),'2')
  // Cash follows the same atomic completion, not a separate weaker path.
  const cashCanonical={...canonical(14),localTable:'FIN_CashTransactions',typeCode:'customer_receipt'}
  sql(`insert into "FIN_CashTransactions" values('${id(14)}','${id(3)}','approved','queued','customer_receipt',now(),null);insert into "FIN_IntegrationQueue"("FINIntQ_ID","FINIntQ_LocalID","FINIntQ_LocalTable") values('${id(114)}','${id(14)}','FIN_CashTransactions');`)
  claim=JSON.parse(sql(`select multideck_finance_begin_export('${id(114)}','${id(1)}','${id(4)}','${JSON.stringify(cashCanonical)}');`))
  const cashResult={status:'synced',externalId:'PAY-14',externalObjectType:'Payment Entry',responsePayload:{multideckCanonicalExport:cashCanonical,multideckDeliveryVerification:{status:'matched'}}}
  assert.equal(JSON.parse(sql(finish(14,claim.token,cashResult))).status,'synced')
  assert.equal(sql(`select "FINCash_StatusCode" from "FIN_CashTransactions" where "FINCash_ID"='${id(14)}'`),'submitted')
 }finally{if(started)spawnSync(join(bin,'pg_ctl'),['-D',join(dir,'data'),'-m','immediate','stop']);rmSync(dir,{recursive:true,force:true})}
})
