import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

const root = new URL("../functions/inbox-api/", import.meta.url)
const index = await readFile(new URL("index.ts", root), "utf8")
const runtime = await readFile(new URL("runtime.ts", root), "utf8")
const core = await readFile(new URL("core.ts", root), "utf8")
const config = await readFile(new URL("../config.toml", import.meta.url), "utf8")
const instantThreadMigration = await readFile(new URL("../migrations/20260803165000_inbox_thread_snapshot.sql", import.meta.url), "utf8")
const threadPageMigration = await readFile(new URL("../migrations/20260803166000_inbox_thread_page.sql", import.meta.url), "utf8")
const automaticReplyAuditMigration = await readFile(new URL("../migrations/20260804130000_inbox_automatic_reply_audit.sql", import.meta.url), "utf8")
const providerFolderMigration = await readFile(new URL("../migrations/20260804203000_inbox_provider_folder_catalog.sql", import.meta.url), "utf8")
const retentionMigration = await readFile(new URL("../migrations/20260805100000_inbox_twelve_month_retention.sql", import.meta.url), "utf8")
const dexterEmailContext = await readFile(new URL("../functions/agent-dexter/email-context.ts", import.meta.url), "utf8")
const dexterRuntime = await readFile(new URL("../functions/agent-dexter/index.ts", import.meta.url), "utf8")

test("authenticated Edge boundary is registered", () => {
  assert.match(config, /\[functions\.inbox-api\]\s+verify_jwt\s*=\s*true/)
  assert.match(index, /user\.auth\.getUser|requireActor/)
  assert.match(runtime, /user\.auth\.getUser\(\)/)
})

test("complete browser route contract is present", () => {
  for (const route of ["providers", "connections", "workspace", "authorize", "shared-mailboxes", "group-mailboxes", "mailboxes", "automatic-reply", "ai-context-sources", "sync", "threads", "read-state", "trash", "summary", "drafts", "send", "attachments"]) {
    assert.match(index, new RegExp(`\\b${route.replace("-", "-")}\\b`), `missing ${route}`)
  }
  for (const method of ["GET", "POST", "PATCH", "DELETE", "OPTIONS"]) assert.match(index, new RegExp(`"${method}"`))
})

test("automatic replies stay mailbox-scoped, provider-backed, and permission checked", () => {
  assert.match(index, /getAutomaticReply/)
  assert.match(index, /updateAutomaticReply/)
  assert.match(runtime, /requireMailbox\(admin, actor, mailboxId, "manage"\)/)
  assert.match(runtime, /requirePermission\(admin, actor, "Email\.Connect"\)/)
  assert.match(runtime, /gmail\.googleapis\.com\/gmail\/v1\/users\/me\/settings\/vacation/)
  assert.match(runtime, /graph\.microsoft\.com\/v1\.0\/me\/mailboxSettings/)
  assert.match(runtime, /gmail\.settings\.basic/)
  assert.match(runtime, /mailboxsettings\.readwrite/)
  assert.match(runtime, /Comm_MailboxAutomaticReplyAudit/)
  assert.doesNotMatch(runtime, /CommAutoReplyAudit_(?:Message|Subject)/)
  assert.match(automaticReplyAuditMigration, /enable row level security/)
  assert.match(automaticReplyAuditMigration, /revoke all .* anon, authenticated/)
  assert.match(automaticReplyAuditMigration, /grant all .* service_role/)
  assert.doesNotMatch(automaticReplyAuditMigration, /CommAutoReplyAudit_(?:Message|Subject)/)
})

test("Inbox startup and thread detail avoid database waterfalls", () => {
  const mailboxList = runtime.slice(runtime.indexOf("export async function listMailboxes"), runtime.indexOf("export async function aiContextSources"))
  const threadDetail = runtime.slice(runtime.indexOf("export async function getThread"), runtime.indexOf("export async function updateThreadState"))
  assert.match(index, /path\[0\] === "workspace"/)
  assert.match(runtime, /export async function inboxWorkspace/)
  assert.match(mailboxList, /comm_inbox_mailbox_unread_counts/)
  assert.doesNotMatch(mailboxList, /CommMessage_MessageDate,CommMessage_ReceivedAt,CommMessage_CreatedAt/)
  assert.match(threadDetail, /admin\.rpc\("comm_inbox_thread_snapshot"/)
  assert.match(runtime, /admin\.rpc\("comm_inbox_thread_page"/)
  assert.match(threadPageMigration, /permissionGranted/)
  assert.match(threadPageMigration, /CommMailboxAccess_CanRead/)
  assert.match(threadPageMigration, /row_number\(\) over/)
  for (const table of ["Comm_MessageRecipients", "Comm_MessageAttachments", "Comm_DeliveryEvents", "Comm_MessageTrackingTokens", "Comm_ReadStates"]) {
    assert.match(instantThreadMigration, new RegExp(table))
  }
  assert.match(instantThreadMigration, /permissionGranted/)
  assert.match(instantThreadMigration, /CommMailboxAccess_CanRead/)
  assert.match(instantThreadMigration, /CommMailboxAccess_CanSend/)
})

test("Dexter email source status is permission-aware and never exposes provider credentials", () => {
  assert.match(runtime, /export async function aiContextSources/)
  assert.match(runtime, /hasPermission\(admin, actor, "Email\.Read"\)/)
  assert.match(runtime, /hasPermission\(admin, actor, "Email\.AIRead"\)/)
  assert.match(runtime, /DEXTER_EMAIL_CONTEXT_ENABLED/)
  assert.match(runtime, /accessibleMailboxCount/)
  assert.match(runtime, /lastSyncedAt/)
  assert.doesNotMatch(index, /CommConn_SecretRef|accessToken|refreshToken/)
})

test("authorization and mailbox ACLs are enforced before service-role reads", () => {
  for (const permission of ["Email.Read", "Email.Send", "Email.Connect", "Email.ManageShared", "Email.AIRead"]) assert.match(runtime, new RegExp(permission.replace(".", "\\.")))
  assert.match(runtime, /Comm_MailboxAccess/)
  assert.match(runtime, /CommMailboxAccess_CanRead/)
  assert.match(runtime, /CommMailboxAccess_CanSendAs/)
  assert.match(runtime, /CommMailboxAccess_CanManage/)
})

test("shared Outlook consent stays explicit and shared discovery remains delegated", () => {
  assert.match(index, /body\.accessMode, body\.returnPath/)
  assert.match(runtime, /returnPath: unknown = "\/inbox"/)
  assert.match(runtime, /body: JSON\.stringify\(\{ action: "authorize", provider, accessMode, returnOrigin: origin, returnPath \}\)/)
  assert.match(runtime, /sharedMailboxAccess: oauthScopes\.has\("mail\.readwrite\.shared"\) && oauthScopes\.has\("mail\.send\.shared"\)/)
  assert.match(runtime, /users\/\$\{encodeURIComponent\(address\)\}\/mailFolders\/inbox/)
  assert.doesNotMatch(runtime, /Directory\.Read\.All/)
  assert.doesNotMatch(runtime, /organizations\/adminconsent/)
})

test("provider secrets stay in Vault and are never serialized to clients", () => {
  assert.match(runtime, /comm_get_email_secret/)
  assert.match(runtime, /comm_update_email_secret/)
  assert.doesNotMatch(index, /CommConn_SecretRef|accessToken|refreshToken/)
})

test("real Gmail and Microsoft folder sync is implemented", () => {
  assert.match(runtime, /includeSpamTrash["']?,\s*["']true/)
  assert.match(runtime, /gmail\.googleapis\.com/)
  for (const folder of ["inbox", "sentitems", "drafts", "junkemail", "deleteditems"]) assert.match(runtime, new RegExp(`"${folder}"`))
  assert.match(runtime, /`\$\{baseUrl\}\/delta`/)
  const outlookSync = runtime.slice(runtime.indexOf("async function syncOutlook"), runtime.indexOf("async function persistFolders"))
  assert.doesNotMatch(outlookSync, /const select = [^\n]*internetMessageHeaders/)
  assert.match(runtime, /Comm_MessageFolders/)
  assert.match(runtime, /CommMailFolder_RoleCode/)
  assert.match(runtime, /CommThread_SourceTypeCode: "provider_sync"/)
  assert.match(runtime, /CommMessage_SourceTypeCode: "provider_sync"/)
})

test("provider labels and nested folders remain access-checked and provider identifiers stay server-side", () => {
  assert.match(runtime, /gmailFolderCatalogue/)
  assert.match(runtime, /users\/me\/labels/)
  assert.match(runtime, /outlookFolderCatalogue/)
  assert.match(runtime, /childFolders/)
  assert.match(runtime, /CommMailbox_FolderCatalogSyncedAt/)
  assert.match(runtime, /OUTLOOK_CUSTOM_FOLDER_BATCH/)
  assert.match(runtime, /CommMailFolder_SyncCursor/)
  assert.match(runtime, /comm_inbox_provider_folder_thread_page/)
  assert.match(runtime, /\.delete\(\)\.eq\("CommMessageFolder_MessageID", messageId\)/)
  assert.match(providerFolderMigration, /permission\."sys_Permission_Value" = 'Email\.Read'/)
  assert.match(providerFolderMigration, /CommMailboxAccess_CanRead/)
  assert.match(providerFolderMigration, /grant execute on function public\.comm_inbox_provider_folder_thread_page[^;]+to service_role/s)
  assert.doesNotMatch(runtime.slice(runtime.indexOf("export async function listMailboxFolders"), runtime.indexOf("export async function aiContextSources")), /providerFolderId:/)
})

test("Dexter can read visible folder context while folder-move watches stay explicitly unsupported", () => {
  assert.match(providerFolderMigration, /multideck_dexter_email_thread_folders/)
  assert.match(providerFolderMigration, /Email\.AIRead/)
  assert.match(providerFolderMigration, /_multideck_dexter_email_mailboxes/)
  assert.match(dexterEmailContext, /multideck_dexter_email_thread_folders/)
  assert.match(dexterEmailContext, /visible Gmail labels or Outlook folders/)
  assert.match(dexterRuntime, /Label changes and folder moves do not emit a dedicated tenant-safe watch event/)
})

test("moving a conversation to trash updates the provider and local folder mapping", () => {
  assert.match(index, /path\[2\] === "trash"/)
  assert.match(runtime, /users\/me\/threads\/\$\{encodeURIComponent\(providerThreadId\)\}\/trash/)
  assert.match(runtime, /messages\/\$\{encodeURIComponent\(providerMessageId\)\}\/move/)
  assert.match(runtime, /destinationId: "deleteditems"/)
  assert.match(runtime, /persistFolders\(admin, mailboxId, message\.CommMessage_ID, \["TRASH"\]\)/)
})

test("Gmail Google Group mailboxes are read-only, address-filtered, and history-safe", () => {
  assert.match(index, /addGroupMailbox/)
  assert.match(index, /path\[2\] === "group-mailboxes"/)
  assert.match(runtime, /CommMailbox_TypeCode: "group"/)
  assert.match(runtime, /CommMailbox_OutboundEnabled: false/)
  assert.match(runtime, /CommMailboxAccess_ScopeCode: "group"/)
  assert.match(runtime, /CommMailboxAccess_CanSend: false/)
  assert.match(runtime, /CommMailboxAccess_CanSendAs: false/)
  assert.match(runtime, /CommThread_IsReadOnly: mailbox\.CommMailbox_TypeCode === "group"/)
  assert.match(runtime, /groupAddress \? gmailGroupQuery\(groupAddress\) : ""/)
  assert.match(runtime, /url\.searchParams\.set\("includeSpamTrash", "true"\)/)
  assert.match(runtime, /gmailMessageMatchesGroup/)
  assert.match(core, /deliveredto:\$\{address\}/)
  assert.match(core, /list:\$\{address\}/)
  assert.match(core, /exact normalized addresses/)
})

test("provider sync retains continuation pages instead of skipping mailbox history", () => {
  assert.match(runtime, /kind: "gmail_history"/)
  assert.match(runtime, /readHistoryPage\(startHistoryId, historyPage\?\.pageToken\)/)
  assert.match(runtime, /if \(pageToken\) url\.searchParams\.set\("pageToken", pageToken\)/)
  assert.match(runtime, /hasMore = !!history\.nextPageToken/)
  assert.match(runtime, /const nextLink = cleanString\(page\["@odata\.nextLink"\]/)
  assert.match(runtime, /hasMore: sync\.hasMore/)
  assert.match(runtime, /error\.providerStatus === 404/)
  assert.match(runtime, /Prefer: `odata\.maxpagesize=\$\{OUTLOOK_BACKFILL_PAGE_SIZE\}`/)
  assert.doesNotMatch(runtime, /messages\/delta\?\$select=\$\{encodeURIComponent\(select\)\}&\$top=/)
  assert.match(runtime, /OUTLOOK_RETENTION_CURSOR_KIND/)
  assert.match(runtime, /phase: "delta_init"/)
  assert.match(runtime, /phase: "delta"/)
  assert.match(core, /public readonly providerStatus\?: number/)
})

test("mailbox sync reports durable historical indexing progress", () => {
  assert.match(runtime, /resultSizeEstimate/)
  assert.match(runtime, /totalItemCount/)
  assert.match(runtime, /CommMailbox_IndexStatus/)
  assert.match(runtime, /CommMailbox_IndexProcessedCount/)
  assert.match(runtime, /CommMailbox_IndexTotalEstimate/)
  assert.match(runtime, /indexPercent/)
  assert.match(runtime, /sync\.hasMore \|\| indexedCount < estimatedTotal/)
})

test("provider mail is retention-bounded before persistence and cleanup stays incremental", () => {
  assert.match(runtime, /INBOX_CORE_RETENTION_MONTHS = 12/)
  assert.match(runtime, /INBOX_WASTE_RETENTION_DAYS = 30/)
  assert.match(runtime, /gmailRetentionQuery\(retention\)/)
  assert.match(runtime, /return `\{after:\$\{gmailAfterDate\(cutoffs\.core\)\} is:draft\}`/)
  const gmailFetch = runtime.slice(runtime.indexOf("const fetchMessages"), runtime.indexOf("// The frequent worker"))
  assert.ok(gmailFetch.indexOf("?format=metadata") < gmailFetch.indexOf("?format=full"))
  assert.match(gmailFetch, /providerMessageWithinRetention\(metadataMessage, retention\)/)
  assert.match(runtime, /receivedDateTime ge \$\{cutoff\.toISOString\(\)\}/)
  assert.match(runtime, /providerMessageWithinRetention/)
  assert.match(runtime, /historyTypes", "messageDeleted"/)
  assert.match(runtime, /row\["@removed"\]/)
  assert.match(runtime, /comm_remove_provider_messages/)
  assert.match(retentionMigration, /comm_purge_expired_provider_mail/)
  assert.match(retentionMigration, /comm_compact_provider_mail/)
  assert.match(retentionMigration, /for update of message skip locked/)
  assert.match(retentionMigration, /limit p_batch_size[\s\S]+for update of message skip locked/)
  assert.match(retentionMigration, /CommMessage_SourceTypeCode" = 'provider_sync'/)
  assert.match(retentionMigration, /not message\."CommMessage_IsDraft"/)
  assert.doesNotMatch(retentionMigration, /update public\."AI_DexterEmailSearchDocuments" search_document/)
})

test("retention compacts duplicate HTML text without weakening Dexter search or private images", () => {
  assert.match(runtime, /HTML_DUPLICATE_TEXT_LIMIT = 20_000/)
  assert.match(runtime, /DEXTER_SEARCH_BODY_LIMIT = 512_000/)
  assert.match(runtime, /typeof body\.data === "string"/)
  assert.match(runtime, /const bodyContent = typeof body\.content === "string"/)
  assert.doesNotMatch(runtime, /cleanString\(body\.content, 2_000_000\)/)
  assert.match(runtime, /multideck_index_dexter_email_body/)
  assert.match(retentionMigration, /AIDexterEmailSearch_BodyDocument/)
  assert.match(retentionMigration, /AIDexterEmailSearch_ParticipantDocument/)
  assert.match(retentionMigration, /AIDexterEmailSearch_AttachmentDocument/)
  assert.match(retentionMigration, /AIDexterEmailSearch_IsSegmented/)
  assert.match(retentionMigration, /on delete set null/)
  assert.match(retentionMigration, /multideck\.retention_cleanup/)
})

test("concurrent Inbox views cannot advance the same provider cursor together", () => {
  assert.match(runtime, /Comm_AcquireMailboxSyncLease/)
  assert.match(runtime, /Comm_ReleaseMailboxSyncLease/)
  assert.match(runtime, /p_lease_seconds: 180/)
  assert.match(runtime, /if \(!leaseAcquired\)/)
  assert.match(runtime, /requiresReconnect && mailbox\.CommMailbox_IndexStatus !== "ready"/)
})

test("provider detail reads are bounded and cannot hang the Edge request indefinitely", () => {
  assert.match(runtime, /mapWithConcurrency\(ids\.slice\(0, 100\), 8/)
  assert.match(runtime, /GMAIL_BACKFILL_PAGE_SIZE = 20/)
  assert.match(runtime, /OUTLOOK_BACKFILL_PAGE_SIZE = 20/)
  assert.match(runtime, /mapWithConcurrency\([\s\S]+?Array\.isArray\(page\.value\)/)
  assert.match(runtime, /setTimeout\(\(\) => controller\.abort\(\), 15_000\)/)
  assert.match(runtime, /provider_timeout/)
})

test("Microsoft Graph failures retain a safe provider code without logging credentials or request URLs", () => {
  const providerJson = runtime.slice(runtime.indexOf("async function providerJson"), runtime.indexOf("function gmailBodies"))
  assert.match(providerJson, /Microsoft Graph request failed/)
  assert.match(providerJson, /providerError\.code/)
  assert.match(providerJson, /providerDiagnostic/)
  assert.match(providerJson, /\[email\]/)
  assert.match(providerJson, /\[url\]/)
  assert.doesNotMatch(providerJson, /console\.error\([^\n]*url/)
  assert.doesNotMatch(providerJson, /console\.error\([^\n]*token/)
})

test("Outlook attachment lists request only base attachment properties", () => {
  const parseGraphMessage = runtime.slice(runtime.indexOf("async function parseGraphMessage"), runtime.indexOf("async function syncOutlook"))
  assert.match(parseGraphMessage, /attachments\?\$select=id,name,contentType,size,isInline/)
  assert.doesNotMatch(parseGraphMessage, /attachments\?\$select=[^`\n]*contentId/)
  assert.match(parseGraphMessage, /attachments\/\$\{encodeURIComponent\(item\.id\)\}\?\$select=id,contentId/)
  assert.match(parseGraphMessage, /item\.isInline === true \|\| referenced\.size > 0/)
  assert.match(parseGraphMessage, /inferGraphContentIdFromFileName\(item\.name, referenced\)/)
  assert.match(parseGraphMessage, /item\.isInline === true \|\| Boolean\(normalizedContentId && referenced\.has\(normalizedContentId\)\)/)
  assert.match(parseGraphMessage, /mapWithConcurrency\(Array\.isArray\(list\.value\)/)
})

test("inline message images repair legacy content IDs and use the private attachment route", () => {
  assert.match(runtime, /hydrateOutlookInlineContentIds/)
  assert.match(runtime, /CommAttachment_ContentID: contentId/)
  const repair = runtime.slice(runtime.indexOf("async function hydrateOutlookInlineContentIds"), runtime.indexOf("export async function getThread"))
  assert.doesNotMatch(repair, /if \(!missing\.length\) return/)
  assert.match(repair, /const messagesNeedingRepair = messages\.filter/)
  assert.doesNotMatch(repair, /filter\(\(item: Row\) => item\.isInline === true\)/)
  assert.match(repair, /Array\.isArray\(list\.value\) \? list\.value : \[\]\)\.slice\(0, 24\)/)
  assert.match(repair, /inferGraphContentIdFromFileName\(item\.name, referenced\)/)
  assert.match(repair, /outlookMimeInlineAttachmentHeaders/)
  assert.match(repair, /mimeContentIdByFileName\.get/)
  assert.match(runtime, /allowInline && !item\.CommAttachment_IsInline/)
  assert.match(index, /searchParams\.get\("disposition"\) === "inline"/)
  assert.match(index, /inline \? "inline" : "attachment"/)
})

test("real mailbox lists avoid full-body reads and batch large database filters", () => {
  const listThreads = runtime.slice(runtime.indexOf("export async function listThreads"), runtime.indexOf("async function mailboxProviderMap"))
  assert.doesNotMatch(listThreads, /from\("Comm_Messages"\)\.select\("\*"\)/)
  assert.match(listThreads, /CommMessage_BodyPreview/)
  assert.match(listThreads, /readInBatches<Row>\(messages\.map/)
  assert.match(listThreads, /readInBatches<Row>\(threadIds/)
  assert.match(listThreads, /readInBatches<Row>\(pageMessageIds/)
})

test("send path has an atomic idempotency claim and all response modes", () => {
  assert.match(runtime, /sha256Hex\(`\$\{actor\.userId\}:\$\{suppliedKey\}`\)/)
  assert.match(runtime, /CommMessage_StatusCode: "sending"/)
  assert.match(runtime, /CommSend_StatusCode: "sending"/)
  for (const mode of ["new", "reply", "reply_all", "forward"]) assert.match(runtime, new RegExp(`"${mode}"`))
  assert.match(runtime, /createReplyAll/)
  assert.match(runtime, /createForward/)
})

test("CORS, HTML and attachment hardening remain fail closed", () => {
  assert.match(core, /assertAllowedRequestOrigin/)
  assert.doesNotMatch(core, /Access-Control-Allow-Origin"\]\s*=\s*"\*"/)
  assert.match(core, /sanitizeEmailHtml/)
  assert.match(index, /X-Content-Type-Options/)
  assert.match(index, /private, no-store/)
})

test("real mail previews decode entities and Gmail encodes international headers", () => {
  assert.match(core, /export function decodeHtmlEntities/)
  assert.match(runtime, /preview: decodeHtmlEntities\(latest\.CommMessage_BodyPreview/)
  assert.match(core, /export function encodeHeaderValue/)
  assert.match(core, /Subject: \$\{encodeHeaderValue\(input\.subject\)\}/)
})
