import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

const read = (path) => readFile(new URL(path, import.meta.url), "utf8")
const migration = await read("../migrations/20260819105000_inbox_thread_detail_paging.sql")
const runtime = await read("../functions/inbox-api/runtime.ts")
const edge = await read("../functions/inbox-api/index.ts")
const contract = await read("../../multideck.client/src/lib/inbox-contract.ts")
const api = await read("../../multideck.client/src/lib/inbox-api.ts")
const workspace = await read("../../multideck.client/src/lib/inbox-workspace.tsx")
const page = await read("../../multideck.client/src/pages/inbox-page.tsx")
const benchmark = await read("../../multideck.client/benchmarks/inbox-thread-detail-paging.mjs")
const supportingReadMigration = await read("../migrations/20260819142000_admin_presence_inbox_reply_bounds.sql")

test("the database returns one exact, tenant-safe message page capped at 50", () => {
  assert.match(migration, /create or replace function public\.comm_inbox_thread_page\(/)
  assert.match(migration, /v_limit integer := greatest\(1, least\(coalesce\(p_limit, 25\), 50\)\)/)
  assert.match(migration, /'messageTotal', v_message_count/)
  assert.match(migration, /'hasOlderMessages'/)
  assert.match(migration, /limit v_limit\s+offset v_offset/)
  assert.match(migration, /where recipient\."CommRecipient_MessageID" in \(select id from message_ids\)/)
  assert.match(migration, /where attachment\."CommAttachment_MessageID" in \(select id from message_ids\)/)
  assert.match(migration, /where event\."CommDelivery_MessageID" in \(select id from message_ids\)/)
  assert.match(migration, /reply\."CommMessage_ReplyToMessageID" in/)
  assert.match(migration, /revoke all on function public\.comm_inbox_thread_page\(uuid,uuid,integer,integer\) from public, anon, authenticated/)
  assert.match(migration, /grant execute on function public\.comm_inbox_thread_page\(uuid,uuid,integer,integer\) to service_role/)
})

test("the Edge route pages thread detail and fails closed when the RPC is missing", () => {
  assert.match(edge, /getThread\(clients\.admin, actor, path\[1\], new URL\(request\.url\)\)/)
  assert.match(runtime, /\["42883", "PGRST202"\]\.includes/)
  assert.match(runtime, /admin\.rpc\("comm_inbox_thread_page"/)
  assert.match(runtime, /p_limit: limit/)
  assert.match(runtime, /p_offset: offset/)
  assert.match(runtime, /else if \(missingInboxReadModel\(paged\.error\)\)/)
  assert.match(runtime, /thread_paging_unavailable/)
  assert.match(runtime, /new InboxHttpError\(503/)
  assert.doesNotMatch(runtime, /comm_inbox_thread_snapshot|legacyThreadPage/)
  assert.match(runtime, /else \{\s+snapshot = await result<Row>\(Promise\.resolve\(paged\)\)/)
  assert.match(runtime, /messageTotal:/)
  assert.match(runtime, /hasOlderMessages:/)
})

test("mailbox and AI thread reads stay bounded instead of rebuilding whole inboxes", () => {
  const listThreads = runtime.slice(runtime.indexOf("export async function listThreads"), runtime.indexOf("async function hydrateOutlookInlineContentIds"))
  const threadData = runtime.slice(runtime.indexOf("async function threadData"), runtime.indexOf("export async function listThreads"))
  assert.match(listThreads, /mailbox_required/)
  assert.match(listThreads, /Choose a mailbox before loading email threads/)
  assert.doesNotMatch(listThreads, /\.limit\(1000\)|readInBatches|mailboxProviderMap/)
  assert.match(threadData, /\.in\("CommMessage_MailboxID", \[\.\.\.accessible\]\)/)
  assert.match(threadData, /\.limit\(100\)/)
  assert.match(runtime, /const replyCandidates[\s\S]*\.order\("CommMessage_CreatedAt", \{ ascending: false \}\)[\s\S]*\.limit\(200\)/)
  assert.match(supportingReadMigration, /"IX_Comm_Messages_reply_candidates"/)
  assert.match(supportingReadMigration, /where not "CommMessage_IsInbound"\s+and not "CommMessage_IsDeleted"/)
})

test("the browser requires bounded server pages and merges older pages without duplicates", () => {
  assert.match(contract, /messageTotal: number/)
  assert.match(contract, /hasOlderMessages: boolean/)
  assert.match(contract, /if \(explicitTotal === undefined\)/)
  assert.match(contract, /Inbox message paging is still being prepared/)
  assert.doesNotMatch(contract, /legacyEnd|legacyStart|normalizedMessages\.slice/)
  assert.match(api, /new URLSearchParams\(\{ limit: String\(limit\), offset: String\(offset\) \}\)/)
  assert.match(workspace, /fetchOlderThreadMessages:/)
  assert.match(workspace, /getThread\(threadId, \{ offset: safeOffset, limit: 25 \}\)/)
  assert.match(workspace, /const seen = new Set<string>\(\)/)
  assert.match(workspace, /messages = \[\.\.\.page\.messages, \.\.\.current\.messages\]\.filter/)
  assert.match(workspace, /messageLimit: messages\.length/)
})

test("conversation bodies are intent-driven and the UI exposes explicit older-message paging", () => {
  const warmEffect = workspace.slice(workspace.indexOf("// Warm only the first visible list page"), workspace.indexOf("const applySelection"))
  assert.match(warmEffect, /fetchThreadPage/)
  assert.doesNotMatch(warmEffect, /prefetchThreadDetail/)
  assert.match(page, /onPrefetch=\{\(\) => prefetchThreadDetail\(item\.id\)\}/)
  assert.match(page, /t\("Load older messages"\)/)
  assert.match(page, /fetchOlderThreadMessages\(targetThreadId, thread\.messages\.length\)/)
  assert.match(page, /role="alert"/)
})

test("the controlled proof models scale without inserting Supabase records", () => {
  assert.match(benchmark, /const mailboxRecordCount = 100_000/)
  assert.match(benchmark, /const hotThreadMessageCount = 5_000/)
  assert.match(benchmark, /const detailPageSize = 25/)
  assert.match(benchmark, /const warmups = 2/)
  assert.match(benchmark, /const runs = 9/)
  assert.match(benchmark, /supabase_writes: 0/)
  assert.doesNotMatch(benchmark, /createClient|SUPABASE_URL|\.insert\(|\.upsert\(/)
})
