// Choices observed in the iCustoms import editor on 14 September 2026.
export const customsAuthorisationCategories = [
  ["ACE", "Authorised consignee for Union transit"],
  ["ACP", "Authorised issuer of proof of Union goods status"],
  ["ACR", "Authorised consignor for Union transit"],
  ["ACT", "Authorised consignee for TIR procedure"],
  ["AEOC", "Authorised Economic Operator — Customs simplifications"],
  ["AEOF", "Authorised Economic Operator — Customs simplifications, security and safety"],
  ["AEOS", "Authorised Economic Operator — Security and safety"],
  ["APEX", "Approved exporter"], ["AWB", "Authorised weigher of bananas"],
  ["BOI", "Binding Origin Information"], ["BRD", "Bulk Import Reduced Data Set authorisation"],
  ["BTI", "Binding Tariff Information"], ["CCL", "Centralised clearance authorisation"],
  ["CGU", "Customs comprehensive guarantee"], ["CSDR", "Community System of Duty Reliefs"],
  ["CSE", "Customs Supervised Exports"],
  ["CVA", "Simplified determination of amounts included in customs value"],
  ["CW1", "Operate a public customs warehouse — type I"],
  ["CW2", "Operate a public customs warehouse — type II"],
  ["CWP", "Operate a private customs warehouse"],
  ["DEP", "Designated Export Place"], ["DPO", "Deferment of payment authorisation"],
  ["EIR", "Entry in the declarant’s records (EIDR) authorisation"],
  ["EORI", "Economic Operator Registration and Identification"],
  ["EXRR", "RORO exporter"], ["EPSS", "Excise Payment Security System"],
  ["ETD", "Electronic Transport Document authorised as a customs declaration"],
  ["EUS", "End Use authorisation"], ["EXEE", "Registered consignee (excise)"],
  ["EXOR", "Registered consignor (excise)"], ["EXW", "Excise warehouse"],
  ["EXWH", "Excise warehouse — Hydrocarbon oils"], ["FAS", "Flexible Accounting System"],
  ["FP", "Freeport authorisation"], ["FTI", "Fixed Transport Installation"],
  ["FZ", "Free zone — Isle of Man only"], ["GGA", "General Guarantee Account"],
  ["GVS", "General Valuation Statement"],
  ["IOSI", "Import One Stop Shop (IOSS) — Intermediary VAT identification number"],
  ["IOST", "Import One Stop Shop (IOSS) — Taxable person VAT identification number"],
  ["IPO", "Inward Processing authorisation"],
  ["MOU", "Memorandum of Understanding — Approved exporters only"],
  ["OPO", "Outward Processing authorisation"],
  ["REM", "Remission of import or export duty"], ["REP", "Repayment of import or export duty"],
  ["REX", "Registered exporter"], ["RSS", "Regular Shipping Services authorisation"],
  ["SAS", "Self-assessment authorisation"], ["SASP", "Single Authorisation for Simplified Procedures"],
  ["SDE", "Simplified Declaration Procedure (SDP) authorisation"],
  ["SIVA", "Simplified Import VAT Accounting"], ["SSE", "Authorisation to use seals of a special type"],
  ["TEA", "Temporary Admission authorisation"],
  ["TEAH", "Temporary Admission — Auction houses (no VAT guarantee required)"],
  ["TRD", "Transit declaration with a reduced dataset"],
  ["TST", "Operate temporary storage facilities"], ["UKCS", "UK Continental Shelf"],
  ["UKD", "UK Destination authorisation"], ["UKTS", "UK Trader Scheme authorisation"],
  ["UKIM", "UK Internal Market Scheme authorisation"],
  ["MIB", "Merchandise in Baggage — Not for Northern Ireland exports"],
  ["ATR", "Advance Tariff Ruling"], ["AOR", "Advance Origin Ruling"],
  ["AVR", "Advance Valuation Ruling"], ["NIRM", "EORI number of the NIRMS authorisation holder"],
] as const
