export const freightPackageTypeOptions = [
  { id: "PX", value: "Pallets", label: "Pallets", description: "PX · Standard freight pallets", keywords: ["PLT", "pallet"] },
  { id: "CT", value: "Cartons", label: "Cartons", description: "CT · Cartons", keywords: ["CTN", "carton"] },
  { id: "BX", value: "Boxes", label: "Boxes", description: "BX · Boxes", keywords: ["BOX", "box"] },
  { id: "CR", value: "Crates", label: "Crates", description: "CR · Crates", keywords: ["CRT", "crate"] },
  { id: "CS", value: "Cases", label: "Cases", description: "CS · Cases", keywords: ["CAS", "case"] },
  { id: "PK", value: "Packages", label: "Packages", description: "PK · General packages", keywords: ["PKG", "package"] },
  { id: "PP", value: "Pieces", label: "Pieces", description: "PP · Loose pieces", keywords: ["PCS", "piece"] },
  { id: "bags", value: "Bags", label: "Bags", description: "Bags and flexible packaging", keywords: ["BAG", "bag"] },
  { id: "sacks", value: "Sacks", label: "Sacks", description: "Sacks", keywords: ["SAK", "sack"] },
  { id: "DR", value: "Drums", label: "Drums", description: "DR · Drums", keywords: ["DRM", "drum"] },
  { id: "barrels", value: "Barrels", label: "Barrels", description: "Barrels", keywords: ["BRL", "barrel"] },
  { id: "bundles", value: "Bundles", label: "Bundles", description: "Bundled cargo", keywords: ["BDL", "bundle", "bunch"] },
  { id: "rolls", value: "Rolls", label: "Rolls", description: "Rolled goods", keywords: ["ROL", "roll"] },
  { id: "reels", value: "Reels", label: "Reels", description: "Cable, wire or material reels", keywords: ["REL", "reel"] },
  { id: "ibcs", value: "IBCs", label: "IBCs", description: "Intermediate bulk containers", keywords: ["IBC", "bulk container"] },
  { id: "totes", value: "Totes", label: "Totes", description: "Reusable tote containers", keywords: ["TOT", "tote"] },
  { id: "ulds", value: "ULDs", label: "ULDs", description: "Air cargo unit load devices", keywords: ["ULD", "air container", "air pallet"] },
  { id: "loose", value: "Loose / unpackaged", label: "Loose / unpackaged", description: "Cargo without outer packaging", keywords: ["LSE", "loose", "unpacked"] },
] as const
