import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react"
import { AnimatePresence, motion } from "motion/react"
import { ArrowLeft, ArrowRight, Building2, Check, FileText, LoaderCircle, Mail, MapPin, Pencil, Plus, RefreshCw, Ship, Sparkles, Users } from "lucide-react"
import { toast } from "sonner"
import { ContactCreateDialog } from "@/components/multideck/contact-create-dialog"
import { CustomerAvatar } from "@/components/multideck/customer-components"
import { MarketingOptInControl } from "@/components/multideck/marketing-opt-in-control"
import { Surface } from "@/components/multideck/surface"
import { StatusPill } from "@/components/multideck/status-pill"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { useLanguage } from "@/i18n/language-provider"
import { getCustomer, getCustomerReference, updateAccount, type ApiCustomerDetail, type CustomerReference, type UpdateAccountInput } from "@/lib/customer-api"
import { CustomerWarehouseAccess } from "@/pages/customer-detail-page"

type CustomField = { id: string; label: string; value: string }
type AccountDraft = UpdateAccountInput & { customFields: CustomField[] }

export function CrmAccountDetailPage({ accountId, navigate }: { accountId: string; navigate: (path: string) => void }) {
  const { t } = useLanguage()
  const [account, setAccount] = useState<ApiCustomerDetail | null>(null)
  const [state, setState] = useState<"loading" | "ready" | "error">("loading")
  const [error, setError] = useState<string | null>(null)
  const [reloadToken, setReloadToken] = useState(0)
  const [editOpen, setEditOpen] = useState(false)
  const [addContactOpen, setAddContactOpen] = useState(false)
  const [draft, setDraft] = useState<AccountDraft | null>(null)
  const [reference, setReference] = useState<CustomerReference | null>(null)
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    let active = true
    setState("loading")
    setError(null)
    Promise.all([getCustomer(accountId), getCustomerReference()]).then(([data, nextReference]) => { if (active) { setAccount(data); setDraft(toDraft(data)); setReference(nextReference); setState("ready") } }).catch((cause) => {
      if (!active) return
      setError(cause instanceof Error ? cause.message : t("This account could not be loaded. Check your connection and try again."))
      setState("error")
    })
    return () => { active = false }
  }, [accountId, reloadToken, t])

  async function saveAccount(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (!draft) return
    setSaving(true)
    try {
      const metadata = { ...draft.metadata, customFields: Object.fromEntries(draft.customFields.filter((field) => field.label.trim()).map((field) => [field.label.trim(), field.value.trim()])) }
      const updated = await updateAccount(accountId, { ...draft, metadata })
      setAccount(updated)
      setDraft(toDraft(updated))
      setEditOpen(false)
      toast.success(t("Account updated"))
    } catch (cause) {
      toast.error(cause instanceof Error ? cause.message : t("The account could not be updated. Your changes are still in the form."))
    } finally {
      setSaving(false)
    }
  }

  if (state === "loading") return <PageState icon={<LoaderCircle className="size-6 animate-spin" />} title={t("Loading account…")} />
  if (state === "error" || !account) return <div className="md-page md-page-stack"><Button variant="ghost" className="w-fit" onClick={() => navigate("/crm/accounts")}><ArrowLeft className="size-4 rtl:rotate-180" />{t("Back to accounts")}</Button><PageState icon={<RefreshCw className="size-6" />} title={t("Account unavailable")} detail={error ?? undefined} action={<Button variant="outline" onClick={() => setReloadToken((value) => value + 1)}>{t("Try again")}</Button>} embedded /></div>

  const openExceptions = account.activeShipments.reduce((total, shipment) => total + shipment.openExceptionCount, 0)
  const customFields = Object.entries((account.metadata.customFields && typeof account.metadata.customFields === "object" ? account.metadata.customFields : {}) as Record<string, unknown>)

  return <div className="md-page md-page-stack">
    <Button variant="ghost" className="w-fit rounded-[var(--md-radius-md)] px-2 text-[13px]" onClick={() => navigate("/crm/accounts")}><ArrowLeft className="size-4 rtl:rotate-180" strokeWidth={1.4} />{t("Back to accounts")}</Button>
    <header className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between">
      <div className="flex min-w-0 items-start gap-4"><CustomerAvatar initials={account.initials} tone="teal" size="lg" /><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="text-[24px] font-medium leading-tight text-[var(--md-ink)]">{account.name}</h1>{account.tier ? <StatusPill tone="teal">{account.tier}</StatusPill> : null}<StatusPill tone={account.marketingOptIn ? "green" : "neutral"}>{t(account.marketingOptIn ? "Marketing opted in" : "Marketing opted out")}</StatusPill></div><p className="mt-2 text-[13px] text-[var(--md-text)]">{[account.vertical || account.industry, account.location, humanize(account.relationshipStatus)].filter(Boolean).join(" · ")}</p>{account.summary ? <p className="mt-3 max-w-[760px] text-[14px] leading-6 text-[var(--md-ink)]">{account.summary}</p> : null}</div></div>
      <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setAddContactOpen(true)}><Plus className="size-4" />{t("Add contact")}</Button><Button onClick={() => setEditOpen(true)} className="bg-[var(--md-accent)] text-[var(--md-accent-ink)] active:scale-[0.96] motion-reduce:transform-none"><Pencil className="size-4" />{t("Edit account")}</Button></div>
    </header>

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Users} label={t("Contacts")} value={String(account.contacts.length)} /><Metric icon={Ship} label={t("Active shipments")} value={String(account.activeShipments.length)} /><Metric icon={Sparkles} label={t("Account health")} value={account.healthScore == null ? "—" : `${Math.round(account.healthScore)}%`} /><Metric icon={Building2} label={t("Open exceptions")} value={String(openExceptions)} tone={openExceptions ? "amber" : "neutral"} /></div>

    <div className="grid gap-[var(--md-page-stack-gap)] 2xl:grid-cols-[minmax(0,1fr)_390px]">
      <div className="grid content-start gap-[var(--md-page-stack-gap)]">
        <Panel title={t("Latest updates")} meta={account.activities.length ? t("Newest first") : undefined}>
          {account.activities.length ? account.activities.map((activity, index) => <ActivityRow key={activity.id} activity={activity} last={index === account.activities.length - 1} />) : <Empty text={t("No account updates have been recorded yet.")} />}
        </Panel>
        <Panel title={t("Recent emails")} meta={account.recentEmails.available ? `${account.recentEmails.items.length}` : t("Permission required")}>
          {!account.recentEmails.available ? <Empty text={t("You need email access to see account conversations here.")} /> : account.recentEmails.items.length ? account.recentEmails.items.map((email, index) => <button key={email.id} type="button" onClick={() => navigate(`/inbox?thread=${email.threadId}`)} className={`group flex w-full items-start gap-3 px-5 py-4 text-start hover:bg-[var(--md-surface-soft)] focus-visible:outline-none focus-visible:ring-[3px] focus-visible:ring-inset focus-visible:ring-[var(--md-accent-a14)] ${index ? "border-t border-[var(--md-line)]" : ""}`}><span className={`mt-0.5 grid size-8 shrink-0 place-items-center rounded-[var(--md-radius-md)] ${email.direction === "inbound" ? "bg-[var(--md-accent-a11)] text-[var(--md-accent)]" : "bg-[var(--md-surface-tint)] text-[var(--md-text)]"}`}><Mail className="size-4" strokeWidth={1.4} /></span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-4"><span className="truncate text-[14px] font-medium text-[var(--md-ink)]">{email.subject}</span><span className="shrink-0 text-[12px] tabular-nums text-[var(--md-subtle)]">{relativeDate(email.occurredAt, t)}</span></span><span className="mt-1 block truncate text-[12px] text-[var(--md-text)]">{[email.contactName || email.contactEmail, email.preview].filter(Boolean).join(" · ")}</span></span><ArrowRight className="mt-2 size-4 shrink-0 text-[var(--md-subtle)] transition-transform duration-150 group-hover:translate-x-0.5 rtl:rotate-180 rtl:group-hover:-translate-x-0.5 motion-reduce:transition-none" strokeWidth={1.4} /></button>) : <Empty text={t("No recent emails are linked to this account or its contacts.")} />}
        </Panel>
        <Panel title={t("Active shipments")} meta={String(account.activeShipments.length)}>{account.activeShipments.length ? account.activeShipments.map((shipment, index) => <div key={shipment.id} className={`grid gap-3 px-5 py-4 sm:grid-cols-[130px_minmax(0,1fr)_auto] sm:items-center ${index ? "border-t border-[var(--md-line)]" : ""}`}><p className="text-[13px] font-medium text-[var(--md-ink)]">{shipment.reference}</p><div className="min-w-0"><p className="truncate text-[14px] font-medium text-[var(--md-ink)]">{shipment.route || t("Route not recorded")}</p><p className="mt-1 text-[12px] text-[var(--md-text)]">{[shipment.mode, shipment.status, shipment.eta ? `${t("ETA")} ${formatDate(shipment.eta)}` : null].filter(Boolean).join(" · ")}</p></div><StatusPill tone={shipment.openExceptionCount ? "amber" : "green"}>{shipment.openExceptionCount ? `${shipment.openExceptionCount} ${t("exceptions")}` : t("On track")}</StatusPill></div>) : <Empty text={t("No active shipments are linked to this account.")} />}</Panel>
        <CustomerWarehouseAccess customerId={account.id} />
      </div>

      <aside className="grid content-start gap-[var(--md-page-stack-gap)]">
        <Panel
          title={t("Contacts")}
          meta={String(account.contacts.length)}
          action={<Button type="button" variant="ghost" className="h-8 rounded-[var(--md-radius-md)] px-2 text-[12px]" onClick={() => setAddContactOpen(true)}><Plus className="size-3.5" strokeWidth={1.5} />{t("Add contact")}</Button>}
        >{account.contacts.length ? account.contacts.map((contact, index) => <button key={contact.id} type="button" onClick={() => navigate(`/crm/contacts/${contact.id}`)} className={`group flex min-h-16 w-full items-center gap-3 px-5 py-3 text-start hover:bg-[var(--md-surface-soft)] focus-visible:outline-none focus-visible:ring-[3px] focus-visible:ring-inset focus-visible:ring-[var(--md-accent-a14)] ${index ? "border-t border-[var(--md-line)]" : ""}`}><CustomerAvatar initials={contact.initials} tone="blue" /><span className="min-w-0 flex-1"><span className="block truncate text-[14px] font-medium text-[var(--md-ink)]">{contact.name}</span><span className="mt-0.5 block truncate text-[12px] text-[var(--md-text)]">{contact.jobTitle || contact.role || contact.email || t("No contact details recorded")}</span></span><ArrowRight className="size-4 text-[var(--md-subtle)] transition-transform duration-150 group-hover:translate-x-0.5 rtl:rotate-180 rtl:group-hover:-translate-x-0.5 motion-reduce:transition-none" strokeWidth={1.4} /></button>) : <Empty text={t("No contacts are linked to this account.")} />}</Panel>
        <Panel title={t("Account details")}><DetailList rows={[[t("Owner"), account.ownerName || t("Unassigned")],[t("Segment"), account.segment],[t("Primary mode"), account.primaryMode],[t("Trade lane"), account.primaryTradeLane],[t("Growth state"), account.growthState],[t("Customer since"), formatDate(account.customerSince)]]} /></Panel>
        <Panel title={t("Communication")}><DetailList rows={[[t("Preferred channel"), humanize(account.engagement?.preferredChannel)],[t("Follow-up messages"), t(account.engagement?.allowFollowupMessages === false ? "Not allowed" : "Allowed")],[t("WhatsApp"), t(account.engagement?.allowWhatsApp ? "Allowed" : "Not allowed")],[t("Minimum gap"), account.engagement ? `${account.engagement.minHoursBetweenNonUrgentMessages} ${t("hours")}` : null],[t("Marketing consent"), t(account.marketingOptIn ? "Opted in" : "Opted out")],[t("Consent source"), humanize(account.marketingConsentSource)]]} /></Panel>
        <Panel title={t("Address")}><div className="px-5 pb-5 pt-1 text-[13px] leading-6 text-[var(--md-text)]"><div className="flex gap-3"><MapPin className="mt-1 size-4 shrink-0 text-[var(--md-accent)]" strokeWidth={1.4} /><address className="not-italic">{account.address ? [account.address.line1, account.address.line2, account.address.townCity, account.address.countyState, account.address.postZipCode, account.address.countryCode].filter(Boolean).map((line) => <span key={line} className="block">{line}</span>) : t("No address recorded")}</address></div>{account.address?.mainEmail ? <a dir="ltr" className="mt-3 block text-start text-[var(--md-accent)]" href={`mailto:${account.address.mainEmail}`}>{account.address.mainEmail}</a> : null}{account.address?.mainPhone ? <a dir="ltr" className="mt-1 block text-start text-[var(--md-accent)]" href={`tel:${account.address.mainPhone}`}>{account.address.mainPhone}</a> : null}</div></Panel>
        {customFields.length ? <Panel title={t("Additional fields")}><DetailList rows={customFields.map(([label, value]) => [label, typeof value === "string" ? value : String(value)])} /></Panel> : null}
      </aside>
    </div>

    <AccountEditDialog open={editOpen} onOpenChange={setEditOpen} draft={draft} setDraft={setDraft} relationshipStatuses={reference?.relationshipStatuses ?? []} originalMarketingOptIn={account.marketingOptIn} saving={saving} onSubmit={saveAccount} />
    <ContactCreateDialog accounts={[account]} fixedAccountId={account.id} open={addContactOpen} onOpenChange={setAddContactOpen} onCreated={(contact) => { setReloadToken((value) => value + 1); navigate(`/crm/contacts/${contact.id}`) }} />
  </div>
}

function AccountEditDialog({ open, onOpenChange, draft, setDraft, relationshipStatuses, originalMarketingOptIn, saving, onSubmit }: { open: boolean; onOpenChange: (open: boolean) => void; draft: AccountDraft | null; setDraft: (draft: AccountDraft) => void; relationshipStatuses: CustomerReference["relationshipStatuses"]; originalMarketingOptIn: boolean; saving: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  const { t } = useLanguage()
  if (!draft) return null
  const set = <K extends keyof AccountDraft>(key: K, value: AccountDraft[K]) => setDraft({ ...draft, [key]: value })
  const address = draft.address
  const engagement = draft.engagement
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto border-0 bg-[var(--md-surface)] text-[var(--md-ink)] shadow-[var(--md-shadow-lift)] sm:max-w-[760px]"><DialogHeader className="text-start"><DialogTitle>{t("Edit account")}</DialogTitle><DialogDescription>{t("Keep the customer record useful for the next operator. Consent changes are recorded with your name and time.")}</DialogDescription></DialogHeader><form className="grid gap-6" onSubmit={onSubmit}>
    <FormSection title={t("Account profile")}><Field label={t("Account name")} required value={draft.name} onChange={(value) => set("name", value)} /><div className="grid gap-4 sm:grid-cols-2"><SelectField label={t("Relationship status")} value={draft.relationshipStatus} options={relationshipStatuses.map((status) => ({ value: status.code, label: status.name }))} onChange={(value) => set("relationshipStatus", value)} /><Field label={t("Tier")} value={draft.tier ?? ""} onChange={(value) => set("tier", value || null)} /><Field label={t("Segment")} value={draft.segment ?? ""} onChange={(value) => set("segment", value || null)} /><Field label={t("Vertical")} value={draft.vertical ?? ""} onChange={(value) => set("vertical", value || null)} /><Field label={t("Primary mode")} value={draft.primaryMode ?? ""} onChange={(value) => set("primaryMode", value || null)} /><Field label={t("Primary trade lane")} value={draft.primaryTradeLane ?? ""} onChange={(value) => set("primaryTradeLane", value || null)} /><Field label={t("Growth state")} value={draft.growthState ?? ""} onChange={(value) => set("growthState", value || null)} /><Field label={t("Account health score")} type="number" value={draft.healthScore == null ? "" : String(draft.healthScore)} onChange={(value) => set("healthScore", value === "" ? null : Math.max(0, Math.min(100, Number(value))))} /><Field label={t("Churn risk score")} type="number" value={draft.churnRiskScore == null ? "" : String(draft.churnRiskScore)} onChange={(value) => set("churnRiskScore", value === "" ? null : Math.max(0, Math.min(100, Number(value))))} /></div><label className="grid gap-1.5 text-[13px] font-medium">{t("Account summary")}<Textarea value={draft.summary ?? ""} onChange={(event) => set("summary", event.target.value || null)} className="min-h-[100px] rounded-[var(--md-radius-md)] bg-white/68 text-[16px] shadow-[var(--md-shadow-line)] sm:text-[14px]" /></label><div className="grid gap-3 sm:grid-cols-2"><CheckRow label={t("Strategic account")} checked={draft.strategic} onChange={(checked) => set("strategic", checked)} /><CheckRow label={t("Allow AI training with approved account data")} checked={draft.trainingAllowed} onChange={(checked) => set("trainingAllowed", checked)} /></div></FormSection>
    <FormSection title={t("Address and contact details")}><div className="grid gap-4 sm:grid-cols-2"><Field label={t("Address line 1")} value={address.line1 ?? ""} onChange={(value) => set("address", { ...address, line1: value || null })} /><Field label={t("Address line 2")} value={address.line2 ?? ""} onChange={(value) => set("address", { ...address, line2: value || null })} /><Field label={t("Town or city")} value={address.townCity ?? ""} onChange={(value) => set("address", { ...address, townCity: value || null })} /><Field label={t("County or state")} value={address.countyState ?? ""} onChange={(value) => set("address", { ...address, countyState: value || null })} /><Field label={t("Postcode")} value={address.postZipCode ?? ""} onChange={(value) => set("address", { ...address, postZipCode: value || null })} /><Field label={t("Country code")} value={address.countryCode ?? ""} onChange={(value) => set("address", { ...address, countryCode: value || null })} /><Field label={t("Main email")} type="email" value={address.mainEmail ?? ""} onChange={(value) => set("address", { ...address, mainEmail: value || null })} /><Field label={t("Main phone")} type="tel" value={address.mainPhone ?? ""} onChange={(value) => set("address", { ...address, mainPhone: value || null })} /></div></FormSection>
    <FormSection title={t("Communication preferences")}><div className="grid gap-4 sm:grid-cols-2"><Field label={t("Preferred channel")} value={engagement.preferredChannel ?? ""} onChange={(value) => set("engagement", { ...engagement, preferredChannel: value || null })} /><Field label={t("Minimum hours between non-urgent messages")} type="number" value={String(engagement.minHoursBetweenNonUrgentMessages)} onChange={(value) => set("engagement", { ...engagement, minHoursBetweenNonUrgentMessages: Number(value) || 0 })} /></div><div className="grid gap-3 sm:grid-cols-2"><CheckRow label={t("Allow follow-up messages")} checked={engagement.allowFollowupMessages} onChange={(checked) => set("engagement", { ...engagement, allowFollowupMessages: checked })} /><CheckRow label={t("Allow thank-you messages")} checked={engagement.allowThankYouMessages} onChange={(checked) => set("engagement", { ...engagement, allowThankYouMessages: checked })} /><CheckRow label={t("Allow WhatsApp")} checked={engagement.allowWhatsApp} onChange={(checked) => set("engagement", { ...engagement, allowWhatsApp: checked })} /><CheckRow label={t("Do not over-contact") } checked={engagement.doNotOverContact} onChange={(checked) => set("engagement", { ...engagement, doNotOverContact: checked })} /></div><label className="grid gap-1.5 text-[13px] font-medium">{t("Communication notes")}<Textarea value={engagement.notes ?? ""} onChange={(event) => set("engagement", { ...engagement, notes: event.target.value || null })} className="min-h-[80px] bg-white/68 text-[16px] shadow-[var(--md-shadow-line)] sm:text-[14px]" /></label></FormSection>
    <FormSection title={t("Marketing consent")}><div className="rounded-[var(--md-radius-lg)] bg-[var(--md-surface-soft)] p-4 shadow-[var(--md-shadow-line)]"><MarketingOptInControl checked={draft.marketingOptIn} onCheckedChange={(checked) => set("marketingOptIn", checked)} /><p className="mt-2 text-[12px] leading-5 text-[var(--md-text)]">{t("Contact-level opt-outs still take priority. Only change this when you can explain the source.")}</p></div><Field label={t("Reason or evidence")} value={draft.marketingConsentReason ?? ""} onChange={(value) => set("marketingConsentReason", value || null)} /></FormSection>
    <FormSection title={t("Additional fields")}><div className="grid gap-2">{draft.customFields.map((field) => <div key={field.id} className="grid gap-2 sm:grid-cols-[minmax(140px,0.8fr)_minmax(180px,1.2fr)_auto]"><Input aria-label={t("Field name")} value={field.label} onChange={(event) => set("customFields", draft.customFields.map((item) => item.id === field.id ? { ...item, label: event.target.value } : item))} placeholder={t("Field name")} className="h-10 bg-white/68 text-[16px] sm:text-[14px]" /><Input aria-label={t("Field value")} value={field.value} onChange={(event) => set("customFields", draft.customFields.map((item) => item.id === field.id ? { ...item, value: event.target.value } : item))} placeholder={t("Value")} className="h-10 bg-white/68 text-[16px] sm:text-[14px]" /><Button type="button" variant="ghost" onClick={() => set("customFields", draft.customFields.filter((item) => item.id !== field.id))}>{t("Remove")}</Button></div>)}</div><Button type="button" variant="outline" className="w-fit" onClick={() => set("customFields", [...draft.customFields, { id: crypto.randomUUID(), label: "", value: "" }])}><Plus className="size-4" />{t("Add field")}</Button></FormSection>
    <DialogFooter><Button type="button" variant="outline" disabled={saving} onClick={() => onOpenChange(false)}>{t("Cancel")}</Button><Button type="submit" disabled={saving || !draft.name.trim() || (draft.marketingOptIn !== originalMarketingOptIn && !draft.marketingConsentReason?.trim())}><AnimatePresence initial={false} mode="wait">{saving ? <motion.span key="saving" initial={{ opacity: 0, scale: 0.25, filter: "blur(4px)" }} animate={{ opacity: 1, scale: 1, filter: "blur(0px)" }} exit={{ opacity: 0, scale: 0.25, filter: "blur(4px)" }} transition={{ type: "spring", duration: 0.3, bounce: 0 }}><LoaderCircle className="size-4 animate-spin" /></motion.span> : <motion.span key="save" initial={{ opacity: 0, scale: 0.25, filter: "blur(4px)" }} animate={{ opacity: 1, scale: 1, filter: "blur(0px)" }} exit={{ opacity: 0, scale: 0.25, filter: "blur(4px)" }} transition={{ type: "spring", duration: 0.3, bounce: 0 }}><Check className="size-4" /></motion.span>}</AnimatePresence>{t(saving ? "Saving…" : "Save account")}</Button></DialogFooter>
  </form></DialogContent></Dialog>
}

function toDraft(account: ApiCustomerDetail): AccountDraft {
  const metadata = account.metadata ?? {}; const fields = metadata.customFields && typeof metadata.customFields === "object" ? metadata.customFields as Record<string, unknown> : {}
  return { name: account.name, relationshipStatus: account.relationshipStatus, tier: account.tier, segment: account.segment, vertical: account.vertical, primaryMode: account.primaryMode, primaryTradeLane: account.primaryTradeLane, growthState: account.growthState, healthScore: account.healthScore, churnRiskScore: account.churnRiskScore, summary: account.summary, strategic: account.strategic, trainingAllowed: account.trainingAllowed, marketingOptIn: account.marketingOptIn, marketingConsentReason: "", metadata, address: account.address ? { line1: account.address.line1, line2: account.address.line2, townCity: account.address.townCity, countyState: account.address.countyState, postZipCode: account.address.postZipCode, countryCode: account.address.countryCode, mainEmail: account.address.mainEmail, mainPhone: account.address.mainPhone } : { line1: null, line2: null, townCity: null, countyState: null, postZipCode: null, countryCode: null, mainEmail: null, mainPhone: null }, engagement: account.engagement ?? { preferredChannel: null, allowThankYouMessages: true, allowFollowupMessages: true, allowWhatsApp: false, doNotOverContact: false, minHoursBetweenNonUrgentMessages: 24, notes: null }, customFields: Object.entries(fields).map(([label, value]) => ({ id: crypto.randomUUID(), label, value: typeof value === "string" ? value : String(value) })) }
}

function Panel({ title, meta, action, children }: { title: string; meta?: string; action?: ReactNode; children: ReactNode }) { return <Surface padding="none" className="overflow-hidden rounded-[var(--md-radius-xl)]"><div className="flex items-center justify-between gap-3 px-5 py-4"><h2 className="text-[15px] font-medium text-[var(--md-ink)]">{title}</h2>{meta || action ? <div className="flex items-center gap-2">{meta ? <span className="text-[12px] text-[var(--md-text)]">{meta}</span> : null}{action}</div> : null}</div>{children}</Surface> }
function Metric({ icon: Icon, label, value, tone = "neutral" }: { icon: typeof Users; label: string; value: string; tone?: "neutral" | "amber" }) { return <Surface padding="none" className="rounded-[var(--md-radius-xl)]"><div className="flex min-h-14 items-center gap-3 px-4 py-2.5"><span className={`grid size-7 shrink-0 place-items-center rounded-[var(--md-radius-md)] bg-[var(--md-surface-tint)] ${tone === "amber" ? "text-[var(--md-amber)]" : "text-[var(--md-accent)]"}`}><Icon className="size-3.5" strokeWidth={1.4} /></span><p className="min-w-0 flex-1 truncate text-[12px] text-[var(--md-text)]">{label}</p><p className="shrink-0 text-[18px] font-medium tabular-nums text-[var(--md-ink)]">{value}</p></div></Surface> }
function ActivityRow({ activity, last }: { activity: ApiCustomerDetail["activities"][number]; last: boolean }) { const { t } = useLanguage(); return <div className={`grid grid-cols-[10px_minmax(0,1fr)_auto] gap-3 px-5 py-4 ${last ? "" : "border-b border-[var(--md-line)]"}`}><span className="mt-1.5 size-2 rounded-full bg-[var(--md-accent)] shadow-[0_0_0_4px_var(--md-accent-a08)]" /><div><p className="text-[14px] font-medium text-[var(--md-ink)]">{activity.subject}</p>{activity.summary ? <p className="mt-1 text-[13px] leading-5 text-[var(--md-text)]">{activity.summary}</p> : null}</div><p className="shrink-0 text-[12px] tabular-nums text-[var(--md-subtle)]">{relativeDate(activity.occurredAt, t)}</p></div> }
function DetailList({ rows }: { rows: [string, string | null | undefined][] }) { const { t } = useLanguage(); const visible = rows.filter(([, value]) => value); return visible.length ? <dl className="px-5 pb-4">{visible.map(([label, value]) => <div key={label} className="grid grid-cols-[minmax(100px,0.8fr)_minmax(0,1.2fr)] gap-4 border-t border-[var(--md-line)] py-3 first:border-t-0"><dt className="text-[12px] text-[var(--md-text)]">{label}</dt><dd className="text-end text-[13px] font-medium text-[var(--md-ink)]" dir="auto">{value}</dd></div>)}</dl> : <Empty text={t("No details recorded.")} /> }
function Empty({ text }: { text: string }) { return <p className="border-t border-[var(--md-line)] px-5 py-6 text-[13px] leading-5 text-[var(--md-text)]">{text}</p> }
function PageState({ icon, title, detail, action, embedded = false }: { icon: ReactNode; title: string; detail?: string; action?: ReactNode; embedded?: boolean }) { return <div className={embedded ? "" : "md-page"}><Surface padding="lg" className="grid min-h-[320px] place-items-center rounded-[var(--md-radius-xl)] text-center"><div className="max-w-md"><span className="mx-auto grid size-11 place-items-center rounded-[var(--md-radius-lg)] bg-[var(--md-surface-tint)] text-[var(--md-accent)]">{icon}</span><p className="mt-4 text-[15px] font-medium text-[var(--md-ink)]">{title}</p>{detail ? <p className="mt-2 text-[13px] leading-5 text-[var(--md-text)]">{detail}</p> : null}{action ? <div className="mt-4">{action}</div> : null}</div></Surface></div> }
function FormSection({ title, children }: { title: string; children: ReactNode }) { return <section className="grid gap-4"><div className="border-b border-[var(--md-line)] pb-2"><h3 className="text-[14px] font-medium text-[var(--md-ink)]">{title}</h3></div>{children}</section> }
function Field({ label, value, onChange, required, type = "text" }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; type?: string }) { return <label className="grid gap-1.5 text-[13px] font-medium text-[var(--md-ink)]"><span>{label}{required ? " *" : ""}</span><Input dir={["email","tel","number"].includes(type) ? "ltr" : "auto"} type={type} required={required} value={value} onChange={(event) => onChange(event.target.value)} className="h-10 rounded-[var(--md-radius-md)] bg-white/68 text-[16px] shadow-[var(--md-shadow-line)] sm:text-[14px]" /></label> }
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: { value: string; label: string }[]; onChange: (value: string) => void }) { const visibleOptions = options.some((option) => option.value === value) ? options : [{ value, label: humanize(value) ?? value }, ...options]; return <label className="grid gap-1.5 text-[13px] font-medium text-[var(--md-ink)]"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="h-10 rounded-[var(--md-radius-md)] bg-white/68 px-3 text-[16px] shadow-[var(--md-shadow-line)] outline-none focus-visible:ring-[3px] focus-visible:ring-[var(--md-accent-a14)] sm:text-[14px]">{visibleOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label> }
function CheckRow({ label, checked, onChange, detail }: { label: string; checked: boolean; onChange: (checked: boolean) => void; detail?: string }) { return <label className="flex min-h-11 items-start gap-3 rounded-[var(--md-radius-lg)] bg-[var(--md-surface-soft)] p-3 shadow-[var(--md-shadow-line)]"><Checkbox checked={checked} onCheckedChange={(value) => onChange(value === true)} className="mt-0.5" /><span><span className="block text-[13px] font-medium text-[var(--md-ink)]">{label}</span>{detail ? <span className="mt-1 block text-[12px] leading-5 text-[var(--md-text)]">{detail}</span> : null}</span></label> }
function humanize(value: string | null | undefined) { return value ? value.replace(/[_-]+/g, " ").replace(/^./, (letter) => letter.toUpperCase()) : null }
function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)) }
function relativeDate(value: string, t: (value: string) => string) { const days = Math.floor((Date.now() - new Date(value).getTime()) / 86_400_000); if (days <= 0) return t("Today"); if (days === 1) return t("Yesterday"); if (days < 30) return `${days} ${t("days ago")}`; return formatDate(value) }
