import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { GB_PROCESSING_BASIS_SOURCE, type GbProcessingBasisReview } from "../../../supabase/functions/_shared/customs-gb-processing-basis.mts"
import type { CalculationResult } from "../../../supabase/functions/_shared/customs-duty-calculation.mts"

export function GbProcessingBasisEditor({ value, onChange, saved, stale, t }: { value?: GbProcessingBasisReview; onChange: (value: GbProcessingBasisReview | undefined) => void; saved?: NonNullable<CalculationResult["gbProcessingBasisReviews"]>[number]; stale: boolean; t: (value: string) => string }) {
  const initial: GbProcessingBasisReview = { date: "", jurisdiction: "GB", entryPolicy: {}, authorisationPolicy: {}, calendarYearClassificationValueGbp: "", evidence: "" }
  const control = "mt-1 min-h-8 w-full min-w-0 rounded-[var(--md-radius-md)] bg-[var(--md-input-bg)] px-2 text-[12px] text-[var(--md-ink)] premium-stroke-soft focus-visible:outline-2 focus-visible:outline-[var(--md-accent)]"
  const grid = "grid min-w-0 grid-cols-[repeat(auto-fit,minmax(min(100%,14rem),1fr))] gap-3"
  const choice = (label: string, answer: boolean | undefined, change: (answer: boolean | undefined) => void) => <label key={label} className="min-w-0">{t(label)}<select className={control} value={answer === true ? "yes" : answer === false ? "no" : ""} onChange={event => change(event.target.value === "" ? undefined : event.target.value === "yes")}><option value="">{t("Not reviewed")}</option><option value="yes">{t("Yes")}</option><option value="no">{t("No")}</option></select></label>
  return <details className="min-w-0 space-y-3">
    <summary className="cursor-pointer rounded-[var(--md-radius-sm)] font-medium text-[var(--md-ink)] focus-visible:outline-2 focus-visible:outline-[var(--md-accent)]">{t("Great Britain — processing calculation basis")}</summary>
    <p>{t("Review the authorisation and original goods before choosing a valuation basis. This records whether original-goods treatment is required; it does not calculate tax or approve another basis.")}</p>
    {!value ? <Button type="button" size="sm" variant="outline" onClick={() => onChange(initial)}>{t("Add GB basis review")}</Button> : <>
      <div className={grid}>
        <label>{t("Review date")}<Input className={control} type="date" value={value.date} onChange={event => onChange({ ...value, date: event.target.value })} /></label>
        <label>{t("Calendar-year total for this applicant and classification (GBP)")}<Input className={control} inputMode="decimal" value={value.calendarYearClassificationValueGbp} onChange={event => onChange({ ...value, calendarYearClassificationValueGbp: event.target.value })} /></label>
        {([["originalBasisElected", "Original-goods basis elected"], ["regulation22Breach", "Regulation 22(3)(c) breach"], ["holderReimportWithinOneYear", "Holder reimported products within one year of export or removal to NI"], ["economicExaminationRequired", "Economic-condition examination required for the application"], ["paragraph6Exception", "A regulation 23(6) exception applies"], ["sensitiveGoods", "Goods are classified as sensitive for the annual threshold"]] as const).map(([key, label]) => choice(label, value[key], answer => onChange({ ...value, [key]: answer })))}
      </div>
      {(["entryPolicy", "authorisationPolicy"] as const).map(stage => <fieldset key={stage} className="space-y-2"><legend className="font-medium">{t(stage === "entryPolicy" ? "Policy position when released to inward processing" : "Policy position when authorisation was granted")}</legend><div className={grid}>{([["exceptedGoods", "Excepted goods"], ["additionalDuty", "Additional duty under sections 13, 14 or 15"], ["nonTariffOrAgriculturalMeasure", "Non-tariff trade or agricultural policy measure"], ["guaranteeRequired", "Schedule 4 paragraph 15(5) guarantee required"]] as const).map(([key, label]) => choice(label, value[stage]?.[key], answer => onChange({ ...value, [stage]: { ...value[stage], [key]: answer } })))}</div></fieldset>)}
      <p>{t("Use the full calendar-year classification total, not this invoice alone. Explain any regulation 23(6) exception and identify the evidence for both policy dates below.")}</p>
      <label className="block">{t("Authorisation, policy checks and exception evidence")}<textarea className={`${control} min-h-24 py-2`} value={value.evidence} onChange={event => onChange({ ...value, evidence: event.target.value })} /></label>
      <fieldset className="min-w-0 space-y-3 pt-3"><legend className="font-medium">{t("Processed-products release")}</legend>
        <p>{t("Complete this only when the reviewed rules and authorisation permit the processed-products basis. Duty and VAT use the released products’ value and current rates. The basis checks above must also be complete.")}</p>
        {!value.processedRelease ? <Button type="button" size="sm" variant="outline" onClick={() => onChange({ ...value, processedRelease: { entryDate: "", entryReference: "", authorisationEvidence: "", dischargeEvidence: "", valuationEvidence: "", noPriorTaxPaymentConfirmed: false, noEquivalenceOrCombinedReliefConfirmed: false } })}>{t("Add processed-products release")}</Button> : <>
          <div className={grid}>{([["entryDate", "Original entry date"], ["entryReference", "Original entry reference"], ["authorisationEvidence", "Authorisation and permitted product basis"], ["dischargeEvidence", "Product identity, quantity, yield and discharge evidence"], ["valuationEvidence", "Processed-product customs and VAT valuation evidence"]] as const).map(([key, label]) => <label key={key} className="min-w-0">{t(label)}{key === "entryDate" ? <Input type="date" className={control} value={value.processedRelease![key]} onChange={event => onChange({ ...value, processedRelease: { ...value.processedRelease!, [key]: event.target.value } })} /> : <textarea className={`${control} min-h-20 py-2`} value={value.processedRelease![key]} onChange={event => onChange({ ...value, processedRelease: { ...value.processedRelease!, [key]: event.target.value } })} />}</label>)}</div>
          {([["noPriorTaxPaymentConfirmed", "No duty or VAT was previously paid for these goods"], ["noEquivalenceOrCombinedReliefConfirmed", "No equivalence or combined relief changes this release"]] as const).map(([key, label]) => <label key={key} className="flex items-start gap-2"><input type="checkbox" className="mt-1 size-4 shrink-0 accent-[var(--md-accent)]" checked={value.processedRelease![key] === true} onChange={event => onChange({ ...value, processedRelease: { ...value.processedRelease!, [key]: event.target.checked } })} /><span>{t(label)}</span></label>)}
          <Button type="button" size="sm" variant="ghost" onClick={() => onChange({ ...value, processedRelease: undefined })}>{t("Remove processed-products release")}</Button>
        </>}
      </fieldset>
      <p>{t("Save, then recalculate to retain the decision. Unanswered questions stay unreviewed.")}</p>
      <Button type="button" size="sm" variant="ghost" onClick={() => onChange(undefined)}>{t("Remove GB basis review")}</Button>
    </>}
    {saved ? <div className="space-y-2" role="status"><p className="font-medium">{t(stale ? "Previous basis review — recalculate after saving" : "Saved basis review")}</p>{[...saved.issues, ...(saved.result?.issues ?? [])].map(issue => <p key={issue}>{t(issue)}</p>)}{saved.result?.basis ? <><p>{t(saved.result.basis === "original-goods-required" ? "Original-goods basis required by the reviewed facts." : "No original-goods trigger established. This does not approve the processed-products basis.")}</p>{"reasons" in saved.result ? saved.result.reasons.map(reason => <p key={reason}>{t(reason)}</p>) : null}</> : null}</div> : null}
    <a href={GB_PROCESSING_BASIS_SOURCE} target="_blank" rel="noreferrer" className="text-[var(--md-accent)] underline">{t("Read regulation 23 and its exceptions")}</a>
  </details>
}
