import { useCallback, useEffect, useMemo, useState } from "react"
import { BadgeCheck, ChartLine, CreditCard, FileText, LoaderCircle, ReceiptText, RefreshCw } from "@/components/icons/hugeicons"
import { InlineNotice } from "@/components/multideck/inline-notice"
import { SettingsPageHeader, SettingsPanel } from "@/components/multideck/settings-components"
import { StatusPill } from "@/components/multideck/status-pill"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { useLanguage } from "@/i18n/language-provider"
import { hasPermission, type AuthUserSummary } from "@/lib/auth-user"
import { getFinanceDocuments, getFinanceDraftOptions, type FinanceDocument, type FinanceDraftOptions } from "@/lib/finance-subledger-api"
import {
  approveSupplierInvoiceMatch, approveSupplierPurchaseOrder, createSupplierPurchaseOrder, getAgedFinanceWorklist,
  generateFinanceMatchProposal, getCollectionActions, getCustomerStatement, getFinanceMatchProposals, getFinanceOperationEntities, getFinancePaymentBanks, getJobProfitability,
  getPaymentRuns, getRemittanceAdvice, getSupplierInvoiceMatchSuggestions, getSupplierPurchaseOrders,
  preparePaymentRun, recordCollectionAction, rejectFinanceMatchProposal, reviewPaymentRun,
  type AgedFinanceItem, type CollectionAction, type CustomerStatement, type FinanceOperationEntity,
  type FinanceMatchProposal, type FinanceWorklist, type JobProfitability, type MatchSuggestions, type PaymentRun, type RemittanceAdvice, type SupplierPurchaseOrder,
} from "@/lib/finance-operations-api"
import { toast } from "sonner"

export type FinanceDailyRoute = "/finance/receivables/statements" | "/finance/receivables/collections" | "/finance/payables/payment-runs" | "/finance/payables/purchase-orders" | "/finance/payables/matching" | "/finance/management/profitability"

const today = () => new Date().toISOString().slice(0, 10)
const numeric = (value: unknown) => Number(value ?? 0)
const tone = (status: string): "teal" | "amber" | "red" | "neutral" => status === "approved" || status === "posted" || status === "routine" ? "teal" : status === "urgent" || status === "rejected" ? "red" : status === "draft" ? "neutral" : "amber"
const errorText = (error: unknown) => error instanceof Error && /failed to fetch|networkerror/i.test(error.message) ? "Finance operations could not be reached. Check the tenant service and try again." : error instanceof Error ? error.message : "The Finance workspace could not be loaded."

export function FinanceDailyPage({ route, navigate, currentUser }: { route: FinanceDailyRoute; navigate: (path: string) => void; currentUser?: AuthUserSummary | null }) {
  const { t, language } = useLanguage()
  const [entities, setEntities] = useState<FinanceOperationEntity[]>([])
  const [entityId, setEntityId] = useState("")
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [version, setVersion] = useState(0)
  const activeEntity = entities.find((value) => value.LegalEntity_ID === entityId)
  const currency = activeEntity?.LegalEntity_BaseCurrencyCodeSnapshot || "GBP"
  const format = useCallback((value: number, code = currency) => {
    try { return new Intl.NumberFormat(language, { style: "currency", currency: code, maximumFractionDigits: 2 }).format(numeric(value)) }
    catch { return `${code} ${numeric(value).toFixed(2)}` }
  }, [language, currency])

  useEffect(() => {
    let active = true
    setLoading(true); setError("")
    getFinanceOperationEntities().then(({ entities: found }) => {
      if (!active) return
      setEntities(found); setEntityId((current) => found.some((item) => item.LegalEntity_ID === current) ? current : found[0]?.LegalEntity_ID || "")
    }).catch((cause) => { if (active) setError(errorText(cause)) }).finally(() => { if (active) setLoading(false) })
    return () => { active = false }
  }, [version])

  const refresh = () => setVersion((value) => value + 1)
  const labels: Record<FinanceDailyRoute, { title: string; description: string; icon: typeof FileText }> = {
    "/finance/receivables/statements": { title: "Customer statements", description: "Prepare a source-backed open-item statement for a customer and review it before printing or sharing.", icon: FileText },
    "/finance/receivables/collections": { title: "Collections worklist", description: "Prioritise overdue customer invoices from recorded due dates and balances, then record each follow-up.", icon: CreditCard },
    "/finance/payables/payment-runs": { title: "Payment runs & remittances", description: "Group approved supplier invoices into a reviewed run, then prepare remittance advice from approved allocations.", icon: CreditCard },
    "/finance/payables/purchase-orders": { title: "Supplier purchase orders", description: "Record and approve supplier commitments separately from customer warehouse purchase orders.", icon: ReceiptText },
    "/finance/payables/matching": { title: "Invoice matching", description: "Compare supplier invoices with approved POs. Suggestions cite both records and require Finance approval.", icon: BadgeCheck },
    "/finance/management/profitability": { title: "Job profitability", description: "Review expected, actual and open WIP or accrual amounts from the canonical job charge calculation.", icon: ChartLine },
  }
  const selected = labels[route]
  return <>
    <SettingsPageHeader title={t(selected.title)} description={t(selected.description)} icon={selected.icon} actions={<Button type="button" variant="outline" onClick={refresh}><RefreshCw className="size-4" />{t("Refresh")}</Button>} />
    <div className="mt-[var(--md-page-stack-gap)] space-y-[var(--md-page-stack-gap)]">
      {error ? <InlineNotice tone="error">{t(error)}</InlineNotice> : null}
      <SettingsPanel title={t("Company") } description={t("Finance records remain scoped to the selected legal entity.")}>
        <div className="max-w-sm px-5 py-4"><label htmlFor="finance-daily-entity" className="mb-2 block text-xs font-medium">{t("Legal entity")}</label><Select value={entityId} onValueChange={setEntityId}><SelectTrigger id="finance-daily-entity"><SelectValue placeholder={t("Choose legal entity")} /></SelectTrigger><SelectContent>{entities.map((item) => <SelectItem key={item.LegalEntity_ID} value={item.LegalEntity_ID}>{item.LegalEntity_Name}</SelectItem>)}</SelectContent></Select></div>
      </SettingsPanel>
      {loading ? <div className="grid min-h-52 place-items-center"><LoaderCircle className="size-5 animate-spin" /><span className="sr-only">{t("Loading Finance")}</span></div> : !entityId ? error ? null : <InlineNotice>{t("Set up a legal entity before using these Finance workflows.")}</InlineNotice> : <>
        {route === "/finance/receivables/statements" && <StatementsWorkspace entityId={entityId} format={format} navigate={navigate} version={version} />}
        {route === "/finance/receivables/collections" && <CollectionsWorkspace entityId={entityId} format={format} navigate={navigate} currentUser={currentUser} version={version} />}
        {route === "/finance/payables/payment-runs" && <PaymentRunsWorkspace entityId={entityId} currency={currency} format={format} navigate={navigate} currentUser={currentUser} version={version} />}
        {route === "/finance/payables/purchase-orders" && <PurchaseOrdersWorkspace entityId={entityId} currency={currency} format={format} currentUser={currentUser} version={version} />}
        {route === "/finance/payables/matching" && <MatchingWorkspace entityId={entityId} format={format} navigate={navigate} currentUser={currentUser} version={version} />}
        {route === "/finance/management/profitability" && <ProfitabilityWorkspace entityId={entityId} format={format} navigate={navigate} version={version} />}
      </>}
    </div>
  </>
}

function AgedTable({ items, format, navigate, selected, onSelect }: { items: AgedFinanceItem[]; format: (value: number, code?: string) => string; navigate: (path: string) => void; selected?: Set<string>; onSelect?: (item: AgedFinanceItem) => void }) {
  const { t } = useLanguage()
  return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-[var(--md-line)] text-xs text-[var(--md-subtle)]"><th scope="col" className="px-5 py-3 text-start font-medium">{t("Invoice")}</th><th scope="col" className="px-5 py-3 text-start font-medium">{t("Customer / supplier")}</th><th scope="col" className="px-5 py-3 text-start font-medium">{t("Due")}</th><th scope="col" className="px-5 py-3 text-start font-medium">{t("Age")}</th><th scope="col" className="px-5 py-3 text-end font-medium">{t("Outstanding")}</th><th scope="col" className="px-5 py-3 text-end font-medium">{t("Action")}</th></tr></thead><tbody className="divide-y divide-[var(--md-line)]">{items.map((item) => <tr key={item.id}>
    <td className="px-5 py-3"><button type="button" className="font-medium text-[var(--md-accent)] underline-offset-2 hover:underline focus-visible:outline-2 focus-visible:outline-[var(--md-accent)]" onClick={() => navigate(`/finance/${item.ledger}/documents/${item.id}`)} data-i18n-skip>{item.number}</button><span className="mt-1 block text-[11px] text-[var(--md-subtle)]" data-i18n-skip>FIN_Documents · {item.id.slice(0, 8)}</span></td>
    <td className="px-5 py-3">{item.partyName}</td><td className="px-5 py-3" data-i18n-skip>{item.dueDate ?? "—"}</td><td className="px-5 py-3"><StatusPill tone={tone(item.priority)}>{item.bucket}</StatusPill><span className="ms-2 text-xs text-[var(--md-subtle)]">{item.daysOverdue ? `${item.daysOverdue}d` : t("Current")}</span></td><td className="px-5 py-3 text-end tabular-nums" data-i18n-skip>{format(item.outstanding, item.currency)}</td><td className="px-5 py-3 text-end">{onSelect && <Button type="button" variant="outline" size="sm" onClick={() => onSelect(item)}>{selected ? selected.has(item.id) ? t("Selected") : t("Select") : t("Follow up")}</Button>}</td>
  </tr>)}{!items.length && <tr><td colSpan={6} className="px-5 py-10 text-center text-[var(--md-subtle)]">{t("No open invoices in this worklist.")}</td></tr>}</tbody></table></div>
}

function useWorklist(entityId: string, ledger: "receivables" | "payables", version: number) {
  const [data, setData] = useState<FinanceWorklist | null>(null)
  const [error, setError] = useState("")
  const [loading, setLoading] = useState(true)
  useEffect(() => { let active = true; setLoading(true); setError(""); setData(null)
    getAgedFinanceWorklist(entityId, ledger).then((value) => { if (active) setData(value) }).catch((cause) => { if (active) setError(errorText(cause)) }).finally(() => { if (active) setLoading(false) })
    return () => { active = false }
  }, [entityId, ledger, version])
  return { data, error, loading }
}

function StatementsWorkspace({ entityId, format, navigate, version }: { entityId: string; format: (value: number, code?: string) => string; navigate: (path: string) => void; version: number }) {
  const { t } = useLanguage()
  const { data, error, loading } = useWorklist(entityId, "receivables", version)
  const customers = useMemo(() => [...new Map([...(data?.items ?? []), ...(data?.offsets ?? [])].map((item) => [item.partyId, item.partyName])).entries()].sort((a, b) => a[1].localeCompare(b[1])), [data])
  const [customerId, setCustomerId] = useState("")
  const [statement, setStatement] = useState<CustomerStatement | null>(null)
  const [busy, setBusy] = useState(false)
  useEffect(() => { setCustomerId(""); setStatement(null) }, [entityId])
  const prepare = async () => { if (!customerId) return; setBusy(true); try { setStatement(await getCustomerStatement(entityId, customerId)) } catch (cause) { toast.error(t(errorText(cause))) } finally { setBusy(false) } }
  return <>
    {error && <InlineNotice tone="error">{t(error)}</InlineNotice>}
    <SettingsPanel title={t("Open-item statement")} description={t("Balances are current at generation time. Review invoices, credits and unapplied receipts before sharing; this page does not send a statement.")}>
      <div className="flex flex-wrap items-end gap-3 px-5 py-4"><div className="w-full max-w-sm"><label htmlFor="statement-customer" className="mb-2 block text-xs font-medium">{t("Customer")}</label><Select value={customerId} onValueChange={(value) => { setCustomerId(value); setStatement(null) }}><SelectTrigger id="statement-customer"><SelectValue placeholder={t("Choose customer")} /></SelectTrigger><SelectContent>{customers.map(([id, name]) => <SelectItem key={id} value={id}>{name}</SelectItem>)}</SelectContent></Select></div><Button type="button" disabled={!customerId || busy} onClick={() => void prepare()}>{busy ? <LoaderCircle className="size-4 animate-spin" /> : <FileText className="size-4" />}{t("Prepare statement")}</Button>{statement && <Button type="button" variant="outline" onClick={() => window.print()}>{t("Print reviewed statement")}</Button>}</div>
      {loading ? <p className="px-5 pb-5 text-sm text-[var(--md-subtle)]">{t("Loading customer balances…")}</p> : !customers.length ? <p className="px-5 pb-5 text-sm text-[var(--md-subtle)]">{t("No customers have an open balance.")}</p> : null}
    </SettingsPanel>
    {statement && <section className="finance-print-sheet"><SettingsPanel title={`${statement.customerName} · ${t(statement.title)}`} description={`${statement.legalEntity} · ${statement.generatedAt.slice(0, 16).replace("T", " ")} UTC`}>
      <p className="px-5 py-3 text-xs text-[var(--md-subtle)]">{t(statement.basis)}</p>
      <div className="overflow-x-auto"><table className="w-full min-w-[600px] text-sm"><thead><tr className="border-b border-[var(--md-line)] text-xs"><th className="px-5 py-3 text-start">{t("Document")}</th><th className="px-5 py-3 text-start">{t("Date / due")}</th><th className="px-5 py-3 text-end">{t("Original")}</th><th className="px-5 py-3 text-end">{t("Outstanding")}</th></tr></thead><tbody className="divide-y divide-[var(--md-line)]">{statement.lines.map((line) => <tr key={line.id}><td className="px-5 py-3"><button type="button" className="text-[var(--md-accent)] hover:underline" onClick={() => navigate(line.type === "customer_receipt" ? "/finance/receivables/cash" : `/finance/receivables/documents/${line.id}`)} data-i18n-skip>{line.number ?? "Unnumbered"}</button><span className="ms-2 text-xs text-[var(--md-subtle)]">{t(line.type === "credit_note" ? "Credit" : line.type === "customer_receipt" ? "Unapplied receipt" : "Invoice")}</span></td><td className="px-5 py-3" data-i18n-skip>{line.documentDate} · {line.dueDate ?? "—"}</td><td className="px-5 py-3 text-end tabular-nums" data-i18n-skip>{format(line.originalAmount, line.currency)}</td><td className="px-5 py-3 text-end tabular-nums" data-i18n-skip>{format(line.outstanding, line.currency)}</td></tr>)}</tbody></table></div>
      <div className="flex flex-wrap justify-end gap-5 border-t border-[var(--md-line)] px-5 py-4 text-sm font-medium">{Object.entries(statement.totals).map(([code, amount]) => <span key={code} data-i18n-skip>{code} {format(amount, code)}</span>)}</div>
    </SettingsPanel></section>}
    <style>{`@media print { body:has(.finance-print-sheet) * { visibility: hidden !important; } body:has(.finance-print-sheet) .finance-print-sheet, body:has(.finance-print-sheet) .finance-print-sheet * { visibility: visible !important; } body:has(.finance-print-sheet) .finance-print-sheet { position: absolute; inset: 0; width: 100%; } }`}</style>
  </>
}

function CollectionsWorkspace({ entityId, format, navigate, currentUser, version }: { entityId: string; format: (value: number, code?: string) => string; navigate: (path: string) => void; currentUser?: AuthUserSummary | null; version: number }) {
  const { t } = useLanguage()
  const { data, error, loading } = useWorklist(entityId, "receivables", version)
  const [actions, setActions] = useState<CollectionAction[]>([])
  const [selected, setSelected] = useState<AgedFinanceItem | null>(null)
  const [actionCode, setActionCode] = useState("call_note")
  const [note, setNote] = useState("")
  const [followUpDate, setFollowUpDate] = useState("")
  const [busy, setBusy] = useState(false)
  const [actionError, setActionError] = useState("")
  const canRecord = hasPermission(currentUser, "Finance.Receivables.Draft")
  useEffect(() => { let active = true; setSelected(null); getCollectionActions(entityId).then((value) => { if (active) setActions(value) }).catch((cause) => { if (active) setActionError(errorText(cause)) }); return () => { active = false } }, [entityId, version])
  const save = async () => { if (!selected || !note.trim()) return; setBusy(true); setActionError(""); try { await recordCollectionAction({ documentId: selected.id, actionCode, note, followUpDate: followUpDate || null }); setActions(await getCollectionActions(entityId)); setSelected(null); setNote(""); setFollowUpDate(""); toast.success(t("Collection action recorded")) } catch (cause) { setActionError(errorText(cause)) } finally { setBusy(false) } }
  return <>
    {error && <InlineNotice tone="error">{t(error)}</InlineNotice>}{actionError && <InlineNotice tone="error">{t(actionError)}</InlineNotice>}
    <SettingsPanel title={t("Aged debtors")} description={t("Priority uses only days overdue and the recorded open balance. Review disputes, promises and customer context before contacting anyone.")}>
      <p className="px-5 pt-4 text-xs text-[var(--md-subtle)]">{data ? `${t("Live balance as at")} ${data.asOf} · ${data.items.length} ${t("open invoices")}` : loading ? t("Loading balances…") : ""}</p>
      <AgedTable items={data?.items ?? []} format={format} navigate={navigate} onSelect={canRecord ? setSelected : undefined} />
    </SettingsPanel>
    {data && <SettingsPanel title={t("Unapplied customer offsets")} description={t(data.basis)}><div className="divide-y divide-[var(--md-line)]">{data.offsets.map((item) => <div key={`${item.kind}-${item.id}`} className="flex flex-wrap items-center justify-between gap-3 px-5 py-3 text-sm"><div><span className="font-medium">{item.partyName}</span><span className="ms-2 text-[var(--md-subtle)]" data-i18n-skip>{item.number} · {item.evidence.sourceTable}/{item.id.slice(0, 8)}</span></div><span className="tabular-nums" data-i18n-skip>{format(item.amount, item.currency)}</span></div>)}{!data.offsets.length && <p className="px-5 py-4 text-sm text-[var(--md-subtle)]">{t("No unapplied credits or receipts.")}</p>}</div><div className="flex flex-wrap justify-end gap-4 border-t border-[var(--md-line)] px-5 py-3 text-sm font-medium">{Object.entries(data.totals).map(([code, amount]) => <span key={code} data-i18n-skip>{code} gross {format(amount.grossInvoices, code)} · offsets {format(amount.unappliedOffsets, code)} · net {format(amount.net, code)}</span>)}</div></SettingsPanel>}
    {selected && canRecord && <SettingsPanel title={`${t("Record follow-up")} · ${selected.partyName}`} description={`${selected.number} · ${selected.priorityReasons.join(" · ")}`}>
      <div className="grid gap-3 px-5 py-4 md:grid-cols-2"><div><label htmlFor="collection-kind" className="mb-2 block text-xs font-medium">{t("Action")}</label><Select value={actionCode} onValueChange={setActionCode}><SelectTrigger id="collection-kind"><SelectValue /></SelectTrigger><SelectContent>{[["call_note","Call note"],["promise_to_pay","Promise to pay"],["query","Customer query"],["hold","On hold"],["resolved","Resolved"]].map(([code, label]) => <SelectItem key={code} value={code}>{t(label)}</SelectItem>)}</SelectContent></Select></div><div><label htmlFor="collection-followup" className="mb-2 block text-xs font-medium">{t("Follow-up date")}</label><Input id="collection-followup" type="date" value={followUpDate} onChange={(event) => setFollowUpDate(event.target.value)} /></div><div className="md:col-span-2"><label htmlFor="collection-note" className="mb-2 block text-xs font-medium">{t("Evidence and next step")}</label><Textarea id="collection-note" value={note} onChange={(event) => setNote(event.target.value)} maxLength={2000} placeholder={t("Record what happened and what should happen next.")} /></div><div className="flex gap-2 md:col-span-2"><Button type="button" disabled={!note.trim() || busy} onClick={() => void save()}>{busy ? <LoaderCircle className="size-4 animate-spin" /> : <BadgeCheck className="size-4" />}{t("Record action")}</Button><Button type="button" variant="outline" onClick={() => setSelected(null)}>{t("Cancel")}</Button></div></div>
    </SettingsPanel>}
    <SettingsPanel title={t("Recent collection activity")} description={t("Recorded actions are audit evidence; no customer message is sent from this page.")}><div className="divide-y divide-[var(--md-line)]">{actions.slice(0, 30).map((action) => <div key={action.FINCollect_ID} className="flex flex-wrap items-center justify-between gap-2 px-5 py-3 text-sm"><div><span className="font-medium">{t(action.FINCollect_ActionCode.replaceAll("_", " "))}</span><span className="ms-2 text-[var(--md-subtle)]" data-i18n-skip>{action.FINCollect_CreatedAt.slice(0, 16).replace("T", " ")}</span><p className="mt-1 text-[var(--md-text)]">{action.FINCollect_Note}</p></div>{action.FINCollect_FollowUpDate && <span className="text-xs text-[var(--md-subtle)]">{t("Follow up")} <span data-i18n-skip>{action.FINCollect_FollowUpDate}</span></span>}</div>)}{!actions.length && <p className="px-5 py-8 text-center text-sm text-[var(--md-subtle)]">{t("No collection actions recorded yet.")}</p>}</div></SettingsPanel>
  </>
}

function PaymentRunsWorkspace({ entityId, currency, format, navigate, currentUser, version }: { entityId: string; currency: string; format: (value: number, code?: string) => string; navigate: (path: string) => void; currentUser?: AuthUserSummary | null; version: number }) {
  const { t } = useLanguage()
  const { data, error, loading } = useWorklist(entityId, "payables", version)
  const [bankAccounts, setBankAccounts] = useState<FinanceDraftOptions["bankAccounts"]>([])
  const [runs, setRuns] = useState<PaymentRun[]>([])
  const [selected, setSelected] = useState<Set<string>>(new Set())
  const [bankId, setBankId] = useState("")
  const [paymentDate, setPaymentDate] = useState(today())
  const [exchangeRate, setExchangeRate] = useState("1")
  const [reason, setReason] = useState("")
  const [reviewReason, setReviewReason] = useState("")
  const [busy, setBusy] = useState(false)
  const [localError, setLocalError] = useState("")
  const [advice, setAdvice] = useState<RemittanceAdvice | null>(null)
  const canPrepare = hasPermission(currentUser, "Finance.Payables.Cash")
  const canReview = hasPermission(currentUser, "Finance.ReviewAndPost")
  useEffect(() => { let active = true; setSelected(new Set()); setBankId(""); setAdvice(null); setLocalError("")
    Promise.all([getPaymentRuns(entityId), canPrepare ? getFinancePaymentBanks(entityId) : Promise.resolve(null)]).then(([loadedRuns, loadedBanks]) => { if (active) { setRuns(loadedRuns); setBankAccounts(loadedBanks?.bankAccounts ?? []) } }).catch((cause) => { if (active) setLocalError(errorText(cause)) })
    return () => { active = false }
  }, [entityId, version, canPrepare])
  const chosen = (data?.items ?? []).filter((item) => selected.has(item.id))
  const chosenCurrencies = [...new Set(chosen.map((item) => item.currency))]
  const chosenCurrency = chosenCurrencies[0] ?? currency
  const banks = bankAccounts.filter((bank) => bank.FINBank_LegalEntityID === entityId && bank.FINBank_CurrencyCode === chosenCurrency)
  const total = chosen.reduce((sum, item) => sum + item.outstanding, 0)
  const toggle = (item: AgedFinanceItem) => {
    if (data?.offsets.some((offset) => offset.partyId === item.partyId && offset.currency === item.currency)) { setLocalError(t("Apply the supplier credit or unapplied payment before preparing this payment run.")); return }
    setLocalError("")
    setSelected((current) => { const next = new Set(current); if (next.has(item.id)) next.delete(item.id); else next.add(item.id); return next })
  }
  const prepare = async () => { setBusy(true); setLocalError(""); try { await preparePaymentRun({ bankAccountId: bankId, documentIds: [...selected], paymentDate, exchangeRate: Number(exchangeRate), reason }); setRuns(await getPaymentRuns(entityId)); setSelected(new Set()); setReason(""); toast.success(t("Payment run sent for review")) } catch (cause) { setLocalError(errorText(cause)) } finally { setBusy(false) } }
  const review = async (run: PaymentRun, decision: "approved" | "rejected") => { if (!reviewReason.trim()) { setLocalError(t("Enter a review reason.")); return } setBusy(true); setLocalError(""); try { await reviewPaymentRun(run.FINPayRun_ID, decision, reviewReason); setRuns(await getPaymentRuns(entityId)); setReviewReason(""); toast.success(t(decision === "approved" ? "Payment run approved" : "Payment run rejected")) } catch (cause) { setLocalError(errorText(cause)) } finally { setBusy(false) } }
  const showAdvice = async (run: PaymentRun) => { setBusy(true); setLocalError(""); try { setAdvice(await getRemittanceAdvice(run.FINPayRun_ID)) } catch (cause) { setLocalError(errorText(cause)) } finally { setBusy(false) } }
  return <>
    {error && <InlineNotice tone="error">{t(error)}</InlineNotice>}{localError && <InlineNotice tone="error">{t(localError)}</InlineNotice>}
    <SettingsPanel title={t("Aged creditors")} description={t("Select approved open supplier invoices. A run contains one payment currency and creates one reviewed payment per supplier.")}><AgedTable items={data?.items ?? []} format={format} navigate={navigate} selected={selected} onSelect={canPrepare ? toggle : undefined} />{loading && <p className="px-5 pb-4 text-xs text-[var(--md-subtle)]">{t("Loading balances…")}</p>}</SettingsPanel>
    {data && <SettingsPanel title={t("Unapplied supplier offsets")} description={t(data.basis)}><div className="divide-y divide-[var(--md-line)]">{data.offsets.map((item) => <div key={`${item.kind}-${item.id}`} className="flex flex-wrap items-center justify-between gap-3 px-5 py-3 text-sm"><div><span className="font-medium">{item.partyName}</span><span className="ms-2 text-[var(--md-subtle)]" data-i18n-skip>{item.number} · {item.evidence.sourceTable}/{item.id.slice(0, 8)}</span></div><span className="tabular-nums" data-i18n-skip>{format(item.amount, item.currency)}</span></div>)}{!data.offsets.length && <p className="px-5 py-4 text-sm text-[var(--md-subtle)]">{t("No unapplied credits or payments.")}</p>}</div><div className="flex flex-wrap justify-end gap-4 border-t border-[var(--md-line)] px-5 py-3 text-sm font-medium">{Object.entries(data.totals).map(([code, amount]) => <span key={code} data-i18n-skip>{code} gross {format(amount.grossInvoices, code)} · offsets {format(amount.unappliedOffsets, code)} · net {format(amount.net, code)}</span>)}</div></SettingsPanel>}
    {canPrepare && <SettingsPanel title={t("Prepare payment run")} description={`${chosen.length} ${t("invoices selected")} · ${format(total, chosenCurrency)}`}>
      <div className="grid gap-3 px-5 py-4 sm:grid-cols-2 xl:grid-cols-4"><div><label htmlFor="payment-bank" className="mb-2 block text-xs font-medium">{t("Payment bank")}</label><Select value={bankId} onValueChange={setBankId}><SelectTrigger id="payment-bank"><SelectValue placeholder={t("Choose bank")} /></SelectTrigger><SelectContent>{banks.map((bank) => <SelectItem key={bank.FINBank_ID} value={bank.FINBank_ID}>{bank.FINBank_Name} · {bank.FINBank_CurrencyCode}</SelectItem>)}</SelectContent></Select></div><div><label htmlFor="payment-date" className="mb-2 block text-xs font-medium">{t("Payment date")}</label><Input id="payment-date" type="date" value={paymentDate} onChange={(event) => setPaymentDate(event.target.value)} /></div><div><label htmlFor="payment-rate" className="mb-2 block text-xs font-medium">{t("Reviewed exchange rate")}</label><Input id="payment-rate" type="number" min="0.000001" step="any" value={exchangeRate} onChange={(event) => setExchangeRate(event.target.value)} /></div><div className="sm:col-span-2 xl:col-span-4"><label htmlFor="payment-reason" className="mb-2 block text-xs font-medium">{t("Preparation reason")}</label><Textarea id="payment-reason" value={reason} onChange={(event) => setReason(event.target.value)} maxLength={500} /></div><div className="sm:col-span-2 xl:col-span-4"><Button type="button" disabled={busy || !selected.size || chosenCurrencies.length !== 1 || !bankId || !reason.trim() || !(Number(exchangeRate) > 0)} onClick={() => void prepare()}>{busy ? <LoaderCircle className="size-4 animate-spin" /> : <CreditCard className="size-4" />}{t("Request payment review")}</Button>{chosenCurrencies.length > 1 && <p role="alert" className="mt-2 text-xs text-[var(--md-red)]">{t("Prepare a separate run for each currency.")}</p>}{chosen.length > 0 && !banks.length && <p role="alert" className="mt-2 text-xs text-[var(--md-red)]">{t("No active payment bank has this currency.")}</p>}</div></div>
    </SettingsPanel>}
    <SettingsPanel title={t("Payment runs")} description={t("Approval posts controlled cash allocations to the native ledger. An external mirror queues only when configured; remittance advice stays a draft for review.")}><div className="divide-y divide-[var(--md-line)]">{runs.map((run) => <div key={run.FINPayRun_ID} className="px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="font-medium" data-i18n-skip>{run.FINPayRun_Number}</span><span className="ms-2"><StatusPill tone={tone(run.FINPayRun_StatusCode)}>{t(run.FINPayRun_StatusCode.replaceAll("_", " "))}</StatusPill></span><p className="mt-1 text-xs text-[var(--md-subtle)]" data-i18n-skip>{run.FINPayRun_PaymentDate} · {run.items.length} invoices · {format(run.FINPayRun_TotalAmount, run.FINPayRun_CurrencyCodeSnapshot)}</p></div><div className="flex flex-wrap gap-2">{run.FINPayRun_StatusCode === "awaiting_approval" && canReview && run.FINPayRun_CreatedBy !== currentUser?.internalUserId && <><Button type="button" size="sm" disabled={busy || !reviewReason.trim()} onClick={() => void review(run, "approved")}>{t("Approve")}</Button><Button type="button" size="sm" variant="outline" disabled={busy || !reviewReason.trim()} onClick={() => void review(run, "rejected")}>{t("Reject")}</Button></>}{run.FINPayRun_StatusCode === "approved" && <Button type="button" size="sm" variant="outline" disabled={busy} onClick={() => void showAdvice(run)}>{t("Review remittance")}</Button>}</div></div>{run.FINPayRun_StatusCode === "awaiting_approval" && canReview && <div className="mt-3 max-w-xl"><label htmlFor={`review-${run.FINPayRun_ID}`} className="mb-1 block text-xs font-medium">{t("Review reason")}</label><Input id={`review-${run.FINPayRun_ID}`} value={reviewReason} onChange={(event) => setReviewReason(event.target.value)} maxLength={500} /></div>}</div>)}{!runs.length && <p className="px-5 py-8 text-center text-sm text-[var(--md-subtle)]">{t("No payment runs have been prepared.")}</p>}</div></SettingsPanel>
    {advice && <section className="finance-print-sheet"><SettingsPanel title={`${t("Remittance advice") } · ${advice.run.FINPayRun_Number}`} description={t("Draft advice for operator review. Printing does not send funds or notify suppliers.")}><div className="flex justify-end px-5 py-3"><Button type="button" variant="outline" onClick={() => window.print()}>{t("Print reviewed advice")}</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead><tr className="border-b border-[var(--md-line)] text-xs"><th className="px-5 py-3 text-start">{t("Supplier")}</th><th className="px-5 py-3 text-start">{t("Invoice")}</th><th className="px-5 py-3 text-start">{t("Payment")}</th><th className="px-5 py-3 text-end">{t("Amount")}</th></tr></thead><tbody className="divide-y divide-[var(--md-line)]">{advice.lines.map((line) => <tr key={`${line.documentId}-${line.paymentNumber}`}><td className="px-5 py-3">{line.supplierName}</td><td className="px-5 py-3" data-i18n-skip>{line.documentNumber}</td><td className="px-5 py-3" data-i18n-skip>{line.paymentNumber} · {line.postingStatus}</td><td className="px-5 py-3 text-end tabular-nums" data-i18n-skip>{format(line.amount, advice.run.FINPayRun_CurrencyCodeSnapshot)}</td></tr>)}</tbody></table></div></SettingsPanel></section>}
    <style>{`@media print { body:has(.finance-print-sheet) * { visibility: hidden !important; } body:has(.finance-print-sheet) .finance-print-sheet, body:has(.finance-print-sheet) .finance-print-sheet * { visibility: visible !important; } body:has(.finance-print-sheet) .finance-print-sheet { position: absolute; inset: 0; width: 100%; } }`}</style>
  </>
}

function PurchaseOrdersWorkspace({ entityId, currency, format, currentUser, version }: { entityId: string; currency: string; format: (value: number, code?: string) => string; currentUser?: AuthUserSummary | null; version: number }) {
  const { t } = useLanguage()
  const [orders, setOrders] = useState<SupplierPurchaseOrder[]>([])
  const [options, setOptions] = useState<FinanceDraftOptions | null>(null)
  const [error, setError] = useState("")
  const [busy, setBusy] = useState(false)
  const [supplierId, setSupplierId] = useState("")
  const [jobId, setJobId] = useState("")
  const [number, setNumber] = useState("")
  const [description, setDescription] = useState("")
  const [netAmount, setNetAmount] = useState("")
  const [sourceReference, setSourceReference] = useState("")
  const [reason, setReason] = useState("")
  const canDraft = hasPermission(currentUser, "Finance.Payables.Draft")
  const canApprove = hasPermission(currentUser, "Finance.ReviewAndPost")
  useEffect(() => { let active = true; setError(""); Promise.all([getSupplierPurchaseOrders(entityId), canDraft ? getFinanceDraftOptions("payables") : Promise.resolve(null)]).then(([found, draft]) => { if (active) { setOrders(found); setOptions(draft) } }).catch((cause) => { if (active) setError(errorText(cause)) }); return () => { active = false } }, [entityId, version, canDraft])
  const create = async () => { setBusy(true); setError(""); try { await createSupplierPurchaseOrder({ legalEntityId: entityId, supplierOrgId: supplierId, jobId: jobId || null, number, currencyCode: currency, netAmount: Number(netAmount), description, sourceReference }); setOrders(await getSupplierPurchaseOrders(entityId)); setSupplierId(""); setJobId(""); setNumber(""); setDescription(""); setNetAmount(""); setSourceReference(""); toast.success(t("Supplier PO draft saved")) } catch (cause) { setError(errorText(cause)) } finally { setBusy(false) } }
  const approve = async (order: SupplierPurchaseOrder) => { setBusy(true); setError(""); try { await approveSupplierPurchaseOrder(order.FINPO_ID, reason); setOrders(await getSupplierPurchaseOrders(entityId)); setReason(""); toast.success(t("Supplier PO approved")) } catch (cause) { setError(errorText(cause)) } finally { setBusy(false) } }
  return <>
    {error && <InlineNotice tone="error">{t(error)}</InlineNotice>}
    {canDraft && <SettingsPanel title={t("New supplier PO")} description={t("This is a reviewed supplier commitment. It does not post a purchase invoice or create goods-in work.")}><div className="grid gap-3 px-5 py-4 md:grid-cols-2"><div><label htmlFor="po-supplier" className="mb-2 block text-xs font-medium">{t("Supplier")}</label><Select value={supplierId} onValueChange={setSupplierId}><SelectTrigger id="po-supplier"><SelectValue placeholder={t("Choose supplier")} /></SelectTrigger><SelectContent>{(options?.parties ?? []).map((party) => <SelectItem key={party.Org_id} value={party.Org_id}>{party.Org_Name}</SelectItem>)}</SelectContent></Select></div><div><label htmlFor="po-job" className="mb-2 block text-xs font-medium">{t("Job")}</label><Select value={jobId || "none"} onValueChange={(value) => setJobId(value === "none" ? "" : value)}><SelectTrigger id="po-job"><SelectValue placeholder={t("Optional job")} /></SelectTrigger><SelectContent><SelectItem value="none">{t("No job")}</SelectItem>{(options?.jobs ?? []).filter((job) => job.Job_LegalEntityID === entityId).map((job) => <SelectItem key={job.Job_ID} value={job.Job_ID} data-i18n-skip>{job.Job_Period}-{job.Job_Number}</SelectItem>)}</SelectContent></Select></div><div><label htmlFor="po-number" className="mb-2 block text-xs font-medium">{t("PO number")}</label><Input id="po-number" value={number} onChange={(event) => setNumber(event.target.value)} maxLength={100} /></div><div><label htmlFor="po-net" className="mb-2 block text-xs font-medium">{t("Net commitment")} · {currency}</label><Input id="po-net" type="number" min="0.01" step="0.01" value={netAmount} onChange={(event) => setNetAmount(event.target.value)} /></div><div className="md:col-span-2"><label htmlFor="po-description" className="mb-2 block text-xs font-medium">{t("Description")}</label><Textarea id="po-description" value={description} onChange={(event) => setDescription(event.target.value)} maxLength={1000} /></div><div className="md:col-span-2"><label htmlFor="po-evidence" className="mb-2 block text-xs font-medium">{t("Source reference")}</label><Input id="po-evidence" value={sourceReference} onChange={(event) => setSourceReference(event.target.value)} placeholder={t("Quote, email or approved procurement reference")} maxLength={200} /></div><div className="md:col-span-2"><Button type="button" disabled={busy || !supplierId || !number.trim() || !description.trim() || !(Number(netAmount) > 0)} onClick={() => void create()}>{t("Save PO draft")}</Button></div></div></SettingsPanel>}
    <SettingsPanel title={t("Supplier commitments")} description={t("Approved PO value is consumed only by reviewed invoice matches.")}><div className="divide-y divide-[var(--md-line)]">{orders.map((order) => <div key={order.FINPO_ID} className="flex flex-wrap items-center justify-between gap-3 px-5 py-4"><div><span className="font-medium" data-i18n-skip>{order.FINPO_Number}</span><span className="ms-2"><StatusPill tone={tone(order.FINPO_StatusCode)}>{t(order.FINPO_StatusCode)}</StatusPill></span><p className="mt-1 text-sm text-[var(--md-text)]">{order.supplierName} · {order.FINPO_Description}</p><p className="mt-1 text-xs text-[var(--md-subtle)]" data-i18n-skip>{format(numeric(order.FINPO_NetAmount), order.FINPO_CurrencyCode)} · matched {format(order.matchedNet, order.FINPO_CurrencyCode)} · FIN_SupplierPurchaseOrders/{order.FINPO_ID.slice(0, 8)}</p></div>{order.FINPO_StatusCode === "draft" && canApprove && order.FINPO_CreatedBy !== currentUser?.internalUserId && <div className="flex items-end gap-2"><div><label htmlFor={`approve-po-${order.FINPO_ID}`} className="mb-1 block text-xs font-medium">{t("Review reason")}</label><Input id={`approve-po-${order.FINPO_ID}`} value={reason} onChange={(event) => setReason(event.target.value)} maxLength={500} /></div><Button type="button" disabled={busy || !reason.trim()} onClick={() => void approve(order)}>{t("Approve")}</Button></div>}</div>)}{!orders.length && <p className="px-5 py-8 text-center text-sm text-[var(--md-subtle)]">{t("No supplier POs recorded yet.")}</p>}</div></SettingsPanel>
  </>
}

function MatchingWorkspace({ entityId, format, navigate, currentUser, version }: { entityId: string; format: (value: number, code?: string) => string; navigate: (path: string) => void; currentUser?: AuthUserSummary | null; version: number }) {
  const { t, language } = useLanguage()
  const [documents, setDocuments] = useState<FinanceDocument[]>([])
  const [documentId, setDocumentId] = useState("")
  const [suggestions, setSuggestions] = useState<MatchSuggestions | null>(null)
  const [proposals, setProposals] = useState<FinanceMatchProposal[]>([])
  const [error, setError] = useState("")
  const [reason, setReason] = useState("")
  const [busy, setBusy] = useState(false)
  const canApprove = hasPermission(currentUser, "Finance.ReviewAndPost")
  useEffect(() => { let active = true; setDocuments([]); setSuggestions(null); setProposals([]); setDocumentId(""); getFinanceDocuments("payables").then((value) => { if (active) setDocuments(value.documents.filter((document) => document.FINDoc_LegalEntityID === entityId && document.FINDoc_TypeCode === "pl_invoice" && ["draft", "awaiting_approval"].includes(document.FINDoc_StatusCode))) }).catch((cause) => { if (active) setError(errorText(cause)) }); return () => { active = false } }, [entityId, version])
  const inspect = async (id: string) => { setDocumentId(id); setSuggestions(null); setProposals([]); setError(""); if (!id) return; try { const [matches, history] = await Promise.all([getSupplierInvoiceMatchSuggestions(id), getFinanceMatchProposals(id)]); setSuggestions(matches); setProposals(history) } catch (cause) { setError(errorText(cause)) } }
  const propose = async () => { setBusy(true); setError(""); try { await generateFinanceMatchProposal(documentId); setProposals(await getFinanceMatchProposals(documentId)); toast.success(t("Source-cited AI proposal saved for review")) } catch (cause) { setError(errorText(cause)) } finally { setBusy(false) } }
  const reject = async (proposal: FinanceMatchProposal) => { if (!reason.trim()) return; setBusy(true); setError(""); try { await rejectFinanceMatchProposal(proposal.FINMatchProposal_ID, reason); setProposals(await getFinanceMatchProposals(documentId)); setReason(""); toast.success(t("AI proposal rejected with reason")) } catch (cause) { setError(errorText(cause)) } finally { setBusy(false) } }
  const approve = async (candidate: MatchSuggestions["candidates"][number]) => { if (!suggestions) return; setBusy(true); setError(""); try { const proposal = proposals.find((item) => item.FINMatchProposal_StatusCode === "pending" && item.FINMatchProposal_PurchaseOrderID === candidate.id); await approveSupplierInvoiceMatch(documentId, candidate.id, reason, proposal?.FINMatchProposal_ID); const [matches, history] = await Promise.all([getSupplierInvoiceMatchSuggestions(documentId), getFinanceMatchProposals(documentId)]); setSuggestions(matches); setProposals(history); setReason(""); toast.success(t("Supplier invoice matched to PO")) } catch (cause) { setError(errorText(cause)) } finally { setBusy(false) } }
  return <>
    {error && <InlineNotice tone="error">{t(error)}</InlineNotice>}
    <SettingsPanel title={t("Review invoice")} description={t("Open draft supplier invoices can be matched before posting. A match records evidence but never changes tax, totals or posting status.")}><div className="max-w-xl px-5 py-4"><label htmlFor="matching-document" className="mb-2 block text-xs font-medium">{t("Supplier invoice")}</label><Select value={documentId} onValueChange={(value) => void inspect(value)}><SelectTrigger id="matching-document"><SelectValue placeholder={t("Choose draft invoice")} /></SelectTrigger><SelectContent>{documents.map((document) => <SelectItem key={document.FINDoc_ID} value={document.FINDoc_ID}>{document.FINDoc_Number || t("Unnumbered")} · {document.partyName} · {format(numeric(document.FINDoc_NetAmount), document.FINDoc_CurrencyCodeSnapshot)}</SelectItem>)}</SelectContent></Select>{!documents.length && <p className="mt-3 text-xs text-[var(--md-subtle)]">{t("No draft supplier invoices are available for matching.")}</p>}</div></SettingsPanel>
    {suggestions && <SettingsPanel title={t("Suggested PO matches")} description={t("Rule-ranked suggestions compare the exact supplier, currency, job and remaining net value. Read the source invoice and PO before approving.")}><div className="flex flex-wrap items-center gap-3 px-5 pt-4 text-xs text-[var(--md-subtle)]"><button type="button" className="text-[var(--md-accent)] hover:underline" onClick={() => navigate(`/finance/payables/documents/${documentId}`)}>{t("Open source invoice")}</button><span data-i18n-skip>FIN_Documents/{documentId.slice(0, 8)} · {suggestions.ruleVersion}</span>{canApprove && !suggestions.existing && suggestions.candidates.some((candidate) => !candidate.conflicts.length) && <Button type="button" size="sm" variant="outline" disabled={busy} onClick={() => void propose()}>{t("Generate AI review proposal")}</Button>}</div>{suggestions.existing ? <InlineNotice>{t("This invoice already has an approved PO match.")}</InlineNotice> : null}<div className="divide-y divide-[var(--md-line)]">{suggestions.candidates.map((candidate) => <div key={candidate.id} className="flex flex-wrap items-start justify-between gap-4 px-5 py-4"><div><p className="font-medium" data-i18n-skip>{candidate.number} · {format(candidate.available)}</p><p className="mt-1 text-xs text-[var(--md-text)]">{candidate.reasons.map(t).join(" · ")}</p><p className="mt-1 text-[11px] text-[var(--md-subtle)]" data-i18n-skip>FIN_SupplierPurchaseOrders/{candidate.id.slice(0, 8)} · rule score {candidate.score}</p>{candidate.conflicts.map((conflict) => <p key={conflict} role="alert" className="mt-1 text-xs text-[var(--md-red)]">{t(conflict)}</p>)}</div>{canApprove && !suggestions.existing && <Button type="button" size="sm" disabled={busy || candidate.conflicts.length > 0 || !reason.trim()} onClick={() => void approve(candidate)}>{t("Approve match")}</Button>}</div>)}{!suggestions.candidates.length && <p className="px-5 py-8 text-center text-sm text-[var(--md-subtle)]">{t("No approved PO matches this supplier and currency. Review supplier or create a PO.")}</p>}</div>{canApprove && !suggestions.existing && suggestions.candidates.length > 0 && <div className="max-w-xl px-5 pb-5"><label htmlFor="match-reason" className="mb-2 block text-xs font-medium">{t("Reviewer note")}</label><Textarea id="match-reason" value={reason} onChange={(event) => setReason(event.target.value)} placeholder={t("Explain the invoice, PO and value evidence.")} maxLength={500} /></div>}</SettingsPanel>}
    {proposals.length > 0 && <SettingsPanel title={t("AI proposal history")} description={t("Model advice is saved with source fields, file identity, model version and every reviewer decision. It never approves a match by itself.")}><div className="divide-y divide-[var(--md-line)]">{proposals.map((proposal) => <div key={proposal.FINMatchProposal_ID} className="space-y-2 px-5 py-4 text-sm"><div className="flex flex-wrap items-center gap-2"><StatusPill tone={tone(proposal.FINMatchProposal_StatusCode)}>{t(proposal.FINMatchProposal_StatusCode)}</StatusPill><span data-i18n-skip>{proposal.FINMatchProposal_Model} · {proposal.FINMatchProposal_PromptVersion} · {new Intl.DateTimeFormat(language, { dateStyle: "medium", timeStyle: "short" }).format(new Date(proposal.FINMatchProposal_CreatedAt))}</span></div><p>{proposal.FINMatchProposal_ResultJSON.rationale}</p><p className="text-xs text-[var(--md-subtle)]" data-i18n-skip>{proposal.FINMatchProposal_PurchaseOrderID ? `Suggested FIN_SupplierPurchaseOrders/${proposal.FINMatchProposal_PurchaseOrderID.slice(0, 8)}` : "No PO recommended"}{proposal.FINMatchProposal_SourceJSON.document.fileName ? ` · ${proposal.FINMatchProposal_SourceJSON.document.fileName}` : ""}</p><ul className="space-y-1 text-xs text-[var(--md-subtle)]">{proposal.FINMatchProposal_ResultJSON.citations.map((citation, index) => <li key={`${citation.field}-${index}`} data-i18n-skip>{citation.field}: {String(citation.value ?? "not recorded")} · {citation.table}/{citation.recordId.slice(0, 8)}{citation.fileSha256 ? ` · file SHA-256 ${citation.fileSha256.slice(0, 12)}…` : ""}</li>)}</ul>{proposal.FINMatchProposal_ReviewReason && <p className="text-xs">{t("Reviewer decision")}: {proposal.FINMatchProposal_ReviewReason}</p>}{proposal.FINMatchProposal_StatusCode === "pending" && canApprove && !suggestions?.existing && <Button type="button" size="sm" variant="outline" disabled={busy || !reason.trim()} onClick={() => void reject(proposal)}>{t("Reject proposal with note")}</Button>}</div>)}</div></SettingsPanel>}
  </>
}

function ProfitabilityWorkspace({ entityId, format, navigate, version }: { entityId: string; format: (value: number, code?: string) => string; navigate: (path: string) => void; version: number }) {
  const { t } = useLanguage()
  const [data, setData] = useState<JobProfitability | null>(null)
  const [error, setError] = useState("")
  const [loading, setLoading] = useState(true)
  useEffect(() => { let active = true; setLoading(true); setError(""); getJobProfitability(entityId).then((value) => { if (active) setData(value) }).catch((cause) => { if (active) setError(errorText(cause)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [entityId, version])
  return <>{error && <InlineNotice tone="error">{t(error)}</InlineNotice>}<SettingsPanel title={t("Job gross profit")} description={t("Expected margin uses the current charge estimate. Recognised margin includes posted invoice net and outstanding WIP or accrual; open balances are not counted twice.")}>
    {loading && <p className="px-5 py-5 text-sm text-[var(--md-subtle)]">{t("Loading job profitability…")}</p>}
    <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-[var(--md-line)] text-xs text-[var(--md-subtle)]"><th className="px-5 py-3 text-start">{t("Job")}</th><th className="px-5 py-3 text-end">{t("Expected revenue")}</th><th className="px-5 py-3 text-end">{t("Expected cost")}</th><th className="px-5 py-3 text-end">{t("Actual revenue / cost")}</th><th className="px-5 py-3 text-end">{t("Open WIP / accrual")}</th><th className="px-5 py-3 text-end">{t("Recognised GP")}</th></tr></thead><tbody className="divide-y divide-[var(--md-line)]">{(data?.jobs ?? []).map((job) => <tr key={job.id}><td className="px-5 py-3"><details><summary className="cursor-pointer font-medium text-[var(--md-accent)] focus-visible:outline-2 focus-visible:outline-[var(--md-accent)]" data-i18n-skip>{job.reference}</summary><div className="mt-3 min-w-80 space-y-2 text-xs text-[var(--md-text)]">{job.charges.map((charge) => <div key={String(charge.FINChargeProfit_JobCostingLineID)}><span data-i18n-skip>{String(charge.FINChargeProfit_ChargeCode ?? "—")} · {String(charge.FINChargeProfit_Description ?? "")}</span><span className="block" data-i18n-skip>Actual {format(numeric(charge.FINChargeProfit_ActualRevenue))} / {format(numeric(charge.FINChargeProfit_ActualCost))} · WIP {format(numeric(charge.FINChargeProfit_OpenWIP))} · accrual {format(numeric(charge.FINChargeProfit_OpenAccrual))}</span><span className="block text-[var(--md-subtle)]" data-i18n-skip>Job_Costing_Lines/{String(charge.FINChargeProfit_JobCostingLineID).slice(0, 8)}</span></div>)}</div></details><button type="button" className="mt-1 text-xs text-[var(--md-accent)] hover:underline" onClick={() => navigate(`/jobs/${job.id}`)}>{t("Open job")}</button></td><td className="px-5 py-3 text-end tabular-nums" data-i18n-skip>{format(job.expectedRevenue)}</td><td className="px-5 py-3 text-end tabular-nums" data-i18n-skip>{format(job.expectedCost)}</td><td className="px-5 py-3 text-end tabular-nums" data-i18n-skip>{format(job.actualRevenue)} / {format(job.actualCost)}</td><td className="px-5 py-3 text-end tabular-nums" data-i18n-skip>{format(job.openWip)} / {format(job.openAccrual)}</td><td className="px-5 py-3 text-end font-medium tabular-nums" data-i18n-skip>{format(job.grossProfit)}</td></tr>)}{!loading && !data?.jobs.length && <tr><td colSpan={6} className="px-5 py-10 text-center text-[var(--md-subtle)]">{t("No jobs have charge profitability records.")}</td></tr>}</tbody></table></div>
  </SettingsPanel></>
}
