import { useCallback, useEffect, useState } from "react"
import { Calculator } from "@/components/icons/hugeicons"
import { SettingsPageHeader, SettingsPanel } from "@/components/multideck/settings-components"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { useLanguage } from "@/i18n/language-provider"
import { hasPermission, type AuthUserSummary } from "@/lib/auth-user"
import { getGlEntities, type GlEntity } from "@/lib/finance-ledger-api"
import { providerPeriod, providerSetup, reviewProviderDifference, runProviderPeriod, type BankPeriod, type ProviderConnection, type ProviderDifference, type ProviderPeriodStatus } from "@/lib/finance-reconciliation-api"

const selectClass = "h-9 w-full rounded-[var(--md-radius-md)] bg-[var(--md-surface-soft)] px-2 text-[13px] text-[var(--md-ink)] focus-visible:outline-2 focus-visible:outline-[var(--md-accent)]"
const kindLabel: Record<string, string> = { external_only: "External-only change", missing_provider: "Missing in accounts system", conflict: "Concurrent conflict", changed: "Changed record", duplicate_local: "Duplicate Multideck identity", duplicate_provider: "Duplicate provider identity" }

export function FinanceProviderReconciliationPage({ currentUser }: { currentUser?: AuthUserSummary | null }) {
  const { t } = useLanguage()
  const canRun = hasPermission(currentUser, "Finance.Integration.Manage"), canReview = hasPermission(currentUser, "Finance.Management.Approve")
  const [entities, setEntities] = useState<GlEntity[]>([]), [entityId, setEntityId] = useState("")
  const [connections, setConnections] = useState<ProviderConnection[]>([]), [periods, setPeriods] = useState<BankPeriod[]>([])
  const [connectionId, setConnectionId] = useState(""), [periodId, setPeriodId] = useState("")
  const [status, setStatus] = useState<ProviderPeriodStatus | null>(null), [differences, setDifferences] = useState<ProviderDifference[]>([]), [offset, setOffset] = useState(0)
  const [reason, setReason] = useState(""), [reviewAction, setReviewAction] = useState<Record<string, "prepare_draft" | "requires_adjustment" | "expected_difference">>({})
  const [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(""), [notice, setNotice] = useState("")
  const connection = connections.find(row => row.ACCIC_ID === connectionId)
  useEffect(() => { let active = true; void getGlEntities().then(result => { if (active) { setEntities(result.entities); setEntityId(result.entities[0]?.LegalEntity_ID || "") } }).catch(cause => { if (active) setError(cause instanceof Error ? cause.message : "Could not load legal entities.") }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [])
  useEffect(() => { if (!entityId) return; let active = true; setLoading(true); setConnectionId(""); setPeriodId(""); setStatus(null); setDifferences([]); void providerSetup(entityId).then(result => { if (active) { setConnections(result.connections); setPeriods(result.periods); setConnectionId(result.connections[0]?.ACCIC_ID || ""); setPeriodId(result.periods[0]?.FINPeriod_ID || "") } }).catch(cause => { if (active) setError(cause instanceof Error ? cause.message : "Could not load accounting connections.") }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [entityId])
  const refresh = useCallback(async (page = 0) => { if (!entityId || !connectionId || !periodId) return; setLoading(true); setError(""); try { const result = await providerPeriod(entityId, periodId, connectionId, page); setStatus(result.status); setDifferences(result.differences); setOffset(page) } catch (cause) { setStatus(null); setDifferences([]); setError(cause instanceof Error ? cause.message : "Could not load provider reconciliation.") } finally { setLoading(false) } }, [entityId, connectionId, periodId])
  useEffect(() => { void refresh(0) }, [refresh])
  const run = async () => { setBusy(true); setError(""); setNotice(""); try { const result = await runProviderPeriod(entityId, periodId, connectionId); setNotice(result.status === "verified" ? "The complete provider period comparison verified." : result.status === "differences" ? `${result.differenceCount} differences were staged for review. No accounting entries were changed.` : "The provider period comparison is incomplete. Review the missing evidence before relying on it."); await refresh(0) } catch (cause) { setError(cause instanceof Error ? cause.message : "The provider comparison failed.") } finally { setBusy(false) } }
  const review = async (difference: ProviderDifference) => { const action = reviewAction[difference.id] || (difference.kind === "external_only" ? "prepare_draft" : "requires_adjustment"); setBusy(true); setError(""); try { await reviewProviderDifference(entityId, difference.id, action, reason); setNotice("Review decision recorded. The period still needs a successful recheck before it can verify."); await refresh(offset) } catch (cause) { setError(cause instanceof Error ? cause.message : "The review decision could not be saved.") } finally { setBusy(false) } }
  return <>
    <SettingsPageHeader title={t("Accounts system reconciliation")} description={t("Compare each period’s documents, cash allocations, tax, journal lines, trial balance and AR/AP/cash controls with the exact connected company.")} icon={Calculator} descriptionPlacement="under-title" actions={<Button variant="outline" onClick={() => void refresh(offset)} disabled={busy || loading}>{t("Refresh")}</Button>} />
    <div className="mt-[var(--md-page-stack-gap)] space-y-[var(--md-page-stack-gap)]">
      {error ? <p role="alert" className="text-[13px] text-[var(--md-red)]">{t(error)}</p> : null}
      {notice ? <p role="status" className="text-[13px] text-[var(--md-green)]">{t(notice)}</p> : null}
      <SettingsPanel title={t("Comparison scope")} description={t("Runs retain source cut-off, page counts, source hashes and review differences. A partial or stale read is incomplete.")}>
        <div className="grid gap-3 sm:grid-cols-3">
          <label className="space-y-1 text-[12px] text-[var(--md-text)]">{t("Legal entity")}<select className={selectClass} value={entityId} onChange={event => setEntityId(event.target.value)} disabled={busy}>{entities.map(entity => <option key={entity.LegalEntity_ID} value={entity.LegalEntity_ID}>{entity.LegalEntity_Name}</option>)}</select></label>
          <label className="space-y-1 text-[12px] text-[var(--md-text)]">{t("Accounts system")}<select className={selectClass} value={connectionId} onChange={event => setConnectionId(event.target.value)} disabled={busy}>{connections.map(item => <option key={item.ACCIC_ID} value={item.ACCIC_ID}>{item.ACCIC_Name} · {item.ACCIC_ExternalTenantName}</option>)}</select></label>
          <label className="space-y-1 text-[12px] text-[var(--md-text)]">{t("Period")}<select className={selectClass} value={periodId} onChange={event => setPeriodId(event.target.value)} disabled={busy}>{periods.map(item => <option key={item.FINPeriod_ID} value={item.FINPeriod_ID}>{item.FINPeriod_Code} · {item.FINPeriod_StartDate}–{item.FINPeriod_EndDate}</option>)}</select></label>
        </div>
        {connection?.ACCIC_ProviderCode === "sage_50" && <p className="mt-3 text-[12px] text-[var(--md-text)]">{t("Sage 50 uses the tenant HyperExt connector. Its company, SDO/ODBC and nominal reads are checked; unsupported complete ledger paging remains an explicit incomplete result.")}</p>}
        {canRun && connection && periodId && <Button className="mt-3" disabled={busy || loading} onClick={() => void run()}>{t(busy ? "Comparing…" : "Run period comparison")}</Button>}
      </SettingsPanel>
      {loading ? <p role="status" className="text-[13px] text-[var(--md-text)]">{t("Loading provider reconciliation…")}</p> : status ? <SettingsPanel title={t("Latest run")} description={t(status.status === "verified" ? "All required pages, identities, journal lines and controls matched at this cut-off. The evidence expires when stale or when new changes arrive." : status.status === "differences" ? "Differences are staged for authorised review. A fresh complete run is required after resolution." : status.reason || "The source read or mapped accounting evidence is incomplete.")}>
        <p className={`text-[13px] font-medium ${status.status === "verified" ? "text-[var(--md-green)]" : status.status === "differences" ? "text-[var(--md-red)]" : "text-[var(--md-amber)]"}`}>{t(({ verified: "Verified", differences: "Differences", incomplete: "Incomplete" })[status.status])}</p>
        {status.asOf && <p className="mt-1 text-[12px] text-[var(--md-text)]">{t("Source cut-off")}: <time data-i18n-skip dateTime={status.asOf}>{status.asOf}</time></p>}
        {typeof status.differenceCount === "number" && <p className="mt-1 text-[12px] text-[var(--md-text)]">{t("Differences")}: <span data-i18n-skip>{status.differenceCount}</span></p>}
        {!!status.issues?.length && <ul className="mt-3 list-inside list-disc space-y-1 text-[12px] text-[var(--md-red)]">{status.issues.map((issue, index) => <li key={index}>{t(issue)}</li>)}</ul>}
      </SettingsPanel> : null}
      {!!differences.length && <SettingsPanel title={t("Differences for review")} description={t("Provider-originated records stay as evidence. A review decision does not post, import or resolve a difference; run the comparison again after the controlled correction.")}>
        {canReview && <label className="mb-3 block max-w-xl space-y-1 text-[12px] text-[var(--md-text)]">{t("Review reason")}<Input value={reason} onChange={event => setReason(event.target.value)} maxLength={1000} disabled={busy} /></label>}
        <div className="divide-y divide-[var(--md-line)]">{differences.map(difference => <article key={difference.id} className="space-y-2 py-3 text-[12px]"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-medium text-[var(--md-ink)]">{t(kindLabel[difference.kind] || difference.kind)} · {t(difference.domain.replaceAll("_", " "))}</p><p className="break-all text-[var(--md-text)]" data-i18n-skip>{difference.identity}</p></div><span className="text-[var(--md-text)]">{t(difference.review_status)}</span></div><div className="grid gap-2 sm:grid-cols-2"><div><p className="font-medium">{t("Multideck")}</p><pre className="mt-1 whitespace-pre-wrap break-all rounded-[var(--md-radius-md)] bg-[var(--md-surface-soft)] p-2 font-sans" data-i18n-skip>{JSON.stringify(difference.local_snapshot?.values ?? null, null, 2)}</pre></div><div><p className="font-medium">{t("Accounts system")}</p><pre className="mt-1 whitespace-pre-wrap break-all rounded-[var(--md-radius-md)] bg-[var(--md-surface-soft)] p-2 font-sans" data-i18n-skip>{JSON.stringify(difference.provider_snapshot?.values ?? null, null, 2)}</pre></div></div>{difference.review_status === "pending" && canReview && <div className="flex flex-wrap gap-2"><select className={selectClass} aria-label={t("Review action")} value={reviewAction[difference.id] || (difference.kind === "external_only" ? "prepare_draft" : "requires_adjustment")} onChange={event => setReviewAction(current => ({ ...current, [difference.id]: event.target.value as "prepare_draft" | "requires_adjustment" | "expected_difference" }))}><option value="requires_adjustment">{t("Requires adjustment")}</option>{difference.kind === "external_only" || difference.kind === "changed" ? <option value="prepare_draft">{t("Propose draft preparation")}</option> : null}<option value="expected_difference">{t("Record expected difference")}</option></select><Button size="sm" disabled={busy || reason.trim().length < 10} onClick={() => void review(difference)}>{t("Record decision")}</Button></div>}{difference.review_reason && <p className="text-[var(--md-text)]">{t("Review reason")}: <span data-i18n-skip>{difference.review_reason}</span></p>}</article>)}</div>
        <div className="mt-3 flex justify-between gap-2"><Button variant="outline" disabled={loading || offset === 0} onClick={() => void refresh(Math.max(0, offset - 100))}>{t("Previous")}</Button><Button variant="outline" disabled={loading || differences.length < 100} onClick={() => void refresh(offset + 100)}>{t("Next")}</Button></div>
      </SettingsPanel>}
    </div>
  </>
}
